### ISSUE TITLE
aiohttp issues with pyodide accessing https url

### ISSUE THREAD

**Issue by syleishere** [fafhrd91/aiohttp#10110]
### Describe the bug

https://github.com/pyodide/pyodide/issues/5239

### To Reproduce

https://github.com/pyodide/pyodide/issues/5239

### Expected behavior

Should be able to access a https url in pyodide

### Logs/tracebacks

```python-traceback
https://github.com/pyodide/pyodide/issues/5239
```

### Python Version

```console
3.12.7
```

### aiohttp Version

```console
latest version or pyodide version
```

### multidict Version

```console
latest version or pyodide version
```

### propcache Version

```console
latest version or pyodide version
```

### yarl Version

```console
latest version or pyodide version
```

### OS

web, or a flutter macos build

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
We're probably not going to be able to debug pyodide for you. If the pyodide developers figure out what is the problem and there's something we can change to resolve it, then we'll look at it. But, the linked report just looks like pyodide is missing some basic functionality, it's not clear what we'd do about that (I'd note that they appear to be maintaining a patch to our code already).

**Comment by syleishere** [comment]
Yeah, not sure why aiohttp is listed as supported on pyodide, main purpose of aiohttp is to connect to https url and return a result lol. Almost seems as if they have to patch aiohttp with calls from https://pyodide.org/en/stable/usage/api/python-api/http.html

**Comment by hoodmane** [comment]
This would be fixed if #7803 got completed and merged. It's listed as "supported" in the automatically generated documentation because we build it and we don't currently have a way to indicate that we build it but it doesn't really work. We should have that though because there are other packages that we build and include for some reason or another but are partially or entirely broken.

**Comment by asvetlov** [comment]
aiohttp is built on top of asyncio.
In turn, pyodide doesn't support asyncio. For example, the socket is missing.
In this case, I doubt if we can provide a full set of aiohttp functionality for pyodide platform.

**Comment by hoodmane** [comment]
Certainly not the full functionality. But JS runtimes have their own async http apis with similar APIs although they have some additional limitations on what headers we can set and such. Using lower level APIs is not likely to work. But a large number of users just need to make some requests with certain headers and maybe a timeout. Downstream libraries that do want more detailed control may also need some modification to get around these limitations. But I think it's preferable that they can do it with the same library to keep changes to support Emscripten small. 

Here's similar PRs for urllib3 and httpx:
https://github.com/encode/httpx/pull/3330
https://github.com/urllib3/urllib3/pull/3195

**Comment by Dreamsorcerer** [comment]
Yeah, I think the approach in the PR is fine (using custom connector, request and response classes). Seems like this issue is invalid then, as pyodide support simply doesn't exist yet.
