### ISSUE TITLE
Response is "falsy"

### ISSUE THREAD

**Issue by Derkades** [fafhrd91/aiohttp#10119]
### Describe the bug

`bool(web.Response())` evaluates to False. I suspect this is because Response inherits from MutableMapping.

This may cause confusion when checking for `if response:` instead of `if response is not None`. 

### To Reproduce

```
>>> response = web.Response()
>>> bool(response)
False
>>> response["a"] = 1
>>> bool(response)
True
```

### Expected behavior

I personally think Response should always be "truthy". 

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
3.13.0
```

### aiohttp Version

```console
3.11.9
```

### multidict Version

```console
6.1.0
```

### propcache Version

```console
0.2.0
```

### yarl Version

```console
1.17.1
```

### OS

Fedora 41

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
It's a minor point, but feel free to make a PR to change it to True.

**Comment by Derkades** [comment]
I do agree that `is None` should be preferred, but sometimes I get lazy and just check `if response`. Then it takes me a while for me to figure out the resulting bug, but that might just be me.

It is a breaking change, so I can understand not wanting to change the existing behaviour.

**Comment by Dreamsorcerer** [comment]
I still slightly agree that it should always be True. The mapping functionality is a minor part of the Response functionality, so I don't think it should define the bool state (I can't think of any use for this). But, I don't feel strongly about it.

**Comment by Derkades** [comment]
I see `Application`, which is also inherits from MutableMapping, already has `__bool__` with `return True` and even a test to assert this behaviour. So there certainly is precedent
