### ISSUE TITLE
HTTPFound is marked as deprecated, so what should I use for redirects?

### ISSUE THREAD

**Issue by rafa-br34** [fafhrd91/aiohttp#10165]
### Describe the bug

All the examples on the aiohttp documentation use `HTTPFound` for redirects, but they're also deprecated and will be removed soon, so I want to know the most future-proof way to implement redirects.

### To Reproduce

Use `raise HTTPFound`

### Expected behavior

Example code that doesn't use deprecated features

### Logs/tracebacks

```python-traceback
The code works fine
```

### Python Version

```console
Python 3.12.0
```

### aiohttp Version

```console
3.10.10
```

### multidict Version

```console
6.1.0
```

### propcache Version

```console
0.2.0
```

### yarl Version

```console
1.16.0
```

### OS

Microsoft Windows 10

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Where do you see this deprecation? I don't see anything saying it's deprecated and will be removed.

The 302 status code is deprecated from HTTP, but if you know this then you should already know the correct codes (i.e. 303 and 307) (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes). Exceptions for all codes are in the docs: https://docs.aiohttp.org/en/stable/web_quickstart.html#exceptions

**Comment by rafa-br34** [comment]
Ok.. but what's the 
> Returning [HTTPException](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.HTTPException) or its subclasses is deprecated and will be removed in subsequent aiohttp versions.

part about? Is it actually *returning* the deprecated exceptions or *raising* them? And no I wasn't aware that 302 was deprecated from HTTP, but in theory, any subclass under `HTTPException` is deprecated (including `HTTPSeeOther` and `HTTPSeeOther`) no?

**Comment by webknjaz** [comment]
Yes. You should raise instead of returning.

**Comment by webknjaz** [comment]
It might be useful to rephrase the docs if that causes confusion, it seems.

**Comment by rafa-br34** [comment]
> Yes. You should raise instead of returning.

That explains it. Raising or returning in the context of the handler is kind of the same thing. (obviously, they have a totally different mechanism behind it, but the documentation doesn't clarify that raising is still fine).

**Comment by Dreamsorcerer** [comment]
Yep, returning an exception won't work in v4, raising is required (and highly recommended in v3 as some middlewares etc. won't work correctly otherwise).
