### ISSUE TITLE
Python hangs when importing aiohttp (memory leak)

### ISSUE THREAD

**Issue by amasend** [fafhrd91/aiohttp#10170]
### Describe the bug

After installation of `aiohttp` in version `3.10.6` or above I cannot run any Python code where `aiohttp` is imported.
`aiohttp` version `3.10.5` works fine.
I cannot even run the simplest python code like:

```python
import aiohttp
```

In the task manager, I can see that system spawned few python processes at once with some of the python processes that consume ~ 14GB of RAM. But sometimes I can see only 1 python process spawned that consumes ~ 1GB of memory but increases through time endlessly.
And after that nothing happen, python just freeze.

In addition:
I have python installed through `pyenv` and used a virtual env through `poetry`.
`Poetry (version 1.8.2)`
`pyenv 2.3.36`
I've reproduced it on a clean environment only with `aiohttp` installed, nothing more.

### To Reproduce

1. Create simple python script:
```python
import aiohttp
```
2. Run this script with `python ./script_name.py`
3. Python start running but nothing else happen, just freeze.

### Expected behavior

I am expecting that simple `import aiohttp` does not hang entire python process.

### Logs/tracebacks

Below attached a traceback of python execution (from aiohttp 3.11.10).
Attached logs from python:
[logs.zip](https://github.com/user-attachments/files/18164833/logs.zip)

### Python Version

```console
$ python --version
Python 3.11.3
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Version: >= 3.10.6
```

### multidict Version

```console
$ python -m pip show multidict
Version: >= 4.7.6
```

### propcache Version

```console
$ python -m pip show propcache
Version: >= 0.2.1
```

### yarl Version

```console
$ python -m pip show yarl
Version: >= 1.18.3
```

### OS

macOS Version 14.7.1 (23H222)
Intel chip.

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
Sorry, I cannot reproduce.
Everything works fine on my box.

**Comment by Dreamsorcerer** [comment]
I'm afraid you'll need to do some more debugging. We probably have millions of users and you're the first to report this. Many developers are on similar environment setups without issue.

Can you reproduce it from running the Git repo locally (e.g. while checked out on the 3.10 branch)? If so, can you do a git bisect or similar and see what commit actually causes the issue for you.

**Comment by amasend** [comment]
Sure, I'll try, also I'll try to reproduce it inside other envs and other developer workstations.

**Comment by amasend** [comment]
Closing as it appears that I had corrupted python installation. When I managed to install everything via `uv` all the versions work fine. Sorry for confusion.
