### ISSUE TITLE
Possibility to pass `base_url` parameter in request methods

### ISSUE THREAD

**Issue by rnv812** [fafhrd91/aiohttp#10187]
### Is your feature request related to a problem?

I have a scenario where for each request I need to change host (post bulk requests to ElasticSearch cluster nodes).

### Describe the solution you'd like

It would be nice to be able to pass `base_url` as request method argument that has priority over `base_url` initialized from  `__init__`. All the logic of joining urls is delegated to library.

### Describe alternatives you've considered

- I think to set it via assignment to `session._base_url` protected attribute is not possibly safe way due to asynchronous execution.

- We could also use `url` parameter to build full url, but in this case we can encounter next problems:
![image](https://github.com/user-attachments/assets/e39eb89c-d8fc-4499-8c1b-7776db9efd60)

- Also we could create `yarl.URL` objects for parts of URL, joining them and pass to `url` parametersr, but as I said before I think this logic should be delegated to library.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Adding a base_url parameter sounds like a weird design.
Anyway, I think #10074 in 3.12 will solve your issue, just pass the full URL.

**Comment by rnv812** [comment]
Ok, thank you
