### ISSUE TITLE
HTTP2 support

### ISSUE THREAD

**Issue by tob123** [fafhrd91/aiohttp#10185]
### Is your feature request related to a problem?

http1.1 is inefficient and slow in case of tls and large requests

### Describe the solution you'd like

support for h2 / http2

### Describe alternatives you've considered

use a different python module: httpx

### Related component

Client

### Additional context

it looks like http3 support is in progress here: https://github.com/aio-libs/aiohttp/issues/5999 (?). but this feature request is from 2021 so not sure whether it is still alive.
then there was a http2 support ticket here: https://github.com/aio-libs/aiohttp/issues/5631
but it was closed ?
note: support for http2 is there on many webservers now (compared to 2021 / 2022). so my thought was give this another bump..

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
Thanks for raising the question.
No, there is no is-progress work on http2 AFAIK.
The request is waiting for the champion, and it is not a low hanging fruit!

**Comment by Dreamsorcerer** [comment]
> it looks like http3 support is in progress here: #5999 (?). but this feature request is from 2021 so not sure whether it is still alive.

Nobody has volunteered to work on it, so it hasn't been started. The discussion is around HTTP/2 as well, I've updated the title there and will close this as a duplicate.

If you really want it, feel free to start working on a solution. But, I doubt you'll see a big difference in performance.
