### ISSUE TITLE
Please Add Host Resolver Rules

### ISSUE THREAD

**Issue by ghost** [fafhrd91/aiohttp#10287]
### Is your feature request related to a problem?

I am in China and  I want to make a tool to scan ip and port which can access blocked websites. 
I have written a tool to bypass DPI, it's a http proxy.

When i scan ip, I need to send a request to a current ip, not the proxy to resolve the ip.

### Describe the solution you'd like

Add a param like `resolve="127.0.0.1:2500"` of `get`. 

### Describe alternatives you've considered

I've tried to redine some funtions, but failed.

An way to do this is to modify the CONNECT:
On the first line:
```
CONNECT www.python.org:443 HTTP/1.1
```

simply modify it to
```
CONNECT 127.0.0.1:80 HTTP/1.1
```

is okay. 

### Related component

Client

### Additional context

`curl` on unix like support `--resolve`. 

So you can use:
```bash
curl  https://www.google.com.hk -x 127.0.0.1:2500 --resolve www.google.com.hk:1445:35.190.240.148
```

---

notice the differences of sni on tls layer, host on http layer and ip on AF_NET layer! 

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Lanius-collaris** [comment]
Can be implemented with a custom _connector_.
https://docs.aiohttp.org/en/stable/client_advanced.html#connectors
https://docs.aiohttp.org/en/stable/client_reference.html#connectors
