### ISSUE TITLE
Elaborate meaning of arguments `allow_redirects`, `max_redirects` for `ClientSession.request` (and related functions) in documentation

### ISSUE THREAD

**Issue by asrelo** [fafhrd91/aiohttp#10282]
### Is your feature request related to a problem?

It took me more time to realize how the arguments `allow_redirects: bool` and `max_redirects: int` to the method [`ClientSession.request`](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.request) aren't redundant than it should have.

Currently they are described as follows:

> * **allow_redirects** (*bool*) – If set to `False`, do not follow redirects. `True` by default (optional).
> * **max_redirects** (*int*) – Maximum number of redirects to follow. `10` by default.

This creates impression that `allow_redirects=False` should have about the same effect as `max_redirects=0`, which is incorrect. By inspecting source code I understood that `allow_redirects` switches if any attempt to process redirects is ever done (logging redirecting responses and potentially raising an exception) or the redirecting response is returned to the user.

### Describe the solution you'd like

Change description of the named parameters in the docs to show how `allow_redirects` affects what a user gets and what side effects are made.

A variant of changes:

> * **allow_redirects** (*bool*) – Whether to process redirects or not. When `True`, redirects are followed (up to `max_redirects` times) and logged into `ClientResponse.history` and `trace_configs`. When `False`, the first redirecting response is returned. `True` by default (optional).
> * **max_redirects** (*int*) – Maximum number of redirects to follow. `TooManyRedirects` is raised when the number is exceeded. Ignored if `allow_redirects=False`. `10` by default.

### Describe alternatives you've considered

N/A

### Related component

Client

### Additional context

Similar problem exists with descriptions of arguments `allow_redirects` and `max_redirects` in other functions:

* `ClientSession.get`
* `ClientSession.head`
* `ClientSession.options`
* `request`

I'm sadly not familiar with the docs tooling here to try to edit docs confidently.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Seems like you already have a suggestion, can you put that into a PR?
