### ISSUE TITLE
Allow for sharing DNSCacheTable in multiple TcpConnectors

### ISSUE THREAD

**Issue by fcomuniz** [fafhrd91/aiohttp#6010]
### Is your feature request related to a problem?

I have a problem when i have to run multiple sessions (because each session has it's own cookies) and i can't share the dns cache easely between the sessions (can cause errors when to many requests run at the same time). This happens usually on webscraping, because we may have to interact using multiple cookie sessions.

### Describe the solution you'd like

I would like to be able to pass a _DNSCacheTable as an argument to TCPConnector, so that i could share the DNSCacheTable between multiple sessions. Would like as well for DNSCacheTable to be a public class that could be easely used.

### Describe alternatives you've considered

I have Managed to do this creating a new class for TCPConnector, but it ends up using the Protected Class _DNSCacheTable. Ideally a public representation of the table would work better.

### Related component

Client

### Additional context

I will try to develop a solution to this, just wante to see if this is something the project is open to.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
You can share TCPConnector with all internal caches between multiple ClienSession instances, isn't it?

**Comment by fcomuniz** [comment]
you can, but there is an issue when you have one of the sessions that uses the connector that closes.

But you are right

**Comment by asvetlov** [comment]
Don't get me wrong, the PR is correct.
The problem is: making something public means commitment to documenting public API and keeping it backward compatible for years.
Looks like DNS cache strategy was not changed for very long but still if we can keep it private -- let's do it.
