### ISSUE TITLE
get amount of open requests

### ISSUE THREAD

**Issue by minusplusminus** [fafhrd91/aiohttp#6021]
### Is your feature request related to a problem?

Hi,

I'm currently testing the webserver functionality that is available. For that i'm using a mjpeg stream which requests frames from queue. I want to change the frame buffer by the amount of open requests that are on a specific route. 

### Describe the solution you'd like

Something like `app.routes.get('/frame').open_requests`

### Describe alternatives you've considered

Just a open connection count var, but its inaccurate

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by greshilov** [comment]
What makes a connection count var inaccurate? You can create a `middleware` and store `handler -> requests count` info in a hash map data structure, which itself is stored in the `app` object.

Consider the following example, hope it helps:

```python3
import asyncio
from aiohttp import web
from collections import Counter


@web.middleware
async def counter_middleware(request, handler):
    route_name = request.match_info.route.name or handler.__name__
    try:
        request.app['counter'][route_name] += 1
        return await handler(request)
    finally:
        request.app['counter'][route_name] -= 1


async def foo(request):
    # Emulate long running request
    await asyncio.sleep(10)
    return web.Response(text='foo')


async def stats(request):
    return web.json_response(data=dict(request.app['counter']))

app = web.Application(middlewares=[counter_middleware])
app['counter'] = Counter()
app.add_routes([web.get('/', foo, name='foo'), web.get('/stats', stats)])


if __name__ == '__main__':
    web.run_app(app)
```

**Comment by webknjaz** [comment]
HTTP is stateless. We get a request, we process it, we send a response on the wire. There's no such thing as an open HTTP request. Did you mean to count open TCP connections?

**Comment by Dreamsorcerer** [comment]
I think the solution above should work.
