### ISSUE TITLE
Allow to specify a timeout based on the last transmitted packet

### ISSUE THREAD

**Issue by adrienballsonos** [fafhrd91/aiohttp#6084]
### Is your feature request related to a problem?

As explained in issue https://github.com/aio-libs/aiohttp/issues/2249, the recommended way to handle large downloads without having timeout issues is to increase the timeout parameter or deactivate it completely.
In my opinion, this is not satisfying as it makes it impossible to handle the real timeouts that may occurred during such requests.

### Describe the solution you'd like

It would be convenient to have a way to specify a timeout that would be based on the last transmitted packet instead of the total connection time.

### Describe alternatives you've considered

none

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
Does [`ClientTimeout.sock_read'](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientTimeout.sock_read) solve your problem?

**Comment by adrienballsonos** [comment]
@asvetlov Indeed it solves my problem, sorry I should have read the doc more carefully.

**Comment by asvetlov** [comment]
No problem!
