### ISSUE TITLE
Helper to run tests in different python versions

### ISSUE THREAD

**Issue by derlih** [fafhrd91/aiohttp#6131]
### Is your feature request related to a problem?

Add helper targets to the Makefile that allow to run the test using the specific version of python and environment (AIOHTTP_NO_EXTENSIONS)

### Describe the solution you'd like

Introduce new targets:
- `test-3.7`
- `test-3.7-no-extensions`

and so on.

It will make easier to check locally the problems occurred during CI on the python versions that are not installed locally.

### Describe alternatives you've considered

Run the required steps manually.

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Personally, I'd prefer to have tox for this but I know that Andrew doesn't like it.

**Comment by derlih** [comment]
I just need a single command to run it. I don't care much how it would work. Would it use docker, tox or other tools.
For instance I had some failing tests for 3.7 and I'm not able to install it on my PC via package manager, I've started to search how to run it. Then I realized, that it's not the first time I'm doing it :-)
That's why I've created this ticket and PR #6132 .
