### ISSUE TITLE
using aiohttp 3.8.0 causes exception in async-timeout==3.0.1

### ISSUE THREAD

**Issue by schlitzered** [fafhrd91/aiohttp#6194]
### Describe the bug

using aiohttp 3.8.0 causes exception, in async_timeout.Timeout, which seems to be a private class

### To Reproduce

from aiohttp import web

### Expected behavior

no exception when loading aiohttp

### Logs/tracebacks

```python-traceback
File "...venv/lib/python3.9/site-packages/aiohttp/helpers.py", line 729, in <module>
    def ceil_timeout(delay: Optional[float]) -> async_timeout.Timeout:
AttributeError: module 'async_timeout' has no attribute 'Timeout'
```

### Python Version

```console
Python 3.9.5
```

### aiohttp Version

```console
aiohttp==3.8.0
async-timeout==3.0.1
```

### multidict Version

```console
5.2.0
```

### yarl Version

```console
1.7.0
```

### OS

has been reproduces on mac and linux

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
As stated in the dependencies, aiohttp v3.8.0 requires `async-timeout>=4`: https://github.com/aio-libs/aiohttp/blob/v3.8.0/setup.cfg#L54. Update your runtime accordingly.

**Comment by asvetlov** [comment]
Maybe an old `pip` was used for aiohttp 3.8 installation?

**Comment by webknjaz** [comment]
I'm pretty sure that it's not pip's fault. Maybe the reported used `--no-deps` or something along the lines of manually managing the dep resolution in an incorrect way. Anyway, as it stands now this is not a bug.

**Comment by kawegh74** [comment]
I had the same problem. I was using `poetry` (version 1.1.11) and `pip` version 21.1.2 and `python` version 3.8.
I updated the pip to 21.3.1 and it worked.
This was the output of `poetry show aiohttp` command:
```
name         : aiohttp
version      : 3.8.0
description  : Async http client/server framework (asyncio)

dependencies
 - aiosignal >=1.1.2
 - async-timeout >=4.0.0a3,<5.0
 - attrs >=17.3.0
 - charset-normalizer >=2.0,<3.0
 - frozenlist >=1.1.1
 - multidict >=4.5,<7.0
 - yarl >=1.0,<2.0
```

**Comment by anksvault** [comment]
Though this is an old thread, i had similar issue with an old application running obsolete packages, i was able to fix this by changing `def ceil_timeout(delay: Optional[float]) -> async_timeout.Timeout:` with 
`def ceil_timeout(delay: Optional[float]) -> async_timeout.timeout:` in `.../site-packages/aiohttp/helpers.py`
