### ISSUE TITLE
latest release (3.8.0) installs `examples` in site-packages

### ISSUE THREAD

**Issue by jieru-hu** [fafhrd91/aiohttp#6203]
### Describe the bug

the latest release installs a top level `examples` packages
```
ls anaconda3/envs/p3711/lib/python3.7/site-packages/examples/
```
This makes it not possible for me to use my own examples module. :( 

### To Reproduce

install latest version

### Expected behavior

do not install a top-level examples package. 

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
$ python --version
Python 3.7.11
and also python 3.8
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.0
```

### multidict Version

```console
$ python -m pip show multidict
Version: 5.2.0
```

### yarl Version

```console
$ python -m pip show yarl
Version: 1.7.2
```

### OS

macOS 

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Fixed by https://github.com/aio-libs/aiohttp/pull/6189.

**Comment by jieru-hu** [comment]
thanks! sorry i only checked open issues so didn't see the fix :)

**Comment by webknjaz** [comment]
No worries :)
