### ISSUE TITLE
Removal of signals module in 3.8 causing breaking changes downstream.

### ISSUE THREAD

**Issue by timothylunaxj4s** [fafhrd91/aiohttp#6250]
### Describe the bug

Hello, I'm using aiohttp under the hood by the use of some higher level libraries, notably Ray and Modin. Ray started breaking on me a few days ago and the culprit appears to be that Ray is unable to access the aiohttp.signals module.

Ray workers are dying when they attempt to access the module with an Import error.

### To Reproduce

1. Use aiohttp > 3.7.4 (ideally 3.8)
2. Attempt to import aiohttp.signals

### Expected behavior

No ImportError

### Logs/tracebacks

```python-traceback
NAN
```

### Python Version

```console
$ python --version
Using both 3.8 and 3.9.
```

### aiohttp Version

```console
$ python -m pip show aiohttp
# Failed version
aiohttp==3.8.0
```

### multidict Version

```console
$ python -m pip show multidict
multidict==5.2.0
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.0
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.9/site-packages
Requires: multidict, idna
Required-by: aiohttp
```

### OS

Debian / Ubuntu Linux

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
I'm sorry for that.
Please use `aiosignals.Signal` instead of `aiohttp.Signal`.
The proposed change is backward compatible with any aiohttp version; it is just a separate library.

**Comment by timothylunaxj4s** [comment]
I understand that this might not be an appropriate place to fix the issue and I'll be filing issues in the appropriate places.

If you're going to deprecate / change API do you have a normal process in place for that?

Thanks!

**Comment by asvetlov** [comment]
We have, but in this particular case, we didn't follow our own deprecation process.
Sorry again for the oversight.

**Comment by webknjaz** [comment]
@asvetlov it should be possible to add a module-level `__getattr__()` with a depreciation warning to fix this, right?

**Comment by asvetlov** [comment]
It doesn't work in Python 3.6

**Comment by webknjaz** [comment]
Fair enough. But if somebody would be up to contributing a Python 3.7+ patch, I won't oppose merging it (just for the aiohttp 3.8 branch, not 3.9).

**Comment by TheFizzWare** [comment]
Downstream libraries (ray) are also broken by:
```python
import aiohttp.frozenlist
```
