### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [fafhrd91/aiohttp#6308]
### Is your feature request related to a problem?

:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

### Describe the solution you'd like

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/aiohttp/lokal -name '*.py')
```

### Describe alternatives you've considered

:crystal_ball: How will the development interests evolve further also according to update candidates in 16 lines of this software?

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
Did you try to apply the pattern yourself?
How many cases are found?
How many of them are false positives?

**Comment by elfring** [comment]
>Did you try to apply the pattern yourself?

Yes, of course (including other software areas).


>How many cases are found?

16 ‒ [Did you overlook any information which I provided already](https://github.com/aio-libs/aiohttp/issues/6308#issue-1052676655 "Describe alternatives you've considered")?

:thought_balloon: Would you dare to repeat the shown source code search and replacement approach in another test repository by any of your preferred software development tools?

**Comment by Dreamsorcerer** [comment]
This looks like a task for flake8. I'd suggest making a flake8 plugin, or adding it to an existing plugin (pyflakes or pycodestyle maybe).

**Comment by elfring** [comment]
>This looks like a task for flake8.

Thanks for such a constructive feedback.

I came along software areas where some developers stumble on difficulties for proposed adjustments according to augmented arithmetic assignment statements.
How do you think about to add any more advices? :thinking:

**Comment by asvetlov** [comment]
I'd like to clarify: I don't want to work on the request myself but can review/merge a pull request if the request demonstrates a real problem and passes all checks.

If @elfring wants to end with advice only without a contribution -- Open Source doesn't work this way, sorry.

**Comment by elfring** [comment]
>… if the request demonstrates a real problem …

 :thinking:
* Do you find [the explanation by the Python enhancement proposal 203](https://www.python.org/dev/peps/pep-0203/#rationale "Proposal for augmented assignments") (from 2000-07-13) sufficient?
* How do you think about to support another bit of collateral evolution accordingly?


>… advice only without a contribution …

:thought_balloon: Can you get any more constructive impressions from my published software development activities?

**Comment by Dreamsorcerer** [comment]
We're not really sure what you're asking for anymore. As mentioned, this would be best integrated into flake8 where it would benefit many projects, rather than getting individual projects to add it.

If you manage to get this feature implemented there, then we look forward to running it on our codebase. But, I don't think there's anything else for us to do here at this time.

**Comment by elfring** [comment]
>…, this would be best integrated into flake8

:thought_balloon: I imagine that additional support would be helpful also for more source code analysis approaches.


> where it would benefit many projects, …

How do you think about to take another look at responses for the tool “Pylint” (for instance)? :thinking:


>But, I don't think there's anything else for us to do here at this time.

I got an other impression.
:thought_balloon: Would you get into the mood to reuse any information from the presented Perl command example?

**Comment by Dreamsorcerer** [comment]
> How do you think about o take another look at responses for the tool “Pylint” (for instance)? thinking

I don't really understand the question. We already use flake8, so I doubt we want to add another very similar tool.

> I got an other impression. thought_balloon Would you get into the mood to reuse any information from the presented Perl command example?

As @asvetlov said, if you have a PR for us to look at, then we can consider changes, but we don't have the time otherwise.

**Comment by elfring** [comment]
* Do you recognise any details from the shown regular expressions?
* Does anything hinder you to try a corresponding command example out before for possibly reasonable source code transformations?

**Comment by webknjaz** [comment]
> * Do you recognise any details from the shown regular expressions?

No.

> * Does anything hinder you to try a corresponding command example out before for possibly reasonable source code transformations?

It's Perl, it's known to be used to hide malicious code in its obscure syntax. That would stop me personally. But also, running random commands manually is not sustainable, they must be integrated into the existing linting infrastructure. Otherwise, it's not particularly useful to use (or for FOSS on a scale for that matter).

I think there's nothing more to discuss here and it is going nowhere so I'm closing the issue (it's not actually an issue or a bug and should've been open in the Discussions space, to begin with).

Here are acceptable action items if somebody with plenty of time wants to proceed:
1. Send a pull request refactoring updating the code (it's not very useful long term, but I think we can live with it if it looks reasonable).
2. Send a PR integrating a linter check for this.

**Comment by elfring** [comment]
>Otherwise, it's not particularly useful to use (or for FOSS on a scale for that matter).

I dare to present an other development view.

I imagine that some Python programmers can interpret regular expressions as demonstrated within a tiny Perl command.

>… (it's not actually an issue or a bug and should've been open in the Discussions space, to begin with).

Do you care for collateral evolution in further software areas (also according to possible source code transformations like the following)?

```diff
diff --git a/aiohttp/http_websocket.py b/aiohttp/http_websocket.py
index ee877fd4..497bf765 100644
--- a/aiohttp/http_websocket.py
+++ b/aiohttp/http_websocket.py
@@ -541,7 +541,7 @@ class WebSocketReader:
                 else:
                     self._payload_length = 0
                     payload.extend(buf[start_pos : start_pos + length])
-                    start_pos = start_pos + length
+                    start_pos += length
 
                 if self._payload_length == 0:
                     if self._has_mask:
@@ -609,12 +609,12 @@ class WebSocketWriter:
                 compressobj = self._compressobj
 
             message = compressobj.compress(message)
-            message = message + compressobj.flush(
+            message += compressobj.flush(
                 zlib.Z_FULL_FLUSH if self.notakeover else zlib.Z_SYNC_FLUSH
             )
             if message.endswith(_WS_DEFLATE_TRAILING):
                 message = message[:-4]
-            rsv = rsv | 0x40
+            rsv |= 0x40
 
         msg_length = len(message)
 
diff --git a/aiohttp/http_writer.py b/aiohttp/http_writer.py
index e0914473..8061f6fd 100644
--- a/aiohttp/http_writer.py
+++ b/aiohttp/http_writer.py
@@ -101,7 +101,7 @@ class StreamWriter(AbstractStreamWriter):
         if self.length is not None:
             chunk_len = len(chunk)
             if self.length >= chunk_len:
-                self.length = self.length - chunk_len
+                self.length -= chunk_len
             else:
                 chunk = chunk[: self.length]
                 self.length = 0
@@ -141,7 +141,7 @@ class StreamWriter(AbstractStreamWriter):
             if chunk:
                 chunk = self._compress.compress(chunk)
 
-            chunk = chunk + self._compress.flush()
+            chunk += self._compress.flush()
             if chunk and self.chunked:
                 chunk_len = ("%x\r\n" % len(chunk)).encode("ascii")
                 chunk = chunk_len + chunk + b"\r\n0\r\n\r\n"
diff --git a/aiohttp/web_fileresponse.py b/aiohttp/web_fileresponse.py
index 3246b8ae..cbbe5a0a 100644
--- a/aiohttp/web_fileresponse.py
+++ b/aiohttp/web_fileresponse.py
@@ -76,7 +76,7 @@ class FileResponse(StreamResponse):
         chunk = await loop.run_in_executor(None, fobj.read, chunk_size)
         while chunk:
             await writer.write(chunk)
-            count = count - chunk_size
+            count -= chunk_size
             if count <= 0:
                 break
             chunk = await loop.run_in_executor(None, fobj.read, min(chunk_size, count))
diff --git a/aiohttp/web_urldispatcher.py b/aiohttp/web_urldispatcher.py
index f014a7f9..8f95714c 100644
--- a/aiohttp/web_urldispatcher.py
+++ b/aiohttp/web_urldispatcher.py
@@ -570,9 +570,9 @@ class StaticResource(PrefixResource):
         url = URL.build(path=self._prefix, encoded=True)
         # filename is not encoded
         if YARL_VERSION < (1, 6):
-            url = url / filename.replace("%", "%25")
+            url /= filename.replace("%", "%25")
         else:
-            url = url / filename
+            url /= filename
 
         if append_version:
             try:
diff --git a/tests/autobahn/client/client.py b/tests/autobahn/client/client.py
index dfca77d1..d1553e52 100644
--- a/tests/autobahn/client/client.py
+++ b/tests/autobahn/client/client.py
@@ -23,7 +23,7 @@ async def client(url: str, name: str) -> None:
                     else:
                         break
 
-        url = url + "/updateReports?agent=%s" % name
+        url += "/updateReports?agent=%s" % name
         async with session.ws_connect(url) as ws:
             print("finally requesting %s" % url)
 
diff --git a/tests/test_multipart.py b/tests/test_multipart.py
index 44fab726..4c779f93 100644
--- a/tests/test_multipart.py
+++ b/tests/test_multipart.py
@@ -88,7 +88,7 @@ class StreamWithShortenRead(Stream):
     async def read(self, size: Optional[Any] = None):
         if size is not None and self._first:
             self._first = False
-            size = size // 2
+            size //= 2
         return await super().read(size)
 
 
diff --git a/tests/test_web_middleware.py b/tests/test_web_middleware.py
index cfd85b5f..364608a5 100644
--- a/tests/test_web_middleware.py
+++ b/tests/test_web_middleware.py
@@ -16,7 +16,7 @@ async def test_middleware_modifies_response(loop: Any, aiohttp_client: Any) -> N
         resp = await handler(request)
         assert 200 == resp.status
         resp.set_status(201)
-        resp.text = resp.text + "[MIDDLEWARE]"
+        resp.text += "[MIDDLEWARE]"
         return resp
 
     app = web.Application()
@@ -65,7 +65,7 @@ async def test_middleware_chain(loop: Any, aiohttp_client: Any) -> None:
                 getattr(handler, "annotation", None)
             )
             resp = await handler(request)
-            resp.text = resp.text + f"[{num}]"
+            resp.text += f"[{num}]"
             return resp
 
         return middleware
@@ -423,7 +423,7 @@ async def test_old_style_middleware(loop: Any, aiohttp_client: Any) -> None:
             resp = await handler(request)
             assert 200 == resp.status
             resp.set_status(201)
-            resp.text = resp.text + "[old style middleware]"
+            resp.text += "[old style middleware]"
             return resp
 
     app = web.Application(middlewares=[middleware])
@@ -444,7 +444,7 @@ async def test_new_style_middleware_class(loop: Any, aiohttp_client: Any) -> Non
             resp = await handler(request)
             assert 200 == resp.status
             resp.set_status(201)
-            resp.text = resp.text + "[new style middleware]"
+            resp.text += "[new style middleware]"
             return resp
 
     app = web.Application()
@@ -466,7 +466,7 @@ async def test_new_style_middleware_method(loop: Any, aiohttp_client: Any) -> No
             resp = await handler(request)
             assert 200 == resp.status
             resp.set_status(201)
-            resp.text = resp.text + "[new style middleware]"
+            resp.text += "[new style middleware]"
             return resp
 
     app = web.Application()
diff --git a/tests/test_websocket_parser.py b/tests/test_websocket_parser.py
index 90f35c49..e19abbab 100644
--- a/tests/test_websocket_parser.py
+++ b/tests/test_websocket_parser.py
@@ -34,7 +34,7 @@ def build_frame(
     if compress:
         compressobj = zlib.compressobj(wbits=-9)
         message = compressobj.compress(message)
-        message = message + compressobj.flush(zlib.Z_SYNC_FLUSH)
+        message += compressobj.flush(zlib.Z_SYNC_FLUSH)
         if message.endswith(_WS_DEFLATE_TRAILING):
             message = message[:-4]
     msg_length = len(message)
```
