### ISSUE TITLE
Types for pytest.fixtures

### ISSUE THREAD

**Issue by vertti** [fafhrd91/aiohttp#6315]
### Is your feature request related to a problem?

I'm trying to include types for my unittests also. Trying to figure out how to type `aiohttp_server` etc, I found that this project uses type: ignore for them.

### Describe the solution you'd like

Would be great to:
1. have all pytests fixtures have a type definition
2. have the documentation include these type definitions in examples

### Describe alternatives you've considered

Well, I could just disable mypy checking for all tests files or use explicit `Any` for aiohttp fixtures.

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by asvetlov** [comment]
Does mypy infer a fixture-as-argument type from the fixture function definition?
IMHO it is not possible by default, and a specific mypy plugin for pytest support doesn't exist yet.
Am I wrong?

**Comment by Dreamsorcerer** [comment]
I'm planning to remove those blanket `type: ignore`s at some point.

mypy can't infer any relation between pytest fixtures and the functions using them, but the types can be explicitly annotated. Although the return types appear to be a function, so maybe we should include an alias for these, but it looks like you should be able to do something like:
`async def test_hello(aiohttp_client: Callable[[Application], TestClient]):`

**Comment by asvetlov** [comment]
Closing the issue, the mentioned suggestions can improve aiohttp code itself (and I support them) but fixture types cannot be inferred by the current type checkers.
