### ISSUE TITLE
Pypi meta shows wrong python requirement

### ISSUE THREAD

**Issue by WisdomPill** [fafhrd91/aiohttp#6319]
### Describe the bug

Having a look [here](https://pypi.org/project/aiohttp/) on the meta section on the left side, there is written that python>=3.6 is supported, while it is only python>=3.7 is supported

### To Reproduce

Have a look [here](https://pypi.org/project/aiohttp/)

### Expected behavior

having the right python requirement on pipy

### Logs/tracebacks

```python-traceback
none
```

### Python Version

```console
$ python --version
```

### aiohttp Version

```console
$ python -m pip show aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

all

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
3.7 is for master (and maybe 3.9), 3.6 is for 3.8. It's not wrong.
