### ISSUE TITLE
There is inconsistency aiohttp.ClientSession.request's document and code.

### ISSUE THREAD

**Issue by agrexgh** [fafhrd91/aiohttp#6372]
### Describe the bug

[Basic API doc](https://docs.aiohttp.org/en/stable/client_reference.html#basic-api) says `aiohttp.ClientSession.request()` returns `aiohttp.ClientResponse`,
but [source code](https://docs.aiohttp.org/en/stable/_modules/aiohttp/client.html) says it returns `aiohttp._RequestContextManager`,

I guess this is problem of documentation, not that of software behavior.

### To Reproduce

NA

### Expected behavior

[Basic API doc](https://docs.aiohttp.org/en/stable/client_reference.html#basic-api) and [source code](https://docs.aiohttp.org/en/stable/_modules/aiohttp/client.html) say same thing.

### Logs/tracebacks

```python-traceback
NA
```

### Python Version

```console
$ python --version
Python 3.9.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /usr/local/lib/python3.9/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by: line-bot-sdk
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.9/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Ubuntu 20.04 on WSL2

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Both are correct. The documentation says 'async-with aiohttp.request...', if you use `async with aiohttp.request()` this will return `ClientResponse`. The source code is a normal `def` function which returns an async context wrapper around `ClientResponse`.

**Comment by agrexgh** [comment]
I see, thx! @Dreamsorcerer 

And I beg you some advices..
Do you know any workaround or any solution about below problem?

I have code like below.
```Python
def get_page(self, url_to_get_page:str) -> aiohttp.ClientResponse:
```

I'd like to use type hints, but `mypy` says below.
```
Incompatible return value type (got "_RequestContextManager", expected "ClientResponse")
```

I changed the code like below.
```Python
def get_page(self, url_to_get_page:str) -> aiohttp._RequestContextManager:
```
`mypy` says below at this time.
```
error: Name "aiohttp._RequestContextManager" is not defined
```

so I couldn't solve `mypy` indication.

**Comment by Dreamsorcerer** [comment]
Either of these would work:
```
from contextlib import asynccontextmanager
from typing import AsyncContextManager, AsyncIterator

import aiohttp

def get_page(url_to_get_page: str) -> AsyncContextManager[aiohttp.ClientResponse]:
    return aiohttp.request("GET", url_to_get_page)

@asynccontextmanager
async def get_page2(url_to_get_page: str) -> AsyncIterator[aiohttp.ClientResponse]:
    async with aiohttp.request("GET", url_to_get_page) as resp:
        yield resp
```

**Comment by agrexgh** [comment]
Thank you so much!
It works!!
