### ISSUE TITLE
Mypy issue

### ISSUE THREAD

**Issue by painassasin** [fafhrd91/aiohttp#6422]
### Describe the bug

Method `_raise_allowed_methods` should return `NoReturn` instead of `None` for mypy compatibility

### To Reproduce

mypy 0.920

### Expected behavior

...

### Logs/tracebacks

```python-traceback
...
```

### Python Version

```console
$ python --version
```

### aiohttp Version

```console
$ python -m pip show aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

macOS

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
We have test coverage for this, so no need to worry about it, unless you want to send a PR.
Fixed in #6423.
