### ISSUE TITLE
proxy endpoint data=request.content results in no data posted

### ISSUE THREAD

**Issue by orglnte** [fafhrd91/aiohttp#6432]
### Describe the bug

I have a proxy endpoint, that used to stream data from the received request to the posted request like in the commented line:

`session.post(
        url,
        params=request.query,
        headers=prepare_headers(request),
        data=await request.read(),
        # this stopped working:
        # data=request.content
    )`

recently (I am not sure after which version) it stopped working. How to make it stream the data again so that no memory is used?

### To Reproduce

Implement a similar endpoint, on 3.8.1

### Expected behavior

data is streamed directly to the destination host, with no need to read and have it in memory

### Logs/tracebacks

```python-traceback
.
```

### Python Version

```console
Python 3.9.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: /Users/michele/.virtualenvs/proxy/lib/python3.9/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by: aiohttp-request-id-logging
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/michele/.virtualenvs/proxy/lib/python3.9/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/michele/.virtualenvs/proxy/lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

macOS and ubuntu

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Documentation shows this is still expected to work: https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-uploads

I've not got time to go through it yet, but if someone wants to put a regression test in a PR that we can look at, that will save us a lot of time (there are some related tests already: https://github.com/aio-libs/aiohttp/blob/master/tests/test_client_request.py#L846).

**Comment by Dreamsorcerer** [comment]
This seems to be working for me on the latest release:
```
import asyncio
import aiohttp
from aiohttp import web
from yarl import URL

async def handler2(request):
    print(await request.read())
    return web.Response(text="Foo")

async def handler(request):
    async with aiohttp.ClientSession() as sess:
        async with sess.post("http://127.0.0.1:8080/foo", data=request.content) as resp:
            print("DONE")

app = web.Application()
app.router.add_post("/", handler)
app.router.add_post("/foo", handler2)
web.run_app(app)
```
```
> curl 'http://10.0.3.211:8080/' -X POST -d 'foo,bar'
```
