### ISSUE TITLE
Content-Length header not set correctly after on_response_prepare

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#6443]
### Describe the bug

I'm struggling to figure out exactly what is happening here, but in aiohttp-devtools we append a script to the end of the body using on_response_prepare: https://github.com/aio-libs/aiohttp-devtools/blob/master/aiohttp_devtools/runserver/serve.py#L52

I can print out `response.body` on the next line and get the expected output, something ending with:
```
</html>
<script src="http://10.0.3.106:8001/livereload.js"></script>
```

But, the output received by the client is without the modification, i.e. curl output ends with:
```
</html>⏎ 
```

### To Reproduce

Run aiohttp-devtools master and observe that there is no script tag included in the output.

### aiohttp Version

3.8

**Comment by Dreamsorcerer** [comment]
Ah, I think it might be the `Content-Length` header. It's resulting in not receiving the extra bytes.

**Comment by Dreamsorcerer** [comment]
Yep, if I rewrite the header then everything works again. Not sure what caused the regression, but I can see the header appears to be set before calling the prepare hooks: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_response.py#L689-L694

Perhaps this step should be done just after the prepare hook?

**Comment by asvetlov** [comment]
I guess `resp.text` and `resp.body` setters should be modified to recalculate `Content-Length` header.
`body` setter has required logic but not for all code branches, `text` has nothing.
I suspect it was a result of the non-accurate refactoring.

**Comment by Dreamsorcerer** [comment]
Ah, so it does. But, 2 problems that fail this. First, we assign bytes, so it doesn't run. Second, even if we were in the `else`, then it only sets the header if it is not already set: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_response.py#L605

I'm unsure what the logic is with creating the header in the setter, but also in the prepare step? Is it because the logic in the setter is a special case, and the prepare step is the generic default? In which case I think we should just move that step in `_start()` to happen after the prepare hooks.

i.e. This code: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_response.py#L689-L694
Needs to happen after this line in the parent class: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_response.py#L354

**Comment by Dreamsorcerer** [comment]
In fact, if we just change that function from `_start()` to `_write_headers()`, that would solve it right? The place we actually want to add this header is just before we write the headers...
https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_response.py#L688
