### ISSUE TITLE
`asyncio.run` compatibility is broken

### ISSUE THREAD

**Issue by Olegt0rr** [fafhrd91/aiohttp#6457]
### Describe the bug

This [PR](https://github.com/aio-libs/aiohttp/pull/5572) broke compatibility with already running loops!

In some cases `aiohttp` can't replace basic `asyncio.run()`.
E.g. in case if you need to get remote config for your server before go.

### To Reproduce

```python
async def main():
    app_config = await get_remote_app_config()
    app = get_web_app()  # my web.Application factory

    loop = asyncio.get_event_loop()
    web.run_app(app, loop=loop, port=app_config.port)
    

asyncio.run(main())
```

### Expected behavior

Applications successfully started within provided event loop.

### Logs/tracebacks

```python-traceback
File "/Users/t0rr/PycharmProjects/TrueMafiaAdvert/app/__main__.py", line 38, in main
    web.run_app(app, loop=loop, port=wa.port)
  File "/Users/t0rr/Library/Caches/pypoetry/virtualenvs/truemafiaadvert-jvaV-hRR-py3.9/lib/python3.9/site-packages/aiohttp/web.py", line 518, in run_app
    _cancel_tasks({main_task}, loop)
  File "/Users/t0rr/Library/Caches/pypoetry/virtualenvs/truemafiaadvert-jvaV-hRR-py3.9/lib/python3.9/site-packages/aiohttp/web.py", line 445, in _cancel_tasks
    loop.run_until_complete(asyncio.gather(*to_cancel, return_exceptions=True))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 618, in run_until_complete
    self._check_running()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
```

### Python Version

```console
$ python --version
Python 3.9.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /Users/t0rr/PycharmProjects/TrueMafia/venv/lib/python3.9/site-packages
Requires: aiosignal, attrs, charset-normalizer, yarl, async-timeout, multidict, frozenlist
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/t0rr/PycharmProjects/TrueMafia/venv/lib/python3.9/site-packages
Requires: 
Required-by: yarl, aiohttp
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/t0rr/PycharmProjects/TrueMafia/venv/lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

macOS

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
`run_app()` should be the entry point of the program, it replaces `asyncio.run()`. Calling `run_app()` inside of `asyncio.run()` is not supported anymore than calling `asyncio.run()` inside of an `asyncio.run()` call is. It doesn't make any sense as it is a blocking function.

From the documentation:
> This is a high-level function very similar to asyncio.run() and should be used as the main entry point for an application. The Application object essentially becomes our main() function. If additional tasks need to be run in parallel, see Complex Applications.
https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.run_app

There is already plenty of discussion on that PR, and as mentioned at the end, please don't pass the loop into `run_app()` as anything other than a temporary fix, please refactor your application to use `run_app()` correctly, or use the lower level app runners if you really want to manage the loop yourself: https://docs.aiohttp.org/en/stable/web_advanced.html#application-runners

**Comment by Dreamsorcerer** [comment]
In your trivial example, assuming there is nothing persistent (like DB connections and such) in the config, then it can simply be written as:

```
app_config = asyncio.run(get_remote_app_config())
app = get_web_app()
web.run_app(app, port=app_config.port)
```

Which, actually, is exactly the case that PR was designed to fix.
