### ISSUE TITLE
Can't decompress gzip with auto_decompress set to False

### ISSUE THREAD

**Issue by dbatten5** [fafhrd91/aiohttp#6466]
### Describe the bug

When the `auto_decompress` property in `ClientSession` is set to `False`, `gzip` encoded responses can't be decoded. With `auto_decompress=True` (the default behaviour), the response is decoded without issue.

### To Reproduce

```python
#!/usr/bin/env python3

import asyncio

from aiohttp import ClientSession


async def main():
    async with ClientSession(auto_decompress=False) as session:
        async with session.get("http://httpbin.org/gzip") as resp:
            text = await resp.text()
            print(text)


asyncio.run(main())
```

### Expected behavior

I would expect the response to be decoded by `resp.text()`, especially as I note that the method can receive an encoding type argument to decode, however I get the error detailed below. I've tried adding an `encoding=` argument with values of `gzip` and `deflate` but then I get a `LookupError: unknown encoding: gzip/deflate`

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "./script.py", line 15, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "./script.py", line 11, in main
    text = await resp.text()
  File "~/.../.venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1086, in text
    encoding, errors=errors
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

### Python Version

```console
$ python --version
Python 3.7.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: None
Author-email: None
License: Apache 2
Location: /~/.../.venv/lib/python3.7/site-packages
Requires: aiosignal, typing-extensions, frozenlist, asynctest, async-timeout, attrs, yarl, multidict, charset-normalizer
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Version: 5.2.0
```

### yarl Version

```console
$ python -m pip show yarl
Version: 1.7.2
```

### OS

Mac OSX Catalina 10.15.7

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
gzip is binary data, why would you expect it to be able to decode it as a string?

**Comment by dbatten5** [comment]
@Dreamsorcerer probably a lack of understanding of gzip and binary data on my behalf. is there a recommended way of handling `gzip` with `aiohttp`?

**Comment by Dreamsorcerer** [comment]
Surely leaving `auto_decompress` alone would be the recommended way? I'm not sure what other case you are trying to handle.

`encoding` is the string encoding, which you tried passing a mimetype to: https://docs.python.org/3/library/stdtypes.html#str

I've never looked at the gzip code, so I don't know if there are functions to help decompress a response manually, but still not sure why you'd even want to.

**Comment by dbatten5** [comment]
@Dreamsorcerer basically I'm using [vcrpy](https://github.com/kevin1024/vcrpy) to record the `aiohttp` requests/responses my package makes when running my test suite. I'd like to be able to store the responses in their encoded form so the files are smaller, however it seems like `aiohttp` decodes the response body before `vcrpy` persists it, which is why I thought I'd look into the `auto_decompress` option. Think I may open an issue with `vcrpy` though as this behaviour is handled quite nicely with `requests`. Will close this issue

**Comment by Dreamsorcerer** [comment]
Presumably, you could just save the binary data then (`resp.read()`, but consider streaming APIs for files: https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-response-content), and use the `gzip` module to read the file back? https://docs.python.org/3/library/gzip.html

**Comment by dbatten5** [comment]
Ah yep that makes sense, I guess it's a little tricky as the responses aren't always gzip encoded so it's a bit of a pain to have to manually catch the different forms of compression that might be used. Would be great to leave the decompression handling to `aiohttp` as it's already built in, hopefully there's a way `vcrpy` can store the binary data

**Comment by Dreamsorcerer** [comment]
Another option is just to recompress all file content with your preferred compression tool (assuming you don't need the stored files to have matching hashes or something). That could reduce space further by always using the most optimal compression and compressing previously uncompressed files.

**Comment by dbatten5** [comment]
Have gone for that solution, thanks @Dreamsorcerer
