### ISSUE TITLE
OSError: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by mknithin** [fafhrd91/aiohttp#6469]
### Describe the bug

I'm using aio http to make a post request, inside a http request  and I'm getting this error when making continues call 

this is the code I'm using 

conn = aiohttp.TCPConnector(limit=0, ttl_dns_cache=300)
    async with aiohttp.ClientSession(connector=conn) as session:
        async with session.post("http://somethign", json={'data': data}, ssl=False) as resp:
            if resp.status == status.HTTP_200_OK:
                ..
            elif resp.status == status.HTTP_401_UNAUTHORIZED:
                ..
            elif resp.status == status.HTTP_404_NOT_FOUND:
                `..```

### To Reproduce

1. call aio.http post request  with ulimited connection pool size
2. the specified exception will occur

### Expected behavior

I think there should some way to handle this when making continues http requests

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "uvloop/loop.pyx", line 2024, in create_connection
  File "uvloop/loop.pyx", line 2000, in uvloop.loop.Loop.create_connection
  File "uvloop/handles/tcp.pyx", line 182, in uvloop.loop.TCPTransport.connect
  File "uvloop/handles/tcp.pyx", line 204, in uvloop.loop._TCPConnectRequest.connect
OSError: [Errno 99] Cannot assign requested address
```

### Python Version

```console
$ python --version
```

### aiohttp Version

```console
$ python -m pip show aiohttp

Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /Users/nithinmk/Library/Caches/pypoetry/virtualenvs/messaging-backend-QVw4N_6B-py3.9/lib/python3.9/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict

Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/nithinmk/Library/Caches/pypoetry/virtualenvs/messaging-backend-QVw4N_6B-py3.9/lib/python3.9/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl

Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/nithinmk/Library/Caches/pypoetry/virtualenvs/messaging-backend-QVw4N_6B-py3.9/lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aio-pika, aiohttp, aiormq
```

### OS

mac os Monterey

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
The traceback is coming from `uvloop`. Is this reproducible with asyncio natively? If not, this should probably be just closed as invalid.
