### ISSUE TITLE
Don't wait for async ```on_startup``` to fully return before starting main web.Application daemon. 

### ISSUE THREAD

**Issue by thiezn** [fafhrd91/aiohttp#6489]
### Is your feature request related to a problem?

Hi,

I use aiphttp web.Application to host a website and I would like to have an async background task that continuously monitors if there's any scheduled work to do. Here's a quick mockup example function for the scheduler:

```python
async def scheduler(app: web.Application):
    while True:
         for task in await list_pending_tasks():
             await asyncio.create_task(task)

         await asyncio.sleep(10)
```

Looking at the aiohttp docs it seems like the on_startup feature would be great for this. Unfortunately it seems when passing on a function that doesn't fully return, the web.Application daemon itself won't start.

### Describe the solution you'd like

It would be great if on_startup functions don't block the main web.Application HTTP listener from starting. 

However, I'm not sure if this is intended behavior. Perhaps some people rely on the functions to be fully completed to ensure work is done **before** the http listener starts?

### Describe alternatives you've considered

As an alternative I'm now taking a look at [application runners](https://docs.aiohttp.org/en/stable/web_advanced.html#application-runners) to see if I can run the parallel task from there. 

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by thiezn** [comment]
My apologies, actually its very well described in the documentation that I missed initially [here](https://docs.aiohttp.org/en/stable/web_advanced.html#background-tasks). 

My mistake was to directly invoke the scheduler function, the solution was to call my scheduler function with async.create_task to add it to the running asyncio loop.

**Comment by Dreamsorcerer** [comment]
> My apologies, actually its very well described in the documentation that I missed initially [here](https://docs.aiohttp.org/en/stable/web_advanced.html#background-tasks).

Yep, check the first example in the next section for a slightly more robust approach (I'll update that other example):
https://docs.aiohttp.org/en/stable/web_advanced.html#complex-applications

As the purpose of the startup is to prepare the application (e.g. opening DB connections), accepting requests before it can correctly process them would be a bad idea.
