### ISSUE TITLE
TCP connection leak if server does not close connection in response to `close_notify`

### ISSUE THREAD

**Issue by simoncampion** [fafhrd91/aiohttp#6490]
### Describe the bug

In certain cases, `aiohttp.ClientSession` seems to only send a TLS `close_notify` message to close a TLS connection. It appears to rely on the server to actually close the underlying TCP connection. When the server doesn't, the connection stays open forever on the client. For example, even if the connection is opened with `async with ClientSession(...):` and the context block is left, the TCP connection will stay open forever.

### To Reproduce

I have been witnessing this behaviour when sending GET requests to a Docker Engine that malfunctions as described [here](https://github.com/docker/for-linux/issues/397). I do not know how to force a Docker Engine into this malfunctioning state. Also, I unfortunately did not manage to write a server process that produces the same connection leak.

Thus, all I can show at this point is the leaking client code. When executed, `netstat -n | grep ESTABLISHED | wc -l` shows an ever increasing number of open TCP connections. `tcpdump` shows that the last message sent by the client for each TCP connection is a TLS `close_notify` alert.

```python
sync def send_request():
  ssl_context = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
  ssl_context.check_hostname = False
  ssl_context.verify_mode = ssl.CERT_NONE
  cert_path = './cert.pem'
  key_path = './key.pem'
  ssl_context.load_cert_chain(certfile=cert_path, keyfile=key_path)
  connector = aiohttp.TCPConnector(ssl=ssl_context, force_close=True)

  async with aiohttp.ClientSession(connector=connector) as session:
    try:
      response = await session.request(
          'GET',
          'https://some.host.running.docker/v1.41/containers/my-container/json',
          params={},
          headers=CIMultiDict({'Content-Type': 'application/json'}),
          data=None,
          timeout=aiohttp.ClientTimeout(sock_read=1, sock_connect=1, total=3),
          chunked=None,
          read_until_eof=True,
      )
    except Exception as e:
      print(repr(e))


async def send_requests_forever():
  while True:
    try:
      await send_request()
    except Exception as e:
      pass
    await asyncio.sleep(1)


asyncio.run(send_requests_forever())
```

### Expected behavior

I'd expect that TCP connections are always eventually closed when opened with `async with ClientSession(...)` and the context block was left.

### Logs/tracebacks

```python-traceback
ServerTimeoutError('Timeout on reading data from socket')
ServerTimeoutError('Timeout on reading data from socket')
ServerTimeoutError('Timeout on reading data from socket')
ServerTimeoutError('Timeout on reading data from socket')
ServerTimeoutError('Timeout on reading data from socket')
ServerTimeoutError('Timeout on reading data from socket')
ServerTimeoutError('Timeout on reading data from socket')
ServerTimeoutError('Timeout on reading data from socket')
...
```

### Python Version

```console
3.10.1
```

### aiohttp Version

```console
3.8.1
```

### multidict Version

```console
5.2.0
```

### yarl Version

```console
1.7.2
```

### OS

MacOS 12.0.1

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by lamoni** [comment]
Bumping this, as we're still seeing this. 

It's a hacky recommendation for reproducing it because I don't have time at the moment to submit anything formal, but I've been able to reproduce this issue in two different env (prod and lab) using Prometheus Alertmanager's API. If you send enough API requests to it using aiohttp and hit the default GET request limit (8 concurrent), it will consistently leak these connections (we see a steady growth of TCP alloc)

**Comment by Dreamsorcerer** [comment]
Which Python version are you using?

**Comment by Dreamsorcerer** [comment]
Judging by the linked PR, it looks like a solution has been found by using enable_cleanup_closed. This appears to run every 2 seconds though, so I'm not sure it's something that should be enabled by default.

I think it should still close the connections when exiting the ClientSession though. So, if that's not the case, we'd really need an aiohttp server/test to reproduce it (even if it require patching aiohttp to reproduce). Maybe some of the test for enable_cleanup_closed could be used as a template.
