### ISSUE TITLE
Graceful Shutdown example gives DeprecationWarning on Python 3.10

### ISSUE THREAD

**Issue by nihil-admirari** [fafhrd91/aiohttp#6501]
### Describe the bug

An example from [Graceful Shutdown](https://docs.aiohttp.org/en/stable/client_advanced.html#graceful-shutdown) uses `asyncio.get_event_loop()` which is deprecated as of [Python 3.10](https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop).

### To Reproduce

1. Implement an example from the documentation
```py
import asyncio

import aiohttp


async def read_website():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://example.org/') as resp:
            await resp.read()

loop = asyncio.get_event_loop()
loop.run_until_complete(read_website())
# Zero-sleep to allow underlying connections to close
loop.run_until_complete(asyncio.sleep(0))
loop.close()
```
2. Run and see
```
DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
```

### Expected behavior

Documentation should provide an example of graceful shutdown without a `DeprecationWarning`.

### Logs/tracebacks

```python-traceback
DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
```

### Python Version

```console
$ python --version
Python 3.10.1
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Version: 3.8.1
```

### multidict Version

```console
$ python -m pip show multidict
Version: 5.2.0
```

### yarl Version

```console
$ python -m pip show yarl
Version: 1.7.2
```

### OS

Linux

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I think we should just add the `await asyncio.sleep()` to the end of the function and remove all the loop lines from that example.
