### ISSUE TITLE
Reload app / log background task exception

### ISSUE THREAD

**Issue by louisabraham** [fafhrd91/aiohttp#6518]
### Describe the bug

A background task I had (registered with `app.on_startup`) had an exception.

But the app seemed to run normally. 

This is my code (the report_task function has an error):

```py
async def report_task():
    schedule.every().day.at("03:00").do(send_reports)
    try:
        while True:
            schedule.run_pending()
            await asyncio.sleep(5)
    except asyncio.CancelledError:
        pass


async def start_background_tasks(app):
    app["report sender"] = asyncio.create_task(report_task())


async def cleanup_background_tasks(app):
    app["report sender"].cancel()
    await app["report sender"]


async def make_app():
    app = web.Application(middlewares=[auth])
    app.add_routes(routes)
    app.on_startup.append(start_background_tasks)
    app.on_cleanup.append(cleanup_background_tasks)
    return app
```

The logs only appear when quitting the app:

```
[2022-01-17 01:21:13 +0100] [1457700] [ERROR] Exception in gunicorn worker
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/aiohttp/worker.py", line 58, in run
    self.loop.run_until_complete(self._task)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3/dist-packages/aiohttp/worker.py", line 116, in _run
    await runner.cleanup()
  File "/usr/lib/python3/dist-packages/aiohttp/web_runner.py", line 251, in cleanup
    await self._cleanup_server()
  File "/usr/lib/python3/dist-packages/aiohttp/web_runner.py", line 337, in _cleanup_server
    await self._app.cleanup()
  File "/usr/lib/python3/dist-packages/aiohttp/web_app.py", line 403, in cleanup
    await self.on_cleanup.send(self)
  File "/usr/lib/python3/dist-packages/aiohttp/signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "main.py", line 222, in cleanup_background_tasks
    await app["report sender"]
  File "main.py", line 210, in report_task
    schedule.run_pending()
```

### To Reproduce

1. Schedule a background task
2. Raise an exception
3. Nothing happens

### Expected behavior

I think there should be a mechanism in place to show the logs or that [the docs](https://docs.aiohttp.org/en/stable/web_advanced.html#background-tasks) should be more clear.

The best would be to have an option that causes the app to be reloaded when there is an exception in a background task.

### Logs/tracebacks

```python-traceback
above
```

### Python Version

```console
$ python --version
Python 3.8.5
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Version: 3.6.2
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

Arch Linux

### Related component

Server

### Code of Conduct

- [x] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
You used `create_task()` to run it in the background. Exceptions in a task are not propagated until you `await` on them, which you do in the last line of cleanup (and this is generally why you do that). You can also see this in the traceback, the exception happens through the `await` line. Nothing to do with aiohttp.

As a side note, you should really use `cleanup_ctx` for that: https://docs.aiohttp.org/en/stable/web_advanced.html#complex-applications
