### ISSUE TITLE
invalid character in header 

### ISSUE THREAD

**Issue by saarsa** [fafhrd91/aiohttp#6525]
### Describe the bug

Can someone explain to me why my code does not work
I get this error all the time `400, message='Invalid header value char', url=URL('https://mayaapi.tase.co.il/api/company/alldetails?companyId=373')
`

my code:
```import aiohttp
import asyncio
import os

os.environ.setdefault('AIOHTTP_NO_EXTENSIONS', "1")
async def test():
    url = 'https://mayaapi.tase.co.il/api/company/alldetails?companyId=373'
    # url = 'https://www.google.com/'
    headers={"Accept-Language": "he-IL","X-Maya-With": "allow"}
    async with aiohttp.request(method="get", url=url, headers=headers) as respon:
        x = await respon.json()
    print(x)

asyncio.run(test())
```
I use `os.environ.setdefault('AIOHTTP_NO_EXTENSIONS', "1")` but it still does not work 

### To Reproduce

.

### Expected behavior

Everything but that 

### Logs/tracebacks

```python-traceback
Exception has occurred: ClientResponseError
400, message='Invalid header value char', url=URL('https://mayaapi.tase.co.il/api/company/alldetails?companyId=373')

The above exception was the direct cause of the following exception:

  File "/home/saar/stock/stock/test.py", line 14, in test
    x = await respon.json()
  File "/home/saar/stock/stock/test.py", line 18, in <module>
```

### Python Version

```console
Python Version: 3.10.1
```

### aiohttp Version

```console
aiohttp Version: 3.8.1
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
yarl Version: 1.7.2
```

### OS

ubuntu server 20.04.3

### Related component

Client

**Comment by asvetlov** [comment]
Because the server sends an invalid character I guess :)

**Comment by saarsa** [comment]
> Because the server sends an invalid character I guess :)

os.environ.setdefault('AIOHTTP_NO_EXTENSIONS', "1") need to work but it not

**Comment by asvetlov** [comment]
I see. The envvar should be set *before* the first `import aiohttp`.
Is it true in your case? I don't see such import in the example, which is suspicious.

**Comment by saarsa** [comment]
> 

ok
Thanks it really helped
