### ISSUE TITLE
Connectionerror when using manual proxy config

### ISSUE THREAD

**Issue by FuckingToasters** [fafhrd91/aiohttp#6554]
### Describe the bug

I have a pice of code, that checks of use_proxies is true and if so it select a random proxy from a textdocument if not it set the value to None what menas, it do the request without any proxy. This worked on the normal request libary when using `proxies` as an argument now it seems like aiohttp replaced `proxies` with `proxy` so i edited the request a bit and now i have a weird Traceback.
```py
    @commands.command(name='joke')
    async def joke(self, ctx):
        try:
            with open("proxies.txt", "r+") as f: proxy = "http://" + random.choice(f.readlines()).strip()
        except IndexError: pass  # print("No proxies found within proxies.txt! Executing the Command without any proxy...")
        await ctx.message.delete()
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Accept-encoding": "gzip, deflate, br",
            "Accept-language": "de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7",
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 OPR/81.0.4196.31"

        }
        async with aiohttp.ClientSession() as session:
            print(await session.get(f"https://icanhazdadjoke.com/", headers=headers, proxy=proxy if use_proxies == "true" else None))
 ```

### To Reproduce

1. changing all syncron requests to asyncron when using aiohttp
2,. having `use_proxies` set to "false"
3. proxy formatting in case i want to use them: `username:password@host:port`

### Expected behavior

Well i acutally expected it to work i guess

### Logs/tracebacks

```python-traceback
<ClientResponse(https://icanhazdadjoke.com/) [200 OK]>
<CIMultiDictProxy('Date': 'Sun, 23 Jan 2022 17:57:11 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-headers': 'User-Agent, Content-Type', 'access-control-allow-methods': 'GET', 'access-control-allow-origin': '*', 'access-control-max-age': '86400', 'access-control-request-method': 'GET', 'cache-control': 'max-age=0, must-revalidate, no-cache, no-store, public, s-maxage=0', 'retry-after': '60', 'x-frame-options': 'DENY', 'x-ratelimit-limit': '100', 'x-ratelimit-remaining': '99', 'x-ratelimit-reset': '1642960692', 'x-xss-protection': '1; mode=block', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=OAKJjLbTFdHcj1R6SbyY6RdrVp1rzsK5ilItybye0XkJqysZ0WszGJf5h4b2EfcI8MGpiz3IjfhkP6Ix1KItG7xZNR%2Fzh9S4fzcT0AYjVC1ezIU0BQeoZrN6uBqeb9tqRrqBkx%2F7e26qkdv3lDts0%2Fg%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Strict-Transport-Security': 'max-age=15552000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '6d22e72a8d774065-LHR', 'Content-Encoding': 'br', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400')>

Unclosed connection
client_connection: Connection<ConnectionKey(host='icanhazdadjoke.com', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None)>
```

### Python Version

```console
$ python --version

Python 3.10.0
```

### aiohttp Version

```console
$ python -m pip show aiohttp

Name: aiohttp
Version: 3.7.4.post0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: Nikolay Kim
Author-email: fafhrd91@gmail.com
License: Apache 2
Location: d:\private\downloads\python\lib\site-packages
Requires: async-timeout, attrs, chardet, multidict, typing-extensions, yarl
Required-by: discord.py
```

### multidict Version

```console
$ python -m pip show multidict

Name: multidict
Version: 5.2.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: d:\private\downloads\python\lib\site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl

Name: yarl
Version: 1.7.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: d:\private\downloads\python\lib\site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

WIndows 11

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> Well i acutally expected it to work i guess

Your output includes the response object you printed, so it looks like it is working...

Regarding the warning, see: https://docs.aiohttp.org/en/stable/client_advanced.html#graceful-shutdown
i.e. Add `await asyncio.sleep(.25)` to the end of the function or similar.

Edit: Actually, maybe that's not the same warning.

**Comment by FuckingToasters** [comment]
> > Well i acutally expected it to work i guess
> 
> Your output includes the response object you printed, so it looks like it is working...
> 
> Regarding the warning, see: https://docs.aiohttp.org/en/stable/client_advanced.html#graceful-shutdown i.e. Add `await asyncio.sleep(.25)` to the end of the function or similar.
> 
> Edit: Actually, maybe that's not the same warning.

The Response return a 200 statuscode (successful apicall) and returns the response object.
It somehow not manage to return the actual json response while it works as expected when using the request or the httpx libary.
It seem like the conection is not closed however because i use an context-manager it should be closed automatically.

I guess that the docs you just sent are not related to the issue i curretnly have because as you already metionedm it indeed is not the same warning.

**Comment by Dreamsorcerer** [comment]
> The Response return a 200 statuscode (successful apicall) and returns the response object. It somehow not manage to return the actual json response

Your example code doesn't ask for the JSON content... What happens if you add a `print(await resp.json())`?

> I guess that the docs you just sent are not related to the issue i curretnly have because as you already metionedm it indeed is not the same warning.

Have you tried adding an `await asyncio.sleep(.25)` to test it? I don't have any better ideas what it might be.
