### ISSUE TITLE
Website content is not up-to-date

### ISSUE THREAD

**Issue by tomzcn** [fafhrd91/aiohttp#6576]
### Describe the bug

https://docs.aiohttp.org/en/stable/client_quickstart.html

“asyncio.run(main)” should be “asyncio.run(main()) "

20220130

### To Reproduce

none

### Expected behavior

none

### Logs/tracebacks

```python-traceback
none
```

### Python Version

```console
none
```

### aiohttp Version

```console
none
```

### multidict Version

```console
none
```

### yarl Version

```console
none
```

### OS

macOS

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by tomzcn** [comment]
stable version is wrong.
latest version is correct.

**Comment by Dreamsorcerer** [comment]
As you pointed out, it's already been fixed. Will be deployed with the next release.

**Comment by tomzcn** [comment]
> As you pointed out, it's already been fixed. Will be deployed with the next release.

I think this is urgent.  I don't know how aiohttp will handle such an emergency.

**Comment by asvetlov** [comment]
> I think this is urgent.

Sorry, I disagree.
