### ISSUE TITLE
 [TODO] Adjust the GHA setup compatibility with `pip >= 22`

### ISSUE THREAD

**Issue by webknjaz** [fafhrd91/aiohttp#6578]
## Long story short

The newly released version requires an explicit `--user` in envs where there is a risk of damaging the interpreter distribution failing loudly.

Example: https://github.com/aio-libs/aiohttp/runs/4998902391?check_suite_focus=true#step:10:166.

**Comment by webknjaz** [comment]
@Dreamsorcerer @asvetlov FYI :point_up:

**Comment by Dreamsorcerer** [comment]
Ah, so the failures now are due to bumping pip without running the tests in Dependabot? I just saw this in #6555

**Comment by webknjaz** [comment]
> Ah, so the failures now are due to bumping pip without running the tests in Dependabot? I just saw this in #6555

I don't think pip is pinned anywhere.

**Comment by Dreamsorcerer** [comment]
Yeah, I remembered that the CI always upgrades to the latest version as an explicit step.

**Comment by webknjaz** [comment]
Yep. OTOH, if we were to use tox, then it'd have virtualenvs inside w/o this problem + we could probably pin stuff better.
