### ISSUE TITLE
Set is_multipart for FormData

### ISSUE THREAD

**Issue by hyzyla** [fafhrd91/aiohttp#6587]
### Is your feature request related to a problem?

I would like to send list of key-value strings as multipart/form-data using client library. For that, I tried to use FormData:

```python
form = aiohttp.FormData()
form.add_field('key', 'value')
```

But server that receive request, receive `application/x-www-form-urlencoded` string, instead of `multipart/from-data`. By looking into source code of `FormData` I found that `is_multipart` flag is set to `True` when I pass bytes or file as value. One way to force FormData to form multipart-form/data is to set private argument manually.
```python
form._is_multipart = True
```

### Describe the solution you'd like

I would like to have non-private option for `FormData` class to use `multipart-form/data`. I may be an option to `__init__.py` or it may be a setter for `is_multipart` property.

### Describe alternatives you've considered

Using:

```python
form._is_multipart = True
```

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Sounds reasonable. I wouldn't go for a setter, though, because this implies that a form instance is expected to change its mode in the middle of the runtime. I think it'd be reasonable to have it set at the initialization time.
Feel free to send a PR!
