### ISSUE TITLE
`custom regex` of router should support `\s` of the pattern

### ISSUE THREAD

**Issue by NewUserHa** [fafhrd91/aiohttp#6619]
### Describe the bug

router like `/{fn:\w+ \d+}` or `/{fn:\w+\s\d+}` can't match path like `/abc 123`,
because of the [coroutine resolve(request)](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.UrlDispatcher.resolve) uses [raw_path](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.BaseRequest.raw_path), which is `/abc%20123` and needs pattern like `/{fn:\w+%20\d+}`.

Usually, users will write ` ` or `\s` for a pattern instead of `%20`

### Python Version

```console
$ python --version
Python 3.8.10
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Version: 3.8.1
```

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by NewUserHa** [comment]
Also, if the URL has **special** (like `% {space}`) and **non-ascii** (other language characters) characters and is `urlencoded`, the `custom regex` can't work at all. (i.e. the users have to write the pattern with the urlencoded raw path)

**Comment by Dreamsorcerer** [comment]
I think spaces are typically discouraged in URLs, which is why this probably hasn't come up before. If you can come with an easy fix though, I'm sure we can consider merging it.

**Comment by NewUserHa** [comment]
say if the url is a totally valid file path and contains like `[ ] ( ) @`, then the regex of the route say like `@routes.get(r'/{fn:.+\[.+\].+)` then it can't ever work. (or checking containing other language characters in the route can't work too.)

How about [coroutine resolve(request)](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.UrlDispatcher.resolve) use `request.path` instead of `request.raw_path`?

**Comment by Dreamsorcerer** [comment]
I don't have time to take a look at the moment. But, I'd suggest trying the change and running the test suite, that will likely tell you if there are problems with the solution.
