### ISSUE TITLE
Incorrect type annotation or docs for TCPConnector(limit=...)

### ISSUE THREAD

**Issue by andrew222651** [fafhrd91/aiohttp#6623]
### Describe the bug

The docs for `TCPConnector` <https://docs.aiohttp.org/en/stable/client_reference.html#tcpconnector> say that the `limit` argument can be `None` but in the code it's annotated with type `int`:
<https://github.com/aio-libs/aiohttp/blob/a9f4746d32db963a8df80fd3e2299b7216b35d37/aiohttp/connector.py#L744>.

### To Reproduce

N/A

### Expected behavior

N/A

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
3.10
```

### aiohttp Version

```console
stable
```

### multidict Version

```console
N/A
```

### yarl Version

```console
N/A
```

### OS

N/A

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
This one says `0`: https://github.com/aio-libs/aiohttp/blob/a9f4746d32db963a8df80fd3e2299b7216b35d37/aiohttp/connector.py#L280

So, should probably update the documentation to that. The code appears to only check `if limit`, so both `0` and `None` should work at runtime.
