### ISSUE TITLE
CancelledError

### ISSUE THREAD

**Issue by H--o-l** [fafhrd91/aiohttp#6719]
### Describe the bug

Using the aiohttp web server, I struggle with `asyncio.CancelledError()` when a client disconnect for some time.
I shielded what needed to be but it has its limits.
Today I found this old PR:
https://github.com/aio-libs/aiohttp/pull/4080

It looks like my issue.
If I understand correctly  `asyncio.CancelledError()` was fixed at the beginning of v3.7.0 (1th October 2019).
But I still have frequent `asyncio.CancelledError()` in my server.

I have investigated a bit more and I find another PR, at the end of v3.7.0 (just before v3.7.0b0 I think) that for me re-introduce the issue:
https://github.com/aio-libs/aiohttp/pull/4415

For me the wrong code is the following:
```py
        if self._task_handler is not None:
            self._task_handler.cancel()
```    

It was removed by https://github.com/aio-libs/aiohttp/pull/4080 (and with all the documentation regarding this issue) but re-introduced silently by https://github.com/aio-libs/aiohttp/pull/4415.

I'm clearly not an expert so I'm not sure of what I'm saying, but does it make sense for you?

### To Reproduce

NA

### Expected behavior

NA

### Logs/tracebacks

```python-traceback
NA
```

### Python Version

```console
3.10.4
```

### aiohttp Version

```console
3.8.1
```

### multidict Version

```console
5.1.0
```

### yarl Version

```console
1.6.3
```

### OS

Fedora 35

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I think the first one caused a regression (as mentioned at https://github.com/aio-libs/aiohttp/issues/4408#issuecomment-572033137), so the second one has reverted that.

Not sure if the documentation should be reverted or if the plan is to improve this later. Will need some feedback from @asvetlov. Personally, I like the fact that the handler can be aborted as soon as the connection has dropped.

**Comment by H--o-l** [comment]
Hey @Dreamsorcerer thanks a lot for the quick answer!

In the following comment that proposed a fix to the regression it was only about `self._waiter.cancel()` not `self._task_handler.cancel()`:
https://github.com/aio-libs/aiohttp/pull/4415#issuecomment-689356233

The final fix of the regression does both `self._waiter.cancel()` and  `self._task_handler.cancel()`, maybe `self._task_handler.cancel()` was a mistake?

> Not sure if the documentation should be reverted or if the plan is to improve this later. 

OK!

> Personally, I like the fact that the handler can be aborted as soon as the connection has dropped.

I find a lot of all issues on the subject, most closed because the subject was thought to be close.
Personally, the solution I prefer would be one discussed in the below issue, with an `allow_cancel` parameter per route:
https://github.com/aio-libs/aiohttp/issues/2492#issue-272673197

The solution of https://github.com/aio-libs/aiohttp/pull/4080 is not ok for me, I need some part of my code to keep executing even when the client disconnect.
But at least the situation would be clearer, and easier to hack in a future proof way, if the code and doc were aligned.

**Comment by Dreamsorcerer** [comment]
> Personally, the solution I prefer would be one discussed in the below issue, with an `allow_cancel` parameter per route: [#2492 (comment)](https://github.com/aio-libs/aiohttp/issues/2492#issue-272673197)

Well spotted. Appears there's already a solution in master which closes the issue, even if it's not allowing cancellation throughout the app.


I think you're probably right, and that line can be reverted. Please make a PR.
Have you already tested the change fixes it for you? Ideally, with `-Wall -X dev`, so you can check those warnings don't return.

> The solution of #4080 is not ok for me, I need some part of my code to keep executing even when the client disconnect.

Well, that's what `asyncio.shield()` is for, to avoid cancellation. So, you can still use that for now, until the revert is released.

**Comment by H--o-l** [comment]
Hey @Dreamsorcerer !

> Have you already tested the change fixes it for you? Ideally, with -Wall -X dev, so you can check those warnings don't return.

I'm sorry, I don't understand the ` -Wall -X dev` you are talking about, I think I don't know the project well enough.

I still tried a few things.

With the simplest server example from here https://github.com/aio-libs/aiohttp/tree/0215cdd4275ea0150f169545b25b66e1f5dc69f0#server, I reverted https://github.com/aio-libs/aiohttp/pull/4415 with the following diff:
```diff
--- a/aiohttp/web_protocol.py
+++ b/aiohttp/web_protocol.py
@@ -331,10 +331,10 @@ class RequestHandler(BaseProtocol):
                 exc = ConnectionResetError("Connection lost")
             self._current_request._cancel(exc)
 
-        if self._task_handler is not None:
-            self._task_handler.cancel()
-        if self._waiter is not None:
-            self._waiter.cancel()
 
         self._task_handler = None
 ```

However, I'm not able to reproduce the issue described in https://github.com/aio-libs/aiohttp/issues/4408, so I can't test if I will re-create the regression or not.
I tried both on master and on v3.8.0.

I can't try on v3.7.0 because my server doesn't start:
```py
$ python test.py                                                                               16:52:00
Traceback (most recent call last):
  File "/home/hoel/Tolteck/test.py", line 2, in <module>
    from aiohttp import web
  File "/home/hoel/.local/lib/python3.10/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/hoel/.local/lib/python3.10/site-packages/aiohttp/client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "/home/hoel/.local/lib/python3.10/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import HeadersParser as HeadersParser
  File "/home/hoel/.local/lib/python3.10/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "/home/hoel/.local/lib/python3.10/site-packages/aiohttp/helpers.py", line 612, in <module>
    class CeilTimeout(async_timeout.timeout):
TypeError: function() argument 'code' must be code, not str
```

I did another test with the following smaller diff:
```diff
--- a/aiohttp/web_protocol.py
+++ b/aiohttp/web_protocol.py
@@ -331,8 +331,8 @@ class RequestHandler(BaseProtocol):
                 exc = ConnectionResetError("Connection lost")
             self._current_request._cancel(exc)
 
-        if self._task_handler is not None:
-            self._task_handler.cancel()
         if self._waiter is not None:
             self._waiter.cancel()
 ```
With the above diff, on client disconnection, I don't have `CancelledError` exception anymore, and in fact I don't have any exception, no `OSError`.
I think the doc say we should have `OSError` https://docs.aiohttp.org/en/stable/web_advanced.html?highlight=disconnection#peer-disconnection so my fix doesn't do what the documentation expects.

For info I'm using Python 3.10.4

What do you think?

**Comment by Dreamsorcerer** [comment]
> I'm sorry, I don't understand the ` -Wall -X dev` you are talking about, I think I don't know the project well enough.

`python -Wall -X dev`
It enables all warnings and developer mode features in python.

> I can't try on v3.7.0 because my server doesn't start:

That error is caused by an incompatible version of async-timeout. You would need to reinstall the correct dependencies when switching between versions.

> With the above diff, on client disconnection, I don't have `CancelledError` exception anymore, and in fact I don't have any exception, no `OSError`.

It says you'll get OSError when reading/writing. It also says that aiohttp will handle it, so I'd expect no exception to appear in your logs. If you want to test it, you'd probably have to add something to the end of your handler (i.e. after the disconnection happens) like:
```
try:
    await request.text()
except OSError:
    print("OSError occurred")
```

**Comment by H--o-l** [comment]
@Dreamsorcerer Thanks for your help! PR opened https://github.com/aio-libs/aiohttp/pull/6727

**Comment by Dreamsorcerer** [comment]
Any chance you managed to reproduce the warnings from #4408 with `python -Wall -X dev`?

**Comment by H--o-l** [comment]
Yes I did! You can see in the PR I talk about it in the end of the commit&PR message.

**Comment by Dreamsorcerer** [comment]
Ah, perfect, haven't got to the PR just yet. Thanks.

**Comment by Tinche** [comment]
Sorry for necroposting, I'm just now going through the aiohttp changelog.

There's no way to restore the old behavior, right? Changing this was big mistake in my mind. Task cancellation is one of asyncio superpowers, and the ability to clean up server resources when a client gives up is invaluable.

**Comment by Dreamsorcerer** [comment]
My understanding is that we received enough issues from users who did not expect this behaviour (and possibly didn't have the asyncio knowledge to handle it well), that the decision was made to remove it (back in the 3.7 release).

I kind of liked the cancellation feature, so I'd be open to accepting a PR which adds it back in as an opt-in feature.

**Comment by mosquito** [comment]
@Dreamsorcerer in #7056 I'm trying to fix it

**Comment by tzoiker** [comment]
To be honest, not cancelling by default on disconnections seems to be unintuitive to me. It seems that most of the time the client either wants some data or sends some to initiate changes. For the former there is no much sense processing any further on disconnect. For the latter, it can be done with background jobs while still responding to the client as quickly as possible. 

Background jobs can always be initiated with `asyncio.create_task`. Otherwise, you can shield it if you definitely need to wait for its completion before responding.

**Comment by Dreamsorcerer** [comment]
> It seems that most of the time the client either wants some data or sends some to initiate changes. For the former there is no much sense processing any further on disconnect. For the latter, it can be done with background jobs while still responding to the client as quickly as possible.

Yes, that's the ideal flow. But, most users don't realise that the disconnection may happen, so they don't even think to create a background task and then are confused why an update didn't happen or only partially happened.

> Background jobs can always be initiated with `asyncio.create_task`. Otherwise, you can shield it if you definitely need to wait for its completion before responding.

And this is somewhere we need to help educate users to do the right thing. You can't just use `asyncio.create_task()`, as you'd then need to keep track of the returned `Task` and remember to `await` it at some point. Failing to do so will result in unawaited warnings and missing exceptions in your code.

I think the best tool for these kind of fire-and-forget tasks we have currently is `aiojobs`, which will handle all that complexity for you.

**Comment by mosquito** [comment]
> Yes, that's the ideal flow. But, most users don't realise that the disconnection may happen, so they don't even think to create a background task and then are confused why an update didn't happen or only partially happened.

Safe code and simple code it's a tradeoff. It seems that there is a misunderstanding here, if somewhere you can create resources faster than the service can release resources, the server is always vulnerable to attacks of this kind.

It seems that this should be very detailed description in the documentation, and a safe default should be set.

> I think the best tool for these kind of fire-and-forget tasks we have currently is aiojobs, which will handle all that complexity for you.

Great, let's give this recommendation to anyone who wants their tasks to run after the client connection is terminated.

We have a lot of services running on aiohttp and expect the client to not be able to spawn hundreds of thousands of tasks just by disconnecting from the server.

**Comment by H--o-l** [comment]
@mosquito 
As long as your suggestion is opt-in I have nothing against it.
Other developers know what they are doing too, don't think you are the only one. You have a use case, we have other.
Shield was a headache for us, as catching exceptions in third-party middleware when the corresponding user had disconnected was really hard to do.
As for aiojobs: add dependencies and complexity in your project if you want, but don't force others to do it, by thinking your use-case is the only one that deserves to be the default.

Last thing, this PR only re-aligned aiohttp with its documentation, as the documentation made the change in v3.7. please discuss this change in the original v3.7 PR otherwise you are spamming me.

**Comment by balloob** [comment]
How come this was released in a patch release? This is a major behavioral and breaking change and should not have been put into 3.8.3. Instead, it should have been kept for 3.9.0, or even better 4.0.0.

**Comment by Dreamsorcerer** [comment]
> How come this was released in a patch release? This is a major behavioral and breaking change and should not have been put into 3.8.3. Instead, it should have been kept for 3.9.0, or even better 4.0.0.

It was released in 3.7. It was then accidentally reverted in 3.8, causing a regression, so was changed again in a patch release.

The memory issue you are experiencing sounds like a separate bug that should be looked at though. It doesn't seem like that should happen regardless of the cancellation method.

**Comment by H--o-l** [comment]
I think it was first released in a v3.7 beta or alpha, or RC or something like that, and reverted (only the code, not the doc, and inside an un-related commit) just before the final v3.7, so the code might never have reached an official final version before the v3.8.3 (but it was still listed in the changelog of the V3.7, and the documentation had changed).

**Comment by balloob** [comment]
@Dreamsorcerer the memory issue went away for Home Assistant users after downgrading to aiohttp 3.8.1.

It seems like there is a bug in 3.8.3 with StreamResponse which doesn't seem to raise on write when the client is gone. With 3.8.1 it gets cancelled when the client gets disconnected. I will try to make a small reproducing script for a new issue later today.

(update: unable to create a reproduce script but users issues went away, will dig further)

**Comment by Dreamsorcerer** [comment]
Any chance you are using ssl_context?
Seems we have a reproducer that only occurs if the server is handling TLS: #7172

**Comment by jsbronder** [comment]
> > How come this was released in a patch release? This is a major behavioral and breaking change and should not have been put into 3.8.3. Instead, it should have been kept for 3.9.0, or even better 4.0.0.
> 
> It was released in 3.7. It was then accidentally reverted in 3.8, causing a regression, so was changed again in a patch release.
> 
> The memory issue you are experiencing sounds like a separate bug that should be looked at though. It doesn't seem like that should happen regardless of the cancellation method.

I've been extensively relying on this behavior for at least 5 years, since
3.5.x, but probably for much longer.  While I haven't used every stable
release, it was definitely the behavior in 3.7.4.post0 [1] and 3.6.2 [2].
Browsing further, it looks like it was the behavior in 3.7.0 [3] and 3.8.0 as
well [4].  Despite what documentation was changed, I really think this should
be reversed and only changed in a new major release, it's definitely a backward
incompatible change.

1. https://github.com/aio-libs/aiohttp/blob/184274d9b28bbfa06ac60e48bf286a761c6a6cb0/aiohttp/web_protocol.py#L283
2. https://github.com/aio-libs/aiohttp/blob/6a5ab96bd9cb404b4abfd5160fe8f34a29d941e5/aiohttp/web_protocol.py#L243
3. https://github.com/aio-libs/aiohttp/blob/cac3cd2450953f5749eda4b5615d982d855ebfb9/aiohttp/web_protocol.py#L257
4. https://github.com/aio-libs/aiohttp/blob/208a4eb6dbf5373d9f5a9f18efac839a6448eadc/aiohttp/web_protocol.py#L300

**Comment by Dreamsorcerer** [comment]
It's opt-in for 3.9 and we have tests covering it to catch regressions now.
Should be able to push a beta release soon.

**Comment by H--o-l** [comment]
> I've been extensively relying on this behavior for at least 5 years, since
> 3.5.x, but probably for much longer. While I haven't used every stable
> release, it was definitely the behavior in 3.7.4.post0 [1] and 3.6.2 [2].
> Browsing further, it looks like it was the behavior in 3.7.0 [3] and 3.8.0 as
> well [4].

Just to help the next person finding this issue, I think the change was first introduced 22 commits before `v3.7.0b0`:
```
$ git name-rev --tags --name-only b8ba3d0cd63db671454cbfa832d58d8477850ece
v3.7.0b0~22
```
Then wrongly reverted (only a tiny bit of code was reverted, and the documentation changes weren't reverted) 4 commits before `v3.7.0b0`:
```
$ git name-rev --tags --name-only 69de6fe9f098ca51637d1269783e734dca0f9a34
v3.7.0b0~4
```
Maybe for better history and follow-up, discussions about this change should be posted on https://github.com/aio-libs/aiohttp/pull/4080 and not here, as my PR just fixed the revert. Indeed the revert did too much compared to what was expected (see https://github.com/aio-libs/aiohttp/commit/69de6fe9f098ca51637d1269783e734dca0f9a34#diff-e979a7e0fdf2258350295395380bf4b52346031bc1da69e81982040c20c31662R1).

> It's opt-in for 3.9 and we have tests covering it to catch regressions now.
> Should be able to push a beta release soon.

Nice!
Just for ref, here is the link to the PR https://github.com/aio-libs/aiohttp/pull/7056

**Comment by jsbronder** [comment]
> It's opt-in for 3.9 and we have tests covering it to catch regressions now. Should be able to push a beta release soon.

This is great and I'm happy to see the improvement.  However my point is that this is a backward incompatible change made in a patch release and should be reverted in 3.8.5.  That's assuming that the project is still following semver as stated here,  https://github.com/aio-libs/aiohttp/blob/a91a8aeebc9823ebd04c1516b3465922190e97e2/docs/faq.rst#what-is-the-api-stability-and-deprecation-policy.
