### ISSUE TITLE
Client example code is wrong in the stable version, but fixed in latest.

### ISSUE THREAD

**Issue by ikariwing** [fafhrd91/aiohttp#6755]
### Describe the bug

Client example code is wrong in the stable version doc:

```asyncio.run(main)```

https://docs.aiohttp.org/en/stable/client_quickstart.html

As a new comer, I spent some time to locate the reason.
Originally I'd like to write a PR to fix this but soon realized that this is already fixed in commit eef86e9e385e40e0b,
which is 2021/12/02, more than 5 months ago.

Now I am curious that how do we avoid the situation that somebody like me encountering the same issue repeatedly since I suppose we do have the need of keeping the corresponding doc for that version? 🤔 

Many thanks :) 

### To Reproduce

the example code in stable version is wrong.
https://docs.aiohttp.org/en/stable/client_quickstart.html

![CleanShot 2022-05-17 at 18 15 46@2x](https://user-images.githubusercontent.com/418952/168788746-591c54b8-84ea-48bc-ac1b-eb6201d129b1.png)

and it's right in the latest version
https://docs.aiohttp.org/en/latest/client_quickstart.html

![CleanShot 2022-05-17 at 18 14 30@2x](https://user-images.githubusercontent.com/418952/168788529-0ab45f63-10ec-48a2-8b41-34e8afde461f.png)

### Expected behavior

We can see the right doc for the previous version...

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
N/A
```

### aiohttp Version

```console
N/A
```

### multidict Version

```console
N/A
```

### yarl Version

```console
N/A
```

### OS

N/A

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
It's deployed with each release, so will be fixed when a new release is made.

**Comment by ikariwing** [comment]
thanks. If we cannot change the doc for previously released version, would it be possible to make sort of comment on it? 🤔
