### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kloczek** [fafhrd91/aiohttp#6758]
### Is your feature request related to a problem?

https://github.com/aio-libs/aiohttp/compare/v3.8.1...master shows +1.4k commits added since last release.
I think that it would be good to make new release 😋 

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Related component

Server and client

### Additional context

I just found that pytest is failing in my build env and when I found so many commits since last release I gave up to check across all those commits to find out it already known or not issue and/or do they have some solution.
Really please make new release because it would make work people like me easier.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
master is v4, I doubt it will get a proper release yet as all the maintainers are too busy. If you looked at those commits, you'd see they go back to 2018, yet the latest release you refer to was released a few months ago. Features landing in master are backported to 3.x branches in most cases, so counting commits from master is a useless metric.

**Comment by Dreamsorcerer** [comment]
In other words, here's the actual changes/fixes since last release:
https://github.com/aio-libs/aiohttp/compare/v3.8.1...3.8

And most of those commits will be relating to CI etc. which won't affect users.

**Comment by kloczek** [comment]
> In other words, here's the actual changes/fixes since last release:
> [v3.8.1...3.8](https://github.com/aio-libs/aiohttp/compare/v3.8.1...3.8)

That was not obvious 😋 
Thx.

OK will try to integrate all commits from 3.8 branch and if pytest will be still failing only than will open issue ticket 😃 
PS. Nevertheless +50 commits IMO is worth to flush as probably 3.8.2 as last release was +.5 year ago.
