### ISSUE TITLE
'Client Quickstart' documentation out-of-sync, containing an erroneous snippet

### ISSUE THREAD

**Issue by alexpovel** [fafhrd91/aiohttp#6768]
### Describe the bug

The [docs currently display this snippet](https://docs.aiohttp.org/en/stable/client_quickstart.html#make-a-request):

```python
import aiohttp
import asyncio

async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://httpbin.org/get') as resp:
            print(resp.status)
            print(await resp.text())

asyncio.run(main)
```

As-is, this snippet won't run, yielding `ValueError: a coroutine was expected, got <function main at 0x000001FA5597B490>`. That's of course because we mustn't pass the function object `main` itself but the coroutine returned from calling it, `main()`.

I wanted to create a short PR but this is actually already correct in the source:

https://github.com/aio-libs/aiohttp/blob/72d3d4b1f68cca5ad15ef50bffb0419b798c7f23/docs/client_quickstart.rst?plain=1#L36

So the docs simply need to be updated/regenerated I reckon. Perhaps other items are out-of-sync as well?

### To Reproduce

1. Run the above code snippet.

### Expected behavior

It prints a valid response.

### Logs/tracebacks

```python-traceback
ValueError: a coroutine was expected, got <function main at 0x000001FA5597B490>
```

### Python Version

```console
$ python --version
3.10.4
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
```

### multidict Version

```console
$ python -m pip show multidict
...
```

### yarl Version

```console
$ python -m pip show yarl
...
```

### OS

...

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Duplicate #6755
