### ISSUE TITLE
More secure hashing

### ISSUE THREAD

**Issue by cap-jmk** [fafhrd91/aiohttp#6785]
### Is your feature request related to a problem?

Running `bandit` on your dependency gives the warning 

```
 Issue: [B324:hashlib] Use of weak MD4, MD5, or SHA1 hash for security. Consider usedforsecurity=False
   Severity: High   Confidence: High
   CWE: CWE-327 (https://cwe.mitre.org/data/definitions/327.html)
   Location: ./venv/lib/python3.9/site-packages/aiohttp/web_ws.py:197:12
   More Info: https://bandit.readthedocs.io/en/1.7.4/plugins/b324_hashlib.html
196	        accept_val = base64.b64encode(
197	            hashlib.sha1(key.encode() + WS_KEY).digest()
198	        ).decode()

```

### Describe the solution you'd like

I think the algorithm is crackable. It is no longer approved by NIST (since 2010), I think. Maybe replacing it with a more secure hashing algorithm or method. 

### Describe alternatives you've considered

According to NIST it could be Maybe SHA2 or SHA3 (https://en.wikipedia.org/wiki/Secure_Hash_Algorithms)

### Related component

Server

### Additional context

Just routine security checking 

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
This is the websocket handshake protocol as defined in https://datatracker.ietf.org/doc/html/rfc6455#section-1.3

Changing the hash would presumably break all websockets...
