### ISSUE TITLE
add before request

### ISSUE THREAD

**Issue by thedtvn** [fafhrd91/aiohttp#6789]
### Is your feature request related to a problem?

before request for check login cookes

### Describe the solution you'd like

like before request of flask

### Describe alternatives you've considered

add before request and check is before request retun != None so do handle if not none skip handle and retun data in before request

### Related component

Server

### Additional context

no

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by thedtvn** [comment]
reopened reason : 
```py
async def before_request(request):
  session = await get_session(request)
  if session.get("login") == None:
    session["login"] = False
    return web.HTTPFound("/login")
    

@middleware
async def middleware(request, handler):
    resp = await before_request(request)
    if resp is None:
       resp = await handler(request)
    return resp
```
error : `RuntimeError: Install aiohttp_session middleware in your aiohttp.web.Application`

**Comment by Dreamsorcerer** [comment]
Read the documentation for aiohttp-session, you need to call `setup()` when creating your application:
https://aiohttp-session.readthedocs.io/en/stable/#usage

**Comment by Dreamsorcerer** [comment]
Otherwise, it looks like you've figured it out.

However, I'd recommend to `raise` the `HTTPFound` exception, and then not return anything. Which will also reduce your middleware to 2 lines (plus `return`ing an exception is deprecated behaviour).

**Comment by Dreamsorcerer** [comment]
```
@middleware
async def login_middleware(request, handler):
    session = await get_session(request)
    if not session.get("login") is None:
      session["login"] = False
      raise web.HTTPFound("/login")
    return await handler(request)
```

Although, you can also use aiohttp-security for this, rather than writing your own authentication code.

**Comment by thedtvn** [comment]
> Read the documentation for aiohttp-session, you need to call `setup()` when creating your application: https://aiohttp-session.readthedocs.io/en/stable/#usage

@Dreamsorcerer i run setup
is a cut of my code

**Comment by thedtvn** [comment]
> aiohttp-security



> ```
> @middleware
> async def login_middleware(request, handler):
>     session = await get_session(request)
>     if not session.get("login") is None:
>       session["login"] = False
>       raise web.HTTPFound("/login")
>     return await handler(request)
> ```
> 
> Although, you can also use aiohttp-security for this, rather than writing your own authentication code.

@Dreamsorcerer but is Easy to controle login and i save alot data in session not juse login data
like `refresh token` and `access token` like that 
*am doing discord bot login

**Comment by thedtvn** [comment]
@Dreamsorcerer 
![image](https://user-images.githubusercontent.com/80153297/174526847-e6f2509a-c068-44ca-9da7-cad43f4fa6bb.png)

**Comment by thedtvn** [comment]
@Dreamsorcerer and this is how to fix 
![image](https://user-images.githubusercontent.com/80153297/174527326-92eeee73-b512-40f0-8752-c737949fe380.png)

**Comment by Dreamsorcerer** [comment]
Ah, yes, I wasn't looking at the middleware ordering. I guess using aiohttp-session functions inside another middleware is not a common case.

**Comment by Dreamsorcerer** [comment]
> > aiohttp-security
> 
> > ```
> > @middleware
> > async def login_middleware(request, handler):
> >     session = await get_session(request)
> >     if not session.get("login") is None:
> >       session["login"] = False
> >       raise web.HTTPFound("/login")
> >     return await handler(request)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Although, you can also use aiohttp-security for this, rather than writing your own authentication code.
> 
> @Dreamsorcerer but is Easy to controle login

aiohttp-security should also be easy, but is also better tested/reviewed code, so you're less likely to introduce a security issue.

>  i save alot data in session not juse login data like `refresh token` and `access token` like that *am doing discord bot login

They are not mutually exclusive, you can still store data in the session (aiohttp-security itself just stores login data in the session under a custom key).
