### ISSUE TITLE
Default value of abstract cookie class methods

### ISSUE THREAD

**Issue by vvanglro** [fafhrd91/aiohttp#6791]
### Is your feature request related to a problem?

When the user only transmits `cookies`, `cookie_jar` is an instance of `CookieJar`, and the return type of the `cookie_jar` method of clientsession is `AbstractCookieJar`.
The `filter_cookies` method `response_url` of `AbstractCookieJar` is required,
`CookieJar` `filter_cookies` method `response_url` has a default value.
```py
import asyncio

import aiohttp


async def main():
    cookies = {'csrfToken': "my_value"}
    async with aiohttp.ClientSession(cookies=cookies) as session:
        session.cookie_jar.filter_cookies()

asyncio.run(main())
```
![image](https://user-images.githubusercontent.com/43594924/173532848-b2f475cb-973d-485f-81fc-dde9a67215c6.png)

### Describe the solution you'd like

change `filter_cookies` method `response_url` has a default value.
```py
    @abstractmethod
    def filter_cookies(self, response_url: URL = URL()) -> "BaseCookie[str]":
        """Return the jar's cookies filtered by their attributes."""
```

### Describe alternatives you've considered

.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
It's not clear to me why that default argument was added, or why you'd want to use it. My reading of the function is that it filters cookies according to the given URL (https://docs.aiohttp.org/en/stable/abc.html#aiohttp.abc.AbstractCookieJar.filter_cookies), so using it without a URL seems rather pointless.

What are you trying to achieve?

**Comment by vvanglro** [comment]
Yes, it doesn't make sense without url, and `filter_cookies`(of class CookieJar(AbstractCookieJar) method has a default value, which is very confusing, maybe it should be clear, the request_url of CookieJar filter_cookies is a required parameter of URL type, And the filter_cookies method also has a deprecation notice, which must be a parameter of type URL https://github.com/aio-libs/aiohttp/blob/339d7f0cc7193345b7409370ea5ff1ab39632116/aiohttp/cookiejar.py#L236
So it might be better to remove the default URL here.

**Comment by Dreamsorcerer** [comment]
The default has been removed.
