### ISSUE TITLE
Post request taking unusually long to reach server (~2.5 seconds)

### ISSUE THREAD

**Issue by skier233** [fafhrd91/aiohttp#6803]
### Describe the bug

I'm actually observing a bug in Rasa Open Source with a 2.5 second delay but I added debug statements in that code and was able to narrow down the source of the delay to an aiohttp call. 

I have this aiohttp call:

    async with aiohttp.ClientSession(timeout=timeout) as session:
        logger.debug("debug 28")
        async with session.post(url, json=payload, raise_for_status=True, ssl=False) as resp:

which calls into this in the server:

    @custom_webhook.route("/webhook", methods=["POST"])
    async def receive(request: Request) -> Union[ResponseStream, HTTPResponse]:
        logger.debug("debug 36")

and I'm seeing a delay of about 2.5 seconds between aiohttp sending this post request (debug 28) and the server receiving the request (debug 36). Does anyone know what the cause of this issue might be?

### To Reproduce

See above

### Expected behavior

An expected response time is expected

### Logs/tracebacks

```python-traceback
see above
```

### Python Version

```console
3.8.0
```

### aiohttp Version

```console
3.7.4
```

### multidict Version

```console
5.2.0
```

### yarl Version

```console
1.7.2
```

### OS

Windows python virtual environment

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by skier233** [comment]
Any help with this would be greatly appreciated!

**Comment by Dreamsorcerer** [comment]
You'd need to provide a complete reproducer. I can't see any reason this would have such a delay (unless you have such a large payload object that it takes over 2 seconds to run json.dumps()).
