### ISSUE TITLE
`web.run_app(path=)` should accept `pathlib.Path`

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#6839]
The `path` parameter to `web.run_app()`: https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.run_app

This should accept a `Path` object, to make things simpler.

**Comment by SamirPS** [comment]
Hello, when this function is define in the source code ? @Dreamsorcerer

**Comment by webknjaz** [comment]
> This should accept a `Path` object, to make things simpler.

How about `os.PathLike`?

_(https://github.com/aio-libs/aiohttp/pull/6843/files#r940309064)_

**Comment by Dreamsorcerer** [comment]
#6843 Done.
