### ISSUE TITLE
error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}

### ISSUE THREAD

**Issue by lucasjinreal** [fafhrd91/aiohttp#6854]
### Describe the bug

error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}

### To Reproduce

error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}

### Expected behavior

error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}

### Logs/tracebacks

```python-traceback
error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}
```

### Python Version

```console
error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}
$ python --version
```

### aiohttp Version

```console
$ python -m pip show aiohttp
error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}
```

### multidict Version

```console
$ python -m pip show multidict
error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}
```

### yarl Version

```console
$ python -m pip show yarl
error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}
```

### OS

error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}

### Related component

Server

### Additional context

error: async-timeout 4.0.2 is installed but async_timeout<4.0,>=3.0 is required by {'aiohttp'}

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
The error is from pip. Either the bug is with pip, or you just need to install the correct version of async-timeout.

If I install an older aiohttp package, then it downgrades async-timeout to the correct version. There must be a version conflict with the packages you have installed.

**Comment by lucasjinreal** [comment]
@Dreamsorcerer Obviously it's not pip issuee.....

I posted here is that, some other lib need aysnc-timeout in 4.0.x, but aiohttp need 3.x

and this lib is redis......

Please upgrade your dependencies.

**Comment by webknjaz** [comment]
> @Dreamsorcerer Obviously it's not pip issuee.....

Obviously you're using aiohttp version that isn't compatible with another library. Nothing to do for us here.

https://github.com/aio-libs/aiohttp/blob/v3.8.1/setup.cfg#L54.

**Comment by Dreamsorcerer** [comment]
```
> pip install aiohttp --upgrade
...
Installing collected packages: async-timeout, aiohttp
  Attempting uninstall: async-timeout
    Found existing installation: async-timeout 3.0.1
    Uninstalling async-timeout-3.0.1:
      Successfully uninstalled async-timeout-3.0.1
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 3.6.3
    Uninstalling aiohttp-3.6.3:
      Successfully uninstalled aiohttp-3.6.3
Successfully installed aiohttp-3.8.1 async-timeout-4.0.2
```

Current release uses 4+. Please upgrade your dependencies.
