### ISSUE TITLE
Please upgrade aiohttp version on pypi.......

### ISSUE THREAD

**Issue by lucasjinreal** [fafhrd91/aiohttp#6858]
### Is your feature request related to a problem?

Please upgrade aiohttp version on pypi.......

### Describe the solution you'd like

Please upgrade aiohttp version on pypi.......

### Describe alternatives you've considered

Please upgrade aiohttp version on pypi.......

### Related component

Server

### Additional context

Please upgrade aiohttp version on pypi.......

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by lucasjinreal** [comment]
@yannick 
<img width="348" alt="image" src="https://user-images.githubusercontent.com/21303438/182643541-e9ae12bf-def0-4c79-abc7-0c2e4534523f.png">

someone says aihttop using 4.0x aiotimeout, but the pypi still old version

**Comment by Dreamsorcerer** [comment]
> someone says aihttop using 4.0x aiotimeout, but the pypi still old version

If you are referring to my comment: https://github.com/aio-libs/aiohttp/issues/6854#issuecomment-1204163736
I clearly show using `pip install` with version 3.8.1. This version already uses async-timeout 4+.

Creating a new release will not change the version of async-timeout. Regardless, I'm sure we'll get a new release out soon with some minor bug fixes.

**Comment by lucasjinreal** [comment]
@Dreamsorcerer thanku! I noticed github is using 4+ version already, but seems pypi didn't get upgrade a long time. Make sync would help us best use this lib also catch up with redis lib.

**Comment by Dreamsorcerer** [comment]
Again, the PyPI version (3.8.1) is already using async-timeout 4+. When we push a new release, it will still be using async-timeout 4+, nothing will change.
