### ISSUE TITLE
We are getting random requests terminations on idling POST

### ISSUE THREAD

**Issue by mykola-mokhnach** [fafhrd91/aiohttp#6881]
### Describe the bug

Our service is behind an API gateway. It server multiple endpoints and they work properly except of the one, which is responsible for file upload. This endpoint supports POST multipart/mixed file uploads, but it also stalls for a while after the request body is fully processed, so the server could process the uploaded file and return a response. 
Randomly HTTP clients observe 503 error responses similar to 

```
ACCESS [2022-08-12T11:26:17.296Z] "POST /v1/storage/upload HTTP/1.1" 503 UC 106754313 95 21212 - "<ip>" "curl/7.29.0" "4f094110-cf38-4f45-88fa-c391744e85cb" "<host>" "<ip>"
```

"UC" in such case means "Upstream disconnect" according to https://blog.getambassador.io/understanding-envoy-proxy-and-ambassador-http-access-logs-fee7802a2ec5

And on the service side the exception is 

```
asyncio.exceptions.CancelledError
```

Initially this looks like the request is being cancelled by a client, but even when I try to wrap the route handler into asyncio.shield like

```
    task = asyncio.start_task(yolo())
    try:
        await asyncio.shield(task)
    except asyncio.CancelledError:
        await task
        raise
```

it still cancels the wrapped task. This does not happen for a "normal" client-initiated disconnect, where CancelledError is only raised once.

The common pattern for such disconnects is that they all happen when the body is fully fetched by the server and the file payload parsing starts (connection is idling from an HTTP client perspective during this time). I've tried to enable aihttp debug/access log, but to no extent.

### To Reproduce

See above

### Expected behavior

See above

### Logs/tracebacks

```python-traceback
See above
```

### Python Version

```console
$ python --version
Python 3.9.13
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.1
```

### multidict Version

```console
$ python -m pip show multidict
6.0.2
```

### yarl Version

```console
$ python -m pip show yarl
1.7.2
```

### OS

python:3.9-slim-bullseye

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Some more code would be useful. Ideally an entire test case that allows us to easily reproduce it.

One thought is that if it is getting stuck while processing the file after upload, maybe it is because the code is blocking while processing the file. If you are running with all debug features on (e.g. `python -Wall -X dev`) then I'd expect you to atleast get some warnings from asyncio about function calls taking too long (anything >100ms should trigger it).

**Comment by mykola-mokhnach** [comment]
Thanks for the response @Dreamsorcerer 

It is true, the file parsing code might block for a while as it uses some third-party libraries, which are not async in their nature, and file I/O (also sync). I was trying to wrap all such calls into `run_in_executor` and we have also added an additional asyncio monitor that measures duration of blocking chunks. Nevertheless I still have a feeling it chokes somewhere when FS I/O or CPU usage becomes too intensive as files might significantly differ in size and complexity.

So, the only way to address this issue would be to move file parsing into a separate service, and it is impossible to guarantee aiohttp would not terminate a connection if a synchronous block happens?

**Comment by Dreamsorcerer** [comment]
asyncio in general is only meant to work correctly if nothing blocks for more than 100ms. So, if you resolve the blocking issues, and the problem still persists, then we'll have to figure out what is broken. But, currently it sounds like the blocking code is the problem, stopping asyncio/aiohttp operating correctly.

If your file processing code is Python code as well, then running in a thread is probably not much help. I'd run it in a subprocess to ensure it's not blocking your main application: https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.create_subprocess_exec

**Comment by mykola-mokhnach** [comment]
> asyncio in general is only meant to work correctly if nothing blocks for more than 100ms

Just out of curiosity: is there a way to increase this timeout to simply verify the assumption is right and no disconnects will be observed afterwards? Could you please point me to the block of code in the library which is responsible for such behaviour?

**Comment by mykola-mokhnach** [comment]
What is also a bit confusing to me: we use the following code to log blocking events and aio loop delays:

```python
import asyncio
import inspect
from typing import Callable, Dict, Any, Optional

from aiohttp.web import Application

from src.monitor.events import EventLoopBlockingTimeEvent, EventLoopDelayEvent, HandlerInfo
from src.utils.logger import make_logger

log = make_logger('Event loop monitor')
UNKNOWN_HANDLER_NAME = 'unknown_handler'


def _extract_task_from_handle(handle: asyncio.events.Handle) -> Optional[asyncio.tasks.Task]:
    cb = getattr(handle, '_callback', None)
    return getattr(cb, '__self__', None)


def _format_handle(handle: asyncio.events.Handle) -> HandlerInfo:
    """
    This is inspired from asyncio.base_events._format_handle
    """
    task = _extract_task_from_handle(handle)
    coroutine = getattr(task, '_coro', None)
    if coroutine:
        local_vars = inspect.getcoroutinelocals(coroutine)  # type: Dict[str, Any]
        name = getattr(coroutine, '__qualname__', None) or \
            getattr(coroutine, '__name__', None) or \
            UNKNOWN_HANDLER_NAME
        return HandlerInfo(name, repr(handle), local_vars)
    return HandlerInfo(UNKNOWN_HANDLER_NAME, repr(handle), {})


def monitor_blocking_methods(execution_time_sec: float, app: Application,
                             *callbacks: Callable[[Application, EventLoopBlockingTimeEvent], None]):
    """
    Patch ``asyncio.events.Handle`` to log warnings every time a callback takes ``duration`` seconds
    or more to run.

    @param execution_time_sec:
    @param app:
    @param callbacks: any callable that accepts ``aiohttp.web.Application`` and ``EventLoopDelayEvent`` as params
    """
    _run = getattr(asyncio.events.Handle, '_run', None)

    def instrumented(self: asyncio.events.Handle):
        loop = asyncio.get_event_loop()
        t0 = loop.time()
        # We have to get the repr and args before actually running it because after running it
        # the frame will be lost
        try:
            handler_info = _format_handle(self)
        except Exception as _:
            log.exception('Got an unexpected exception while formatting the handler info')
            handler_info = HandlerInfo(UNKNOWN_HANDLER_NAME, repr(self), {})
        assert _run
        _run(self)
        dt = loop.time() - t0
        if dt >= execution_time_sec:
            event = EventLoopBlockingTimeEvent(handler_info, dt)
            for callback in callbacks:
                callback(app, event)

    setattr(asyncio.events.Handle, '_run', instrumented)


def monitor_event_loop_delay(interval_sec: int, app: Application,
                             *callbacks: Callable[[Application, EventLoopDelayEvent], None]):
    """
    Monitors event loop delay or lag

    @param interval_sec:
    @param app:
    @param callbacks: any callable that accepts ``aiohttp.web.Application`` and ``EventLoopDelayEvent`` as params
    """
    loop = asyncio.get_event_loop()

    def watcher(start_time: float):
        latency = (loop.time() - start_time) - interval_sec
        for callback in callbacks:
            callback(app, EventLoopDelayEvent(latency))
        loop.call_later(interval_sec, watcher, loop.time())

    watcher(loop.time())


....


from dataclasses import dataclass
from typing import Any, Dict


@dataclass
class HandlerInfo:
    name: str
    full_repr: str
    local_vars: Dict[str, Any]


@dataclass
class EventLoopBlockingTimeEvent:
    handler_info: HandlerInfo
    execution_time_sec: float


@dataclass
class EventLoopDelayEvent:
    delay_sec: float


....

from aiohttp.web import Application

# HANDLER_EXECUTION_TIME_LIMIT_SEC = 0.1
# EVENT_LOOP_MONITORING_TASK_INTERVAL_SEC = 60
# EVENT_LOOP_DELAY_LOGGING_THRESHOLD_MS = 50

from src.models.constants import HANDLER_EXECUTION_TIME_LIMIT_SEC, EVENT_LOOP_MONITORING_TASK_INTERVAL_SEC
from src.monitor.events_handlers import log_blocking_handler_event, log_event_loop_delay_event
from src.monitor.event_loop import monitor_blocking_methods, monitor_event_loop_delay


def setup_monitor(app: Application):
    monitor_blocking_methods(HANDLER_EXECUTION_TIME_LIMIT_SEC, app, log_blocking_handler_event)
    monitor_event_loop_delay(EVENT_LOOP_MONITORING_TASK_INTERVAL_SEC, app, log_event_loop_delay_event)

```

I see some correlation between these logs and connection termination failures but it turns out connections terminations still happen more often then these events get logged. This probably means aiohttp drops the connection even if shorter blocking events happen

**Comment by Dreamsorcerer** [comment]
I don't know what code might be causing timeouts, as I haven't got the time to dig into your issue presently. The 100ms rule is an estimate for all of asyncio, it is not expected to behave correctly if you are blocking for longer than that.

> This probably means aiohttp drops the connection even if shorter blocking events happen

Unless you are looking at the events in more detail, it may just be that you have several tasks which block for shorter periods of time before aiohttp's task is run. e.g. if you have 10 tasks taking 500ms before aiohttp's task is run, then that is 5 seconds before aiohttp can do anything.

As mentioned before, you should get these long running warnings if you use Python's dev mode. Instrumenting the code like that shouldn't be necessary.

**Comment by mykola-mokhnach** [comment]
Thank you @Dreamsorcerer for following our issue. I really appreciate that.

I'm not sure it would be a good idea to run python in dev mode on a production server. Unfortunately I cannot reproduce the issue in staging env though - it looks it only happens if high load is observed. I've also tried to put a vanilla `time.sleep(10)` into the the async file upload handler to simulate the above behaviour, but that did not change anything, - the connection is still intact.

**Comment by mykola-mokhnach** [comment]
When I simulate high CPU load in the local container plus blocking calls I still cannot reproduce the original disconnect issue, although getting some more interesting warnings, that probably have to do with aiohttp:

```
WARNING:asyncio:Executing <Task pending name='Task-3866' coro=<TCPConnector._resolve_host() running at /root/.local/share/virtualenvs/app-storage-service-evEBRps7/lib/python3.8/site-packages/aiohttp/connector.py:880> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.8/asyncio/futures.py:360, <TaskWakeupMethWrapper object at 0x7ff86871ce90>()] created at /usr/local/lib/python3.8/asyncio/base_events.py:422> cb=[shield.<locals>._inner_done_callback() at /usr/local/lib/python3.8/asyncio/tasks.py:885] created at /root/.local/share/virtualenvs/app-storage-service-evEBRps7/lib/python3.8/site-packages/aiohttp/connector.py:1147> took 0.196 seconds

WARNING:asyncio:Executing <Task pending name='Task-3864' coro=<MinIOClient.upload_file() running at /opt/app-storage-service/src/storage/minio.py:179> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff867f5ffd0>()] created at /usr/local/lib/python3.8/asyncio/base_events.py:422> cb=[_wait.<locals>._on_completion() at /usr/local/lib/python3.8/asyncio/tasks.py:518] created at /usr/local/lib/python3.8/asyncio/tasks.py:382> took 0.195 seconds

WARNING:asyncio:Executing <Task pending name='Task-3869' coro=<ClientRequest.write_bytes() running at /root/.local/share/virtualenvs/app-storage-service-evEBRps7/lib/python3.8/site-packages/aiohttp/client_reqrep.py:583> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.8/asyncio/futures.py:360, <TaskWakeupMethWrapper object at 0x7ff8689d1f50>()] created at /usr/local/lib/python3.8/asyncio/base_events.py:422> created at /root/.local/share/virtualenvs/app-storage-service-evEBRps7/lib/python3.8/site-packages/aiohttp/client_reqrep.py:671> took 0.103 seconds

WARNING:asyncio:Executing <Task pending name='Task-9' coro=<RequestHandler._handle_request() running at /root/.local/share/virtualenvs/app-storage-service-evEBRps7/lib/python3.8/site-packages/aiohttp/web_protocol.py:435> wait_for=<Future pending cb=[shield.<locals>._outer_done_callback() at /usr/local/lib/python3.8/asyncio/tasks.py:902, <TaskWakeupMethWrapper object at 0x7ff868646390>()] created at /usr/local/lib/python3.8/asyncio/base_events.py:422> cb=[<TaskWakeupMethWrapper object at 0x7ff869c3fb50>()] created at /root/.local/share/virtualenvs/app-storage-service-evEBRps7/lib/python3.8/site-packages/aiohttp/web_protocol.py:510> took 0.109 seconds

```

**Comment by Dreamsorcerer** [comment]
Not too sure if any of those will help you find the issue or not. But, first one looks like it's related to DNS resolution. That might be resolved by installing aiodns (though I'm not too sure how the default one works..).

2nd seems to be coming from /opt/app-storage-service/src/storage/minio.py:179, so I'd suggest looking into that one and checking what is happening there. Would be bad if it's blocking on a file upload.

No clue why the 3rd one would happen.

I suspect the 4th one is to do with the request handler (i.e. the function you have assigned to the route, or possibly some middleware).

Unfortunately, it's going to be rather tricky to figure out, if the issue can't be reproduced outside of your production server.

**Comment by mykola-mokhnach** [comment]
It turned out the connection has been cancelled because of a bug in a third party module: https://github.com/talkiq/gcloud-aio/pull/500

Although we had quite a hard time while figuring out where exactly this exception is thrown because of the way aiohttp handlers react to CancelledError. Basically, it is not clear whether this was aiohttp, which initiated the cancellation, or the handler itself. Perhaps, the situation could be improved since Python 3.9, where it is possible to provide a custom exception message to the `cancel` API call., or some additional debug logs could be added to aiohttp itself to confirm "external" cancellation.

Nevertheless, many thanks for your insights @Dreamsorcerer 

P. S. The blocking issue 

```
function TCPConnector._resolve_host (<Handle <TaskStepMethWrapper object at 0x7f160f4c3d90>()>) was blocking the loop for 116.7574618011713 ms, called with args self: <aiohttp.connector.TCPConnector object at 0x7f1610853be0>, host: oauth2.googleapis.com, port: 443, traces: []
```

is still being observed randomly even after aiodns has been added to projects dependencies. I assume it should be reported as an issue to the above gcloud-aio lib as well.
