### ISSUE TITLE
when is the next release?

### ISSUE THREAD

**Issue by tooptoop4** [fafhrd91/aiohttp#6883]
### Describe the solution you'd like

CVEs gone

### Describe alternatives you've considered

s3fs use this

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
When we get to releasing it. Still need to merge some Python 3.11 things.

There are no CVEs to be 'gone'.
