### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte... invalid start byte

### ISSUE THREAD

**Issue by desireewilliams** [fafhrd91/aiohttp#6902]
### Describe the bug

When sending a POST request to an API that returns a PDF response, I'm unable to receive the data as the response is automatically trying to be decoded instead of simply returning the content 

### To Reproduce

> import os
import asyncio
import aiohttp

> async def getReport(session,reportUrl:str,anItem:str) :
    # the payload is application specific and in the correct format
    payload = '{"timezone":"local","format":"pdf","itemID":"'+ anItem + '"}'
    print(f'Starting a report')
    async with session.post(url=reportUrl,data=payload,ssl=False) as resp: 
       response = await resp
    print(f'Finishing a report')
    return response.content

> async def getAllReport(baseUrl:str,headers:str,itemList:list,path:str='/reportPath/'):
    async with aiohttp.ClientSession(headers=headers) as session:
        reportUrl = baseUrl + '/reportGenerationAPI'
        tasks = []
        for anItem in itemList:
            tasks.append(asyncio.ensure_future(getReport(session=session,reportUrl=reportUrl,anItem=anItem)))
        allReports = await asyncio.gather(*tasks)
        n = 0
        for aReport in allReports:
            filename = f'{path}{n}.pdf' 
            n = n + 1
            with open(filename,'wb') as f:
                f.write(aReport)

> baseUrl = 'https://myAPIurl'
headers = {'Authorization': 'Bearer ' + aToken,
    'Content-Type': 'application/json'}
itemList = []
itemList.append('guid1')
itemList.append(guid2')

> asyncio.run(getAllReport((baseUrl=baseUrl,headers=headers,itemList=ids))

### Expected behavior

If no method is called, I would expect that the response be what ever is received from the API.

### Logs/tracebacks

```python-traceback
... lib\site-packages\aiohttp\client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 124: invalid start byte
```

### Python Version

```console
$ python --version
Python 3.10.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
aiohttp 3.8.1
```

### multidict Version

```console
$ python -m pip show multidict
N/A
```

### yarl Version

```console
$ python -m pip show yarl
N/A
```

### OS

Windows

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by mshandrovskiy** [comment]
Set `auto_decompress=False` if you need to disable it.

**Comment by desireewilliams** [comment]
> 

ok, so the ClientSession has been updated to
> async with aiohttp.ClientSession(headers=headers,auto_decompress=False) as session:

and now I'm getting a:
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream'

which is where I was before I started getting it to read the content and error on the decode.

**Comment by mshandrovskiy** [comment]
It's hard to tell since your code is not properly formatted or runnable. I tried to run a best guess and it's broken in a way that makes me thing this is not your actual implmentation.

```
  File "/Users/mikes/.pyenv/versions/3.10.6/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/mikes/.pyenv/versions/3.10.6/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/mikes/PycharmProjects/ansible2/aiohttp_test.py", line 23, in getAllReport
    allReports = await asyncio.gather(*tasks)
  File "/Users/mikes/PycharmProjects/ansible2/aiohttp_test.py", line 10, in getReport
    response = await resp
TypeError: object ClientResponse can't be used in 'await' expression
```

Looking at your error thou, you are probably trying to load it as JSON when it's supposed to be a PDF response.

**Comment by Dreamsorcerer** [comment]
Yes, you've not provided the full traceback to see what you are actually doing. But, the error is in a call to `resp.json()`, which is obviously not going to work on a PDF.

**Comment by desireewilliams** [comment]
Apologies for not posting the full traceback, but it has references (names) that I can't post. I went back through as I was previously getting the 'object ClientResponse can't be used in 'await' expression' prior to the invalid bytes, and the code did revert back to that. I think something is buggy on my side as it throws some combination of those two errors as I launch different python sessions in the same virtual environment. I'll create a new environment from version control and start over. 

Pulling your documentation on client side calls, I think the auto_decompress=False is what I need. Thank you for the patience!
