### ISSUE TITLE
Aiohttp conflicts with other asyncio functions [Ubuntu 18.04.5]

### ISSUE THREAD

**Issue by internall** [fafhrd91/aiohttp#6913]
### Describe the bug

I am running a locally hosted server using aiohttp, simultaneously with other asyncio functions including telethon client. My code works just fine on windows, however, when I run it on my vps (Ubuntu 18.04.5) aiohttp's server "blocks" other asyncio functions (such as telethon client).

Here is what my code looks like
```
app = web.Application()


async def payment_notification(request):
    '''
    handles /payment_notification post request
    '''
    pass

...

loop = asyncio.get_event_loop()

async def multiple_functions():
    task1 = loop.create_task(func())
    task2 = loop.create_task(func2())

    await client.disconnect()

loop.run_until_complete(multiple_functions())

client.connect()

app.add_routes([web.post("/payment_notification", payment_notification)])
web.run_app(app)
```

On ubuntu, this prints "Running on 0.0.0.0 ..." but my telethon client will work only if stop aiohttp (ctrl + c)

### To Reproduce

OS: Ubuntu 18.04.5
python 3.6.9
Libraries needed: telethon - aiohttp

### Expected behavior

Both the server and the client should work at the same time.

### Logs/tracebacks

```python-traceback
Running on 0.0.0.0
```

### Python Version

```console
$ python --version
3.6.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8
```

### multidict Version

```console
$ python -m pip show multidict
5.1.0
```

### yarl Version

```console
$ python -m pip show yarl
 1.6.3
```

### OS

Ubuntu 18.04.5

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
They're not being blocked, they're in a different loop and therefore not being run at all.
Please consdier `run_app()` to be the equivalent of `asyncio.run()` and should therefore be the main entry point of your application:
https://docs.aiohttp.org/en/stable/web_advanced.html#complex-applications
