### ISSUE TITLE
aiohttp 3.8.1 speedups still include cchardet

### ISSUE THREAD

**Issue by gilbahat** [fafhrd91/aiohttp#6914]
### Describe the bug

It appears that the fix in https://github.com/aio-libs/aiohttp/issues/6819 is incomplete or otherwise fails to register with pypi:

$ curl -s https://pypi.org/pypi/aiohttp/json | jq ".info.requires_dist"
[
  "attrs (>=17.3.0)",
  "charset-normalizer (<3.0,>=2.0)",
  "multidict (<7.0,>=4.5)",
  "async-timeout (<5.0,>=4.0.0a3)",
  "yarl (<2.0,>=1.0)",
  "frozenlist (>=1.1.1)",
  "aiosignal (>=1.1.2)",
  "idna-ssl (>=1.0) ; python_version < \"3.7\"",
  "asynctest (==0.13.0) ; python_version < \"3.8\"",
  "typing-extensions (>=3.7.4) ; python_version < \"3.8\"",
  "aiodns ; extra == 'speedups'",
  "Brotli ; extra == 'speedups'",
  "cchardet ; extra == 'speedups'"
]

one would expect cchardet to be marked by a python_version marker, yet it is not.
I suspect the problem might be with https://github.com/aio-libs/aiohttp/blob/master/requirements/constraints.txt#L27 which does not contain a marker.

please advise.

### To Reproduce

Create a pyproject.toml with aiohttp version 3.8.1 with speedups in an environment with python3.10
run poetry update

### Expected behavior

poetry lock file does not contain cchardet

### Logs/tracebacks

```python-traceback
n/a
```

### Python Version

```console
3.10
```

### aiohttp Version

```console
3.8.1
```

### multidict Version

```console
n/a
```

### yarl Version

```console
n/a
```

### OS

MacOS X Monterey 12.5.1

### Related component

Client

### Additional context

I found out that cchardet was still being installed in my python 3.10 project.
surprisingly enough, it worked still.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
It was closed only last month. There has not been a new release in that time. It sounds like we're close to a new release, so it will be available when that happens.
