### ISSUE TITLE
No info about request in access log if request is cancelled

### ISSUE THREAD

**Issue by ValeryVS** [fafhrd91/aiohttp#7010]
### Describe the bug

Http request is cancelled. For example, with [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) from browser. If there is no `except CancelledError` in handler, there will not be an access log entry about this request.

### To Reproduce

```
from asyncio import CancelledError

from aiohttp import web

async def handler(self, request: Request):
    try:
        # some code
        return
    except CancelledError:
        logger.error('import location cancelled')

api_router = web.Application()

api_router.router.add_post(
    '/do-something',
    handler,
)
```

### Expected behavior

I'm not sure, but, probably, there should be access log entry about request even if there was CancelledError and it was not handled. Otherwise, how I should know about these requests?

### Logs/tracebacks

```python-traceback
-
```

### Python Version

```console
$ python --version
3.10.4
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.1
```

### multidict Version

```console
$ python -m pip show multidict
6.0.2
```

### yarl Version

```console
$ python -m pip show yarl
1.8.1
```

### OS

https://hub.docker.com/layers/library/python/3.10.4/images/sha256-16f3cde3d42a8049c4668d85a874abd5684e2c634b189dfab30506d30495f408?context=explore

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Personally, I'd deploy behind nginx and get the access logs from there.

But, if you can create a PR with a test that reproduces the problem, then I'm sure we can figure out a fix.

However, I don't think the handler will be cancelled with aiohttp 3.8.2+ (this was a regression in 3.8.0 for a behaviour which was removed in 3.7).
