### ISSUE TITLE
Accept bytes as valid Headers value

### ISSUE THREAD

**Issue by MarkJiYuan** [fafhrd91/aiohttp#7024]
### Is your feature request related to a problem?

I tried to send a request with headers that value is bytes object using aiohttp client, resulted in such error:
```
File "/root/projects/lox_pkg/test/aiohttp_test/http_writer.py", line 130, in write_headers
    buf = _serialize_headers(status_line, headers)
  File "aiohttp/_http_writer.pyx", line 132, in aiohttp._http_writer._serialize_headers
  File "aiohttp/_http_writer.pyx", line 109, in aiohttp._http_writer.to_str
TypeError: Cannot serialize non-str key b'uQeQ8DTG2ndsfzv82aDyaXYi3eBoXDhULL/7F8tRRwjwyY='
```

Here are my code snippets:
```python
API_URL = 'https://api.kucoin.com'
uri = '/api/v1/sub/user'
headers = {
    "KC-API-SIGN": sign,
    "KC-API-TIMESTAMP": str(current_ts),
    "KC-API-KEY": api_key,
    "KC-API-PASSPHRASE": passphrase,
    "Content-Type": "application/json",
    "KC-API-KEY-VERSION": "2"
}

async with aiohttp_test.ClientSession() as session:
    async with session.get(API_URL + uri, headers=headers) as resp:
        print(resp.status)
        print(await resp.json())
```

The reason is value of "KC-API-SIGN" is `bytes` object instead of `str`, so simply decode them works well. But when using other HTTP libraries such as `requests`, `urllib3`, it doesn't matter explicitly convert to `str` or not. So it would be a pleasure that same code can work for both async or sync HTTP library.

Code example:
```python
# raise Error
async with aiohttp_test.ClientSession() as session:
    async with session.get(API_URL + uri, headers=headers) as resp:
        print(resp.status)
        print(await resp.json())

# works well
r = requests.get(API_URL + uri, headers=headers)
print(r.status_code)
print(r.json())

# works well too
http = urllib3.PoolManager()
r = http.request('GET', API_URL + uri, headers=headers)
print(json.loads(r.data.decode('utf-8')))
```

### Describe the solution you'd like

I dive into aiohttp's code, and find that problem is due to this function: `_serialize_headers` in `http_writer.py`.
```python
def _safe_header(string: str) -> str:
    if "\r" in string or "\n" in string:
        raise ValueError(
            "Newline or carriage return detected in headers. "
            "Potential header injection attack."
        )
    return string

def _py_serialize_headers(status_line: str, headers: "CIMultiDict[str]") -> bytes:

    headers_gen = (_safe_header(k) + ": " + _safe_header(v) for k, v in headers.items())
    line = status_line + "\r\n" + "\r\n".join(headers_gen) + "\r\n\r\n"
    return line.encode("utf-8")


_serialize_headers = _py_serialize_headers

try:
    import aiohttp._http_writer as _http_writer  # type: ignore[import]

    _c_serialize_headers = _http_writer._serialize_headers
    if not NO_EXTENSIONS:
        _serialize_headers = _c_serialize_headers
except ImportError:
    pass
```
Whether using C EXTENSIONS or not, this function requires headers value to be `str`. In order to make simplest change,  I suggest to convert `bytes` to `str` before `_serialize_headers` function call. 
Here are my solution:
```python
async def write_headers(
    self, status_line: str, headers: "CIMultiDict[str]"
) -> None:
    """Write request/response status and headers."""
    if self._on_headers_sent is not None:
        await self._on_headers_sent(headers)
    
    # Accept bytes header value
    for k in list(headers.keys()):
        v = headers[k]
        if hasattr(v, "decode"):
            headers[k] = v.decode("utf-8")

    # status + headers
    buf = _serialize_headers(status_line, headers)
    self._write(buf)
```
I'm still a naive developer, so not knowing whether this is acceptable or not, Please give me some advices.

### Describe alternatives you've considered

It cost me some time to figure out the header implementation differences between `aiohttp` and python built-in `http` library. So may be we can add some hints in the doc.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> ```python
> async def write_headers(
>     self, status_line: str, headers: "CIMultiDict[str]"
> ) -> None:
>     """Write request/response status and headers."""
>     if self._on_headers_sent is not None:
>         await self._on_headers_sent(headers)
>     
>     # Accept bytes header value
>     for k in list(headers.keys()):
>         v = headers[k]
>         if hasattr(v, "decode"):
>             headers[k] = v.decode("utf-8")
> 
>     # status + headers
>     buf = _serialize_headers(status_line, headers)
>     self._write(buf)
> ```

I think this just negatively impacts performance just to convert bytes to str. If you are stuck with bytes in your application, it makes more sense to me to just convert to str in your code. Atleast then the performance impact is explicit in your code.

The proposed code would also impact performance for everyone who are _not_ using bytes.

**Comment by Dreamsorcerer** [comment]
Also, the code always converts from `utf-8`, I don't think aiohttp should just assume the encoding of your bytes..

**Comment by MarkJiYuan** [comment]
Yes, I agree.
