### ISSUE TITLE
https proxies

### ISSUE THREAD

**Issue by Lamchi-Joo** [fafhrd91/aiohttp#7032]
### Is your feature request related to a problem?

Does aiohtto support https proxy?if not,When is expected to support?

### Describe the solution you'd like

answer me 

### Describe alternatives you've considered

nothing

### Related component

Server, Client

### Additional context

nothing

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Is this not in the docs? https://docs.aiohttp.org/en/stable/client_advanced.html#proxy-support
Particularly the warning box at the bottom that explains the current state of TLS-in-TLS proxies.

**Comment by Dreamsorcerer** [comment]
As far as I can tell, that means in should be working with aiohttp 3.8+ and Python 3.11+.
