### ISSUE TITLE
AttributeError: '<class 'pydap.model.DatasetType'>' object has no attribute 'decode'

### ISSUE THREAD

**Issue by faridfarhat** [fafhrd91/aiohttp#7065]
### Describe the bug

I want to access GPM precipitation from NASA. But when I open the data with xarray, it returns this attribute error. I also updated xarray to the latest version, as was suggested in previous issues. Still it is not working. 

### To Reproduce

dataset

### Expected behavior

xarray dataset

### Logs/tracebacks

```python-traceback
import xarray as xr
from pydap.client import open_url
from pydap.cas.urs import setup_session

url='https://gpm1.gesdisc.eosdis.nasa.gov/opendap/GPM_L3/GPM_3IMERGDE.06/2000/06/3B-DAY-E.MS.MRG.3IMERG.20000601-S000000-E235959.V06.nc4'

session = setup_session('myusername, 'mypassword')
dataset = open_url(url, session=session)

xr.open_dataset(dataset,engine='pydap')

AttributeError: '<class 'pydap.model.DatasetType'>' object has no attribute 'decode'
```

### Python Version

```console
$ python --version
3.10
```

### aiohttp Version

```console
$ python -m pip show aiohttp
NA
```

### multidict Version

```console
$ python -m pip show multidict
NA
```

### yarl Version

```console
$ python -m pip show yarl
NA
```

### OS

macOS

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
So, register a bug against pydap, instead of a totally unrelated library?
