### ISSUE TITLE
Backslashes stripped from multipart form filenames

### ISSUE THREAD

**Issue by barneygale** [fafhrd91/aiohttp#7070]
### Describe the bug

I'm dealing with a slightly wonky HTTP client that sends _full file paths_ in the 'filename' field of a form data part. Like:

```
POST /test.html HTTP/1.1
Host: example.org
Content-Type: multipart/form-data;boundary="boundary"

--boundary
Content-Disposition: form-data; name="uploadfile"; filename="C:\Users\me\example.txt"

value2
--boundary--
```

However, when I read the request with `await request.post()`, I find that the filename has been mangled to `C:Usersmeexample.txt`, i.e. the backslashes have been removed.

[The standards don't agree](https://github.com/curl/curl/issues/7789#issuecomment-930138204) on how backslashes should be supplied, but the [WHATWG spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#multipart-form-data) seemed to be followed by the CURL folks, and it *doesn't* suggest that backslashes need to be doubled, nor escape-encoded. Therefore I think this is a bug in aiohttp.

### To Reproduce

1. Implement an HTTP client that sends a full Windows-style file path as the filename in a multipart form data request
2. Call `data = await request.post()` and print `data['uploadfield'].filename`

### Expected behavior

The original filename is reproduced

### Logs/tracebacks

```python-traceback
Actual behaviour: the backslashes are stripped.
```

### Python Version

```console
$ python --version
Python 3.10.4
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by: aiobotocore
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Requires: idna, multidict
Required-by: aiohttp
```

### OS

macOS 12; CentOS 7

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by barneygale** [comment]
Problematic code: https://github.com/aio-libs/aiohttp/blob/71ae610e4d8350f1f1f121164b75ce3ad78d7902/aiohttp/multipart.py#L95-L96

Originates here: https://github.com/aio-libs/aiocouchdb/commit/c68b11d8356b843774ce091cc6353389c612dced

**Comment by Dreamsorcerer** [comment]
According to the commit, it was implemented against a set of tests. It looks like that code was designed to handle quoted strings, where it is assuming the backslashes are escape characters, like in this test: http://test.greenbytes.de/tech/tc2231/#attabspathwin

If that is correct, then the client should be sending `\\` in order to properly quote it.

There appears to be a test that exactly matches this case too:
http://test.greenbytes.de/tech/tc2231/#attfncontqs

So, that's why it strips the backslashes.

I've no idea if that should be changed or not.

**Comment by barneygale** [comment]
Those test cases seem to predate [RFC 7578](https://www.rfc-editor.org/rfc/rfc7578) and [WHATWG](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#multipart-form-data). The WHATWG standard is a 'living document' that better reflects what clients/servers actually do nowadays.

**Comment by Dreamsorcerer** [comment]
Then maybe it needs to be updated. If you want to make a PR, we can look at updating it.

**Comment by barneygale** [comment]
Finally got around to opening a PR! #7257

**Comment by barneygale** [comment]
Invalid per RFC 7230:

> Recipients that process the value of a quoted-string MUST handle a quoted-pair as if it were replaced by the octet following the backslash.
