### ISSUE TITLE
ClientSession TRACE method support

### ISSUE THREAD

**Issue by vkosuri** [fafhrd91/aiohttp#7071]
### Is your feature request related to a problem?

When Try to use TRACE method ClientSession Object no attribute trace, aiohttp==3.8.3

``` Python
async with aiohttp.ClientSession() as session:
    action = getattr(session, 'trace')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'ClientSession' object has no attribute 'trace'
```

### Describe the solution you'd like

Trace support for ClientSession as per RFC https://httpwg.org/specs/rfc9110.html#TRACE
```Python
async with aiohttp.ClientSession() as session:
    action = getattr(session, 'trace')
```
### Describe alternatives you've considered

NA

### Related component

Client

### Additional context

NA

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
We don't have a method for connect either. Just use the request() method: https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession.request

I'm not sure that method is useful enough to be worth adding a dedicated method.
