### ISSUE TITLE
aiohttp-3.8.3 fails to compile on Gentoo Linux because Makefile shell is not bash

### ISSUE THREAD

**Issue by cengique** [fafhrd91/aiohttp#7073]
### Describe the bug

Compilation failure on Gentoo Linux (and potentially other systems, see below for logs and explanation)

### To Reproduce

Build error

### Expected behavior

Compile without errors

### Logs/tracebacks

```python-traceback
Build fails because of the following error:


>>> Emerging (1 of 3) dev-python/aiohttp-3.8.3-r1::gentoo
 * Fetching files in the background.
 * To view fetch progress, run in another terminal:
 * tail -f /var/log/emerge-fetch.log
 * aiohttp-3.8.3.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                                [ ok ]
>>> Unpacking source...
>>> Unpacking aiohttp-3.8.3.tar.gz to /var/tmp/portage/dev-python/aiohttp-3.8.3-r1/work
>>> Source unpacked in /var/tmp/portage/dev-python/aiohttp-3.8.3-r1/work
>>> Preparing source in /var/tmp/portage/dev-python/aiohttp-3.8.3-r1/work/aiohttp-3.8.3 ...
 * Build system packages:
 *   dev-python/gpep517            : 9
 *   dev-python/installer          : 0.5.1-r1
 *   dev-python/setuptools         : 65.5.1
 *   dev-python/setuptools_scm     : 7.0.5
 *   dev-python/wheel              : 0.37.1-r1
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/aiohttp-3.8.3-r1/work/aiohttp-3.8.3 ...
 * Checking whether python3_11 is suitable ...
 *   >=dev-lang/python-3.11.0_beta4:3.11 ...                                                                                                                                                       [ !! ]
 * Checking whether python3_10 is suitable ...
 *   >=dev-lang/python-3.10.4:3.10 ...                                                                                                                                                             [ ok ]
 *   python_check_deps ...                                                                                                                                                                         [ ok ]
 * Using python3.10 in global scope
 * python3_10: running distutils-r1_run_phase python_configure_all
make -j9 requirements/.hash/cython.txt.hash 
make: command: Command not found
/bin/sh: line 1: ./tools/check_sum.py: No such file or directory
```

In the PyPI.org distro tar.gz file, there is no `tools/check_sum.py` included, so the `ifneq` statement on `Makefile:28` will fail on some systems. 

On my system, I actually have `sha256sum` installed, but the if statement fails by not finding `command`, which is a Bash builtin command. This is because the default shell in the Makefile is not specified as Bash. It can be fixed by adding:

```
SHELL:=/bin/bash
```
```


### Python Version

```console
$ python --version
python-3.10.4:3.10 .
```

### aiohttp Version

```console
$ python -m pip show aiohttp
aiohttp-3.8.3
```

### multidict Version

```console
$ python -m pip show multidict
Version: 6.0.2
```

### yarl Version

```console
$ python -m pip show yarl
Version: 1.8.1
```

### OS

Description:    Gentoo Linux
Release:        2.8

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
cc @mgorny

**Comment by mgorny** [comment]
What shell are you using? FWICS `command` is required by POSIX, and both dash and posh support it, so it sounds like a broken shell.

**Comment by cengique** [comment]
@mgorny I use bash, but it doesn't seem to be the one employed by `make` since `command` works in bash. Why not add a `SHELL:=` line to enforce the shell you want to be used?

**Comment by mgorny** [comment]
…because that would mean it wouldn't work at all on systems without bash?

**Comment by cengique** [comment]
This is a bit strange. Apparently, the default SHELL inside Makefiles on my system is `/bin/sh`. However, if I define `SHELL` - even setting it to `/bin/sh` - makes the `$(shell command ...)` work again. On my system `/bin/sh` is a symlink to `bash` anyway. So I'm not sure what is happening. 

There is another problem with the Makefile: if sha256sum doesn't exist on a system, then it looks for the tools/check_sum.py which is not in the distribution packages.

Another alternative is checking existence of sha256sum without using shell and command? Maybe something like this:
https://stackoverflow.com/questions/23245308/check-file-existence-with-makefile-conditional

**Comment by mgorny** [comment]
> Another alternative is checking existence of sha256sum without using shell and command? Maybe something like this:
> https://stackoverflow.com/questions/23245308/check-file-existence-with-makefile-conditional

That would work only if you could rely on specific path (and you can't, that will break e.g. Gentoo Prefix).

The problem seems to exist in your make or shell. Perhaps it'd be better to file a Gentoo bug and try to figure out what's wrong there first.

**Comment by thesamesam** [comment]
Downstream bug is https://bugs.gentoo.org/880633. Let's discuss there.

**Comment by mgorny** [comment]
It turned out that it was a problem with GNU make 4.2. Upgrading to 4.3 resolved the problem.
