### ISSUE TITLE
Implement `WebSocketResponse.get_extra_info`

### ISSUE THREAD

**Issue by xdustinface** [fafhrd91/aiohttp#7078]
### Is your feature request related to a problem?

There is no way to access `get_extra_info` from a `WebSocketResponse`, like its possible in `ClientWebSocketResponse`, there was a related issue before this was implemented: https://github.com/aio-libs/aiohttp/issues/1717.

### Describe the solution you'd like

Im thinking about just having `WebSocketResponse.get_extra_info` implemented like `ClientWebSocketResponse.get_extra_info`.

### Describe alternatives you've considered

As workaround we just access the private member like in 

```python
response._writer.transport.get_extra_info("the info")
```

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
#7658

**Comment by Dreamsorcerer** [comment]
#7658
