### ISSUE TITLE
Server examples are failing with AttributeError: module 'aiohttp' has no attribute 'web'

### ISSUE THREAD

**Issue by rutgerhendriks** [fafhrd91/aiohttp#7116]
### Describe the bug

I tried to follow the server examples in:
https://docs.aiohttp.org/en/stable/web_quickstart.html
but there is no 'web' attribute on aiohttp
In __init__.py there is no mention of importing web, so that seems to be the issue to me

### To Reproduce

1. import aiohttp (v3.8.3)
2. aiohttp.web gives attributeerror

### Expected behavior

aiohttp.web exist

Manually editing __init__.py and adding:
from . import web as web
seems to solve my issue

### Logs/tracebacks

```python-traceback
~$ python3
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiohttp
>>> aiohttp.web
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aiohttp' has no attribute 'web'
>>>
```

### Python Version

```console
$ python --version
3.10.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.3
```

### multidict Version

```console
$ python -m pip show multidict
6.0.2
```

### yarl Version

```console
$ python -m pip show yarl
1.7.2
```

### OS

Ubuntu 22.04

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I don't see `aiohttp.web` referenced in those examples.
They all use `from aiohttp import web`, which is a submodule. I believe only client parts are imported into `aiohttp` namespace, in order to avoid increasing import time for everyone only using the client.
You could also just `import aiohttp.web`.
