### ISSUE TITLE
Shouldn't `session.close()` be a sync function?

### ISSUE THREAD

**Issue by NewUserHa** [fafhrd91/aiohttp#7118]
### Is your feature request related to a problem?

```py
import weakref
import aiohttp
class FOO():
  def __init__(self):
    self.session = aiohttp.ClientSession()
    self._finalizer = weakref.finalize(self, self._close) # ?

  def _close(self):
    ... #?

  def close(self):
    await self.session.close()

  async def run():
    do_task()
```

### Describe the solution you'd like
https://github.com/aio-libs/aiohttp/blob/30b7a4e99677b4014dda2372504343bb05fc983e/aiohttp/connector.py#L406-L412
in 3.8.3, it can use `_close()`.
https://github.com/aio-libs/aiohttp/blob/ba0c9bb1d0a78001584367429a59c84bbcdc8015/aiohttp/connector.py#L372-L383
But in the main branch, the code can't.

The class should be used repeatedly as library like `foo=FOO(); await foo.run(); await foo.run()` or by users like `asyncio.run(FOO().run())`

Then the session can't be closed via the pythonic `finalize` without `asyncio.create(self.session.close())`.
### Describe alternatives you've considered
The session could be like the returned `response.close()` or `[BaseTransport.close](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.close)` that can be closed sycnly

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> Then the session can't be closed via the pythonic `finalize` without `asyncio.create(self.session.close())`.

That doesn't look pythonic to me. The pythonic solution is to make your code explicit and handle the lifetime of the object with `async with`.

If it's not an async function, then we can't ensure the connections are closed when the function returns, which results in unexpected behaviour for users and warnings being triggered by Python (about unclosed sockets or similar).

**Comment by NewUserHa** [comment]
Then there're endless nested `async with`.
And you can not share the session but only pass it all around via argument of functions.

Then how is it possible to automatically clean up when the object is garbage collected? rather than closed manually by users?

The response has sync function `.close()`, the session has sync function `_close()` in version 3.8.3 too, but the master deleted it.

**Comment by Dreamsorcerer** [comment]
> Then there're endless nested `async with`. And you can not share the session but only pass it all around via argument of functions.

You're sharing the session by passing it to functions. You only need 1 `async with` at the top-level, depending on how you structure your code. e.g. In an aiohttp server application, you'd just make it available on the global app object with a cleanup_ctx:

```
async def client_session(app):
    async with ClientSession() as sess:
        app["session"] = sess
        yield
app.cleanup_ctx.append(client_session)
```

> Then how is it possible to automatically clean up when the object is garbage collected? rather than closed manually by users?

"explicit > implicit". Cleaning up on garbage collection is not recommended (if it was, we wouldn't get unclosed socket warnings and the like from Python), and would be awkward to do with async code (as you've already pointed out).

Why do you think users can't use `async with` (I've no idea what your application is)?

> The response has sync function `.close()`, the session has sync function `_close()` in version 3.8.3 too, but the master deleted it.

I think if you look through the git history, you'll find the bug reports that lead to it. I'm pretty sure it was because of the issues I referred to earlier, which couldn't be fixed properly in 3.x. We have to ignore some warnings in 3.x in order to work around it.

**Comment by NewUserHa** [comment]
> you'll find the bug reports that lead to it

you mean `ResourceWarning: unclosed transport #1925`?

I check `trio` and see it has both `.close()` and `.aclose()` on `tcptransport`

> (I've no idea what your application is)?

It's the client, that doesn't have `app.cleanup_ctx`.
so if want to close a session inited in `__init__`, it's hard to achieve, unless uses lock that can be released in sync.

**Comment by Dreamsorcerer** [comment]
I don't think we'll do this, as we aim to provide safe asyncio code. The methods need to be async to avoid blocking the event loop while also ensuring that everything is cleaned up and closed when the function returns.

Unless a good example is given that explains why we'd want a sync version which doesn't have this guarantee and will likely lead to errors/warnings, I don't see it happening.
