### ISSUE TITLE
filter_cookies only acceps URL and not string

### ISSUE THREAD

**Issue by magicmatt007** [fafhrd91/aiohttp#7121]
### Describe the bug

The documentation of filter_cookies(), as well as many code examples, are using String as the function parameters:

" filtered = session.cookie_jar.filter_cookies('http://httpbin.org')"
https://docs.aiohttp.org/en/stable/client_advanced.html#cookie-jar

When trying to do this with Python 3.11, I get an error.

Looking at the source code of aiohttp, you can see that the function actually expects an URL object and only has a error catching for String.

 deffilter_cookies(
        self, request_url: URL=URL()
    ) 

Error catching:
ifnotisinstance(request_url, URL):
            warnings.warn(
                "The method accepts yarl.URL instances only, got {}".format(
                    type(request_url)
                ),
                DeprecationWarning,
            )
            request_url=URL(request_url)

Other functions like get() officially accept URL and String for an url:

 defget(
        self, url: StrOrURL, *, allow_redirects: bool=True, **kwargs: Any
    ) ->"_RequestContextManager":

Shouldn't filter_cookies also officially be implemented to accept String?

### To Reproduce

see above

### Expected behavior

see above

### Logs/tracebacks

```python-traceback
see above
```

### Python Version

```console
$ python --version
3.11
```

### aiohttp Version

```console
$ python -m pip show aiohttp

3.8.3
```

### multidict Version

```console
$ python -m pip show multidict

6.0.3
```

### yarl Version

```console
$ python -m pip show yarl

1.8.2
```

### OS

Windows 10

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
https://github.com/aio-libs/aiohttp/pull/3753

Says that this is internal to aiohttp.

https://docs.aiohttp.org/en/stable/client_advanced.html#custom-cookies

Suggests otherwise...

So, maybe we can officially support `str` if that's useful.

**Comment by Dreamsorcerer** [comment]
At the same time, it's only used for some trivial demo. Do you have a use case for `.filter_cookies()`?

**Comment by magicmatt007** [comment]
I had used the requests library before and was looking for a shorthand to get a certain session cookie.

with requests, that was fairly easy:
  s = requests.Session()
   ....
  csrf = s.cookies['CSRF']

With aiohttp, I have to loop through all cookies manually to find the desired one. Not a big deal, but I thought that the filter_cookies could be an more elegant way. That said, it still would only allow to filter for a domain and not a certain cookie name. So even if support for str was officially added, it wouldn't solve my usecase.

I was mainly confused that the examples in the doc use str, whilst filter_cookies doesn't officially support it... So either support it, or update the doc :-)
