### ISSUE TITLE
Client raises asyncio.TimeoutError

### ISSUE THREAD

**Issue by poofeg** [fafhrd91/aiohttp#7122]
### Describe the bug

Client raises `asyncio.TimeoutError`, although according to the documentation it seems that [`aiohttp.ServerTimeoutError`](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ServerTimeoutError) should be raised.

### To Reproduce

1. Run `nc -l 8000`
2. Run:
```python
import aiohttp
import asyncio


async def main():
    timeout = aiohttp.ClientTimeout(total=10)
    async with aiohttp.ClientSession(timeout=timeout) as session:
        try:
            async with session.get('http://127.0.0.1:8000'):
                pass
        except aiohttp.ServerTimeoutError:
            print('aiohttp.ServerTimeoutError')
        except aiohttp.ClientError:
            print('aiohttp.ClientError')
        except asyncio.TimeoutError:
            print('asyncio.TimeoutError')


if __name__ == '__main__':
    asyncio.run(main())
```
3. Wait 10 seconds
4. Get result: "asyncio.TimeoutError"

### Expected behavior

Result: "aiohttp.ServerTimeoutError"

### Logs/tracebacks

```python-traceback
asyncio.TimeoutError
```

### Python Version

```console
3.11.0
```

### aiohttp Version

```console
3.8.3
```

### multidict Version

```console
6.0.2
```

### yarl Version

```console
1.8.1
```

### OS

macOS 12.6.1

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Hey @graingert, can this be related to your patch #6877?

**Comment by webknjaz** [comment]
Looks like the code does raise `ServerTimeoutError` on (1) connection timeout
(https://github.com/aio-libs/aiohttp/blob/0d39c84ad47115b7b0af411fa3a6080c56f3cdff/aiohttp/client_proto.py#L197) and on read timeout (https://github.com/aio-libs/aiohttp/blob/0d39c84ad47115b7b0af411fa3a6080c56f3cdff/aiohttp/client.py#L504)

**Comment by poofeg** [comment]
This is not a new behavior. At least since version 2.3.10, this case raises `asyncio.TimeoutError` exception.

**Comment by nick-merrill** [comment]
Thanks for posting this question @poofeg. I had thought we had handled timeouts in our retry logic, but we didn't identify this exception as one that needs to be handled as well.

I would suggest:
1. Update the [documentation](https://docs.aiohttp.org/en/stable/client_reference.html#client-exceptions) to clarify that `asyncio.TimeoutError` may be raised in the event of a timed-out request.
2. Consider (but probably avoid) raising `ServerTimeoutError` instead of `asyncio.TimeoutError` in this case.

Do people agree the documentation should be updated to call out this behavior?

**Comment by Dreamsorcerer** [comment]
@webknjaz @bdraco Any opinion on these timeouts?
Currently (atleast on master), ConnectionTimeoutError is thrown for connect and sock_connect, SocketTimeoutError for sock_read, and TimeoutError for total.
As it's a total timeout, not specific to the server connection, maybe it makes sense to keep as a TimeoutError?

Also, I noticed that ClientResponse.start() reenters the same timer context that is already being used in the parent Client._request() call, which seems redundant.


> but we didn't identify this exception as one that needs to be handled as well.

Not as well. It's the only one that needs to be handled as it is the parent for all timeout exceptions.

**Comment by Dreamsorcerer** [comment]
> Also, I noticed that ClientResponse.start() reenters the same timer context that is already being used in the parent Client._request() call, which seems redundant.

This could have been planned for future timeouts though (there are several proposed timeouts commented out in ClientTimeout).

**Comment by bdraco** [comment]
I don't have a strong opinion either way as long as the docs reflect what actually happens.  I would consider this issue closed by the changes proposed in https://github.com/aio-libs/aiohttp/pull/8968
