### ISSUE TITLE
support for non absolute urls

### ISSUE THREAD

**Issue by vkosuri** [fafhrd91/aiohttp#7142]
### Is your feature request related to a problem?

I am trying to test one of my servers with a non-absolute URI through a proxy server using aiohttp. unfortunately, aiohttp complains InvalidURL exception. This feature is really useful to perform some kind of negative testing 

```Python
import aiohttp
import asyncio

async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get(url='/get', proxy='http://proxy.com') as resp:
            print(resp.status)
            print(await resp.text())

asyncio.run(main())

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "test.py", line 6, in main
    async with session.get(url='/get', proxy='http://proxy.com') as resp:
  File "/home/kosuri/gitswarm/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/kosuri/gitswarm/venv/lib/python3.8/site-packages/aiohttp/client.py", line 508, in _request
    req = self._request_class(
  File "/home/kosuri/gitswarm/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/home/kosuri/gitswarm/venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: /get
```

### Describe the solution you'd like

The current approach is checking ``host`` instead it use for ``path``
```
>>> import yarl
>>> url = yarl.URL('hello')
>>> url.host
>>> url.path
'hello'
>>> 
```

### Describe alternatives you've considered

NA

### Related component

Client

### Additional context

NA

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I'm not sure I understand what you are trying to achieve, really. Where do you expect it to make the request to? My reading of the code is that a host is needed to open a connection: https://github.com/aio-libs/aiohttp/blob/d51013db325f18e2c663ffc3828c74d36ca299f1/aiohttp/connector.py#L1087

Curiously though, the possibillity of a relative URL did come up in a PR this week: https://github.com/aio-libs/aiohttp/pull/7131#issuecomment-1363204012
Though I was imagining more of a custom class which handles the host directly, rather than trying to connect to no host.

**Comment by Dreamsorcerer** [comment]
Ah wait, host is set to the proxy URL at that point, maybe it can work.

Seems like the kind of edge case that's not worth supporting for us though, I'd suggest trying to subclass `ClientRequest` for this specific case and passing the custom class to `ClientSession`.

**Comment by webknjaz** [comment]
HTTP requests need a target host. Proxy is just a transport and the queries are sent through it but it's not an endpoint. Looks like you're confusing concepts here. The URL is not valid because the HTTP query wouldn't know where to send the requests without a host set.

**Comment by vkosuri** [comment]
@webknjaz thanks, we are trying to do some kind of negative testing using our proxy sits and transmitting the information to the server where we need to verify the non-absolute uris.

``` Topology
client -> proxy -> server
```

**Comment by webknjaz** [comment]
So you're trying to use aiohttp for testing your proxy? That's weird and you wouldn't be able to intercept TLS traffic anyway.
Also, aiohttp is not designed to produce malformed requests. Why don't you just have raw HTTP in your tests?

**Comment by vkosuri** [comment]
Thanks, I am trying to do that unfortunately I did not any examples for proxy, is there any example to do for http proxy t?

**Comment by webknjaz** [comment]
You'll probably need to find a way to write raw requests over a TCP connection. But aiohttp is not a testing framework, and it's not designed to be used maliciously either.
I've seen examples of such low-level stuff @ https://github.com/cherrypy/cheroot/blob/57fc412/cheroot/test/test_conn.py#L742-L745 / https://github.com/cherrypy/cheroot/blob/57fc412/cheroot/test/test_core.py#L339-L342 / https://github.com/aio-libs/aiohttp/blob/743c21f/tests/test_http_writer.py#L282-L285, but that's not to be considered public API.

FWIW, you should be able to achieve what you want using stdlib's [`http.client.HTTPConnection`](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection) if writing synchronous code works for you.

Closing per above.

**Comment by vkosuri** [comment]
Thanks for the examples @webknjaz, I will go through them.
