### ISSUE TITLE
Doc: Typo ContentDisposition

### ISSUE THREAD

**Issue by solarjoe** [fafhrd91/aiohttp#7151]
### Describe the bug

Current doc states `ContentDisposition` has a field `value`

https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ContentDisposition
But it is `type`. 

https://github.com/aio-libs/aiohttp/blob/5bf9b4aae7046704b418c16452c2d1ced934abfb/aiohttp/client_reqrep.py#L96

### To Reproduce

Just a typo.

### Expected behavior

-

### Logs/tracebacks

```python-traceback
-
```

### Python Version

```console
-
```

### aiohttp Version

```console
-
```

### multidict Version

```console
-
```

### yarl Version

```console
-
```

### OS

-

### Related component

Client

### Additional context

-

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
You're right, feel free to send a PR.

**Comment by solarjoe** [comment]
PR created.
https://github.com/aio-libs/aiohttp/pull/7154
