### ISSUE TITLE
Incorrect parsing of HTTP status line in the C implementation

### ISSUE THREAD

**Issue by emontnemery** [fafhrd91/aiohttp#7165]
### Describe the bug

The parsing of HTTP status lines with multiple spaces between the HTTP version and the status code trips up the C implementation, which incorrectly sets the response status to 0.

### To Reproduce

```
>>> from aiohttp import http_parser
>>> p = http_parser.HttpResponseParserPy(1, None, 2**16); p.feed_data("HTTP/1.1  200 OK\r\n\r\n".encode())[0][0][0].code
200
>>> p = http_parser.HttpResponseParserC(1, None, 2**16); p.feed_data("HTTP/1.1  200 OK\r\n\r\n".encode())[0][0][0].code
0
```

### Expected behavior

The Python and C implementations should behave in the same way, and either:
- Raise an error if there are multiple spaces between fields in the status line
- Handle multiple spaces between fields in the status line, i.e. both should behave like the Python implementation behaves
  The behavior of the Python parser is allowed: https://www.rfc-editor.org/rfc/rfc9112.html#name-status-line

### Logs/tracebacks

```python-traceback
-
```

### Python Version

```console
$ python --version
Python 3.10.4
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: /home/erik/aiohttp_bug/.venv/lib/python3.10/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/erik/aiohttp_bug/.venv/lib/python3.10/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/erik/aiohttp_bug/.venv/lib/python3.10/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Linux

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
If you want to look into it, we just use llhttp. So, first thing would ideally be to pull the latest version of llhttp and verify the issue still exists. If so, then open an issue in that project.

**Comment by emontnemery** [comment]
Thanks @Dreamsorcerer, this is indeed an issue in llhttp. I opened a PR there: https://github.com/nodejs/llhttp/pull/216

**Comment by Dreamsorcerer** [comment]
Oh, and one other thing to check is whether it happens with the lenient flag or not. We still need to enable that flag:
https://github.com/aio-libs/aiohttp/issues/5269#issuecomment-1215686989

**Comment by emontnemery** [comment]
The current behavior of llhttp is the same with and without the lenient flag set; the testcases added in https://github.com/nodejs/llhttp/pull/216 pass on both lenient and strict mode without the code changes.

**Comment by Dreamsorcerer** [comment]
Great. Would be nice to do get that flag changed though, if you'd like to make an extra contribution here.

**Comment by emontnemery** [comment]
How come you closed the issue, do you not keep issues caused by dependencies open?

**Comment by Dreamsorcerer** [comment]
Just figured there was nothing to do here. Suppose we need a PR to bump the version, so can leave it open for that..

**Comment by emontnemery** [comment]
llhttp did not accept the PR which would improve handling of extra spaces, instead this PR which errors on extra spaces looks like it will be merged soon: https://github.com/nodejs/llhttp/pull/217

**Comment by Dreamsorcerer** [comment]
Presumably resolved now.
