### ISSUE TITLE
`BaseTestServer.start_server()` changes `host` value to an IP address

### ISSUE THREAD

**Issue by ppena-LiveData** [fafhrd91/aiohttp#7166]
### Describe the bug

For some reason, `BaseTestServer.start_server()` changes `self.host` to an IP address, which is a problem if someone is expecting a host name, e.g. `localhost`. I am using [aioresponses](https://pypi.org/project/aioresponses/) in addition to [pytest-aiohttp](https://pypi.org/project/pytest-aiohttp/), the latter of which creates a `aiohttp.test_utils.TestServer`. The problem is that if I pass `http://localhost:{port}` to `aioresponses(passthrough=[...])` and then try to do a relative `client.get('/')`, it uses `127.0.0.1` instead of `localhost`, so `aioresponses` does not try to pass that through to `aiohttp` to handle it.

I see that @webknjaz made [the commit](https://github.com/aio-libs/aiohttp/commit/3d243f74e472eb57fe06759537f121094c3d3da9) that added code to `start_server()` to change `self.host` to an IP address, but the commit message doesn't say why that is being done.

### To Reproduce

This pytest reproduction of the problem is just a slight variation of the example code from https://pypi.org/project/pytest-aiohttp/:
```python
from aiohttp import web
from aioresponses import aioresponses


async def hello(request):
    return web.Response(body=b'Hello, world')


def create_app():
    app = web.Application()
    app.router.add_route('GET', '/', hello)
    return app


async def test_hello(aiohttp_client):
    host, port = 'localhost', 54321
    with aioresponses(passthrough=[f'http://{host}:{port}']):
        opts = {'host': host, 'port': port}
        client = await aiohttp_client(create_app(), server_kwargs=opts)
        resp = await client.get('/')
        assert resp.status == 200
        text = await resp.text()
        assert 'Hello, world' in text
```

### Expected behavior

Relative paths should work when using an `aiohttp_client` with a `host` value of `localhost`, even when using `aioresponses`.

### Logs/tracebacks

```python-traceback
The pytest reproduction above causes `aioresponses/core.py` to throw this exception:

aiohttp.client_exceptions.ClientConnectionError: Connection refused: GET http://127.0.0.1:54321/
```

### Python Version

```console
$ python --version
Python 3.9.13
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
...
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
...
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.8.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
```

### OS

Windows 11 but also in Linux:
```
$ uname -a
Linux hippy 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by ppena-LiveData** [comment]
NOTE: to workaround the issue, you can replace the `_root` URL of the `TestServer`, like this:
```python
client._server._root = URL(f'http://{host}:{port}')
```

**Comment by Dreamsorcerer** [comment]
Test is passing for me now, so this must have been fixed in a recent release.
