### ISSUE TITLE
(🎁) Python 3.11 support

### ISSUE THREAD

**Issue by KotlinIsland** [fafhrd91/aiohttp#7170]
### Is your feature request related to a problem?

https://github.com/aio-libs/aiohttp/pull/7169#issuecomment-1384271888

### Describe the solution you'd like

- Trove classifiers for 3.11

### Describe alternatives you've considered

N/A

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by link2xt** [comment]
For me aiohttp already works with Python 3.11. Should this issue be closed?

**Comment by Harmon758** [comment]
I don't think this is resolved, since the trove classifier is still missing in setup.cfg.
I'm also not sure if the flaky tests mentioned in https://github.com/aio-libs/aiohttp/pull/7169#issuecomment-1384271888 are fixed yet.

**Comment by a-shchupakov** [comment]
Any progress on this? Can we consider aiohttp 3.9.x to support Python 3.11? And what about Python 3.12?
@webknjaz 👀

**Comment by Dreamsorcerer** [comment]
You can just look at the test run on the latest commit to see the current status. We still have 1 test failing 100% of the time (after 10 mins of timeout) on Windows. That same test fails on Mac in about 50% of CI runs.
