### ISSUE TITLE
Add no-cache headers to static files

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#7179]
When serving static files (via StaticResource) should we add no-cache headers to avoid caching of static files?
In: https://github.com/aio-libs/aiohttp/blob/4635161ee8e7ad321cca46e01ce5bfeb1ad8bf26/aiohttp/web_urldispatcher.py#L635

Reasoning is that all our documentation says that these should only be used for development, and it can be frustrating when files are cached during development.

**Comment by jalajk24** [comment]
Can I work on this issue? I am pretty new to this

**Comment by Dreamsorcerer** [comment]
Sure, should just be able to add headers to that request (maybe checking that no existing header is already there).

**Comment by webknjaz** [comment]
@Dreamsorcerer I'd go for normal modification date based cache expiration instead of disabling the cache blindly. Even though, it's not recommended for production, some people may still use it for various reasons.
https://www.hyrumslaw.com

**Comment by Dreamsorcerer** [comment]
There's the `append_version` parameter which can be used for cache busting. But, it might be good to avoid browser caching completely. Maybe another parameter to enable these headers?

**Comment by Dreamsorcerer** [comment]
Saying that, I've just thought maybe it's better to just add a middleware that adds no-cache headers if you want to avoid browser caching completely. So, maybe it's not such a good idea. Could just mention this in the documentation somewhere instead?

**Comment by webknjaz** [comment]
A middleware sounds good.

**Comment by Dreamsorcerer** [comment]
OK, thought of a better idea. I've just added the headers when serving static files through aiohttp-devtools, which is explicitly a local dev tool:
https://github.com/aio-libs/aiohttp-devtools/pull/526

Not sure if it is worth adding a middleware to all requests from the main app as well or not..
