### ISSUE TITLE
ClientSesssion's request methods don't display acceptable parameters.

### ISSUE THREAD

**Issue by jujumilk3** [fafhrd91/aiohttp#7185]
### Describe the solution you'd like

I just created PR of it.
I created more explicit parameters for the http methods used in the ClientSession class.

### Describe alternatives you've considered

Create http methods as classes and inherit parameters from `_request` method

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
An issue pointing to a PR with no description is not helpful, we'll just look at the PR..
