### ISSUE TITLE
Multiple shutdown calls if using multiple sites

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#7204]
Maybe a question for @asvetlov, but there seems to be some odd behaviour between runners and sites in web_runner.py.

It seems that when the application is being shutdown, the calls look like:
```
BaseRunner.cleanup()
  -> BaseSite.stop()
    -> BaseRunner.shutdown()  # Application.shutdown happens here
    -> BaseRunner.server.shutdown()
  -> BaseSite.stop()  # etc. for each site
    -> BaseRunner.shutdown()
    -> BaseRunner.server.shutdown()
  -> BaseRunner._cleanup_server()  # Application.cleanup happens here
```

I'm unclear in what situation there would be multiple sites, but it seems that the application shutdown, and the server shutdown, will happen once for every site. Surely we don't want to run the shutdowns multiple times.

It also just seems odd to me that the runner shutdown calls would come from the site, when the runner is the one calling the stop method on the site. Wouldn't it make more sense for the call order to look like:
```
BaseRunner.cleanup()
  -> BaseSite.stop()
  -> BaseSite.stop()
  -> BaseRunner.shutdown()
  -> BaseRunner.server.shutdown()
  -> BaseRunner._cleanup_server()
```
Where everything is managed in the runner?

**Comment by asvetlov** [comment]
The idea was: a shutdown event per each assigned site plus the single cleanup after all served sites are down.

P.S. I am sorry for very long silence. And I very appreciate you all who kept the project moving.

**Comment by Dreamsorcerer** [comment]
No problem. I'm just wondering if the documentation should be changed or anything to make it clear what should go in a shutdown callback vs cleanup.

e.g. The documentation shows closing a database as an example for shutdown. Surely we don't want to try and close the database connection multiple times, and don't want to close it while there is still a site running?
https://docs.aiohttp.org/en/stable/web_advanced.html#signals

I guess I'm unsure what you'd put in a shutdown callback that makes sense for it to be once per site instead of once per application.

**Comment by Dreamsorcerer** [comment]
Seems like this has also come up before in #4646.

I think this is rather confusing, and we should consider changing this. All examples I've seen in the documentation (and user's actual apps) seem to assume that the shutdown is happening once per application (e.g. DB cleanups). I've never seen an example where it makes sense to be called once per site.

It also seems a little confusing to me that it is the _Application's_ shutdown being called when the _site_ is being shutdown. I feel it would be much clearer if the site had it's own shutdown method, or if the Application's methods were called something like on_site_shutdown, making it much clearer that this is a callback triggered by the site, and not part of the application's shutdown.

So, I'd propose reordering shutdown() to be once per Application (which aligns with most usage/documentation already in existence), and if per-site is still desired, we add the new callback for that (though, it'd be nice to have some examples as to why that's even desired).
