### ISSUE TITLE
RuntimeError: coroutine ignored GeneratorExit after ServerTimeoutError

### ISSUE THREAD

**Issue by pokotylo** [fafhrd91/aiohttp#7212]
### Describe the bug

`asyncio.gather()` cancels submitted futures as soon as one of them raises an exception. This works with e.g. TimeoutError, but fails to cancel requests that generate `ServerTimeoutError: Connection timeout`.

Being called inside of a process pool, these ignored exceptions may lead to a `BrokenProcessPool` exception, or lead to a hanging process pool that does not exit the `with ProcessPoolExecutor` context after all futures have been completed.

### To Reproduce

This test reproduces the `RuntimeError: coroutine ignored GeneratorExit` errors. It does not reproduce the `BrokenProcessPool` exception, or a hanging process pool on my system, which were observed in our app.

Connection timeout is simulated with `http://example.com:81/` and the normal Timeout with `https://httpstat.us/200?sleep=60000`.

<details>
<summary> The reproducing test code</summary>

``` python
import asyncio
import logging
import sys
import unittest
from concurrent.futures import ProcessPoolExecutor
from time import sleep

import aiohttp
from aiohttp import ServerTimeoutError
from asyncio import TimeoutError

logger = logging.getLogger(__name__)

timeout = aiohttp.ClientTimeout(total=5, connect=5)

requests_number = 20

async def async_request(file_url: str):
    async with aiohttp.ClientSession(timeout=timeout) as session:
        async with session.get(file_url) as response:
            print(response, file=sys.stderr)


class TimeoutsTest(unittest.IsolatedAsyncioTestCase):
    # both calls outside the process pool work fine, there are no ignored exceptions

    async def test_timeout(self):
        url = "https://httpstat.us/200?sleep=60000"
        with self.assertRaises(TimeoutError):
            await asyncio.gather(*[async_request(url) for _ in range(requests_number)])

        # otherwise the exceptions occur during test shutdown
        sleep(1)

    async def test_connection_timeout(self):
        url = "http://example.com:81/"
        with self.assertRaises(ServerTimeoutError):
            await asyncio.gather(*[async_request(url) for _ in range(requests_number)])

        # otherwise the exceptions occur during test shutdown
        sleep(1)


max_workers = 4
tasks_number = max_workers * 4


def run_in_process_pool(file_url):
    io_loop = asyncio.get_event_loop()
    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures = [io_loop.run_in_executor(executor, process_task, file_url) for _ in range(tasks_number)]

        for future in asyncio.as_completed(futures):
            response = asyncio.get_event_loop().run_until_complete(future)
            yield response


def process_task(file_url):
    try:
        # a new loop in each process
        asyncio.set_event_loop(asyncio.new_event_loop())

        return asyncio.get_event_loop().run_until_complete(asyncio.gather(*[async_request(file_url) for _ in range(requests_number)]))
    except Exception as exception:
        return exception


class TimeoutsProcessPoolTest(unittest.TestCase):
    # when running the connection_timeout test, it generates the output seen below

    def test_timeout_process_pool(self):
        url = "https://httpstat.us/200?sleep=60000"
        results = list(run_in_process_pool(url))

        for result in results:
            self.assertIsInstance(result, TimeoutError)
        self.assertEqual(max_workers * 4, len(results))

    def test_connection_timeout_process_pool(self):
        url = "http://example.com:81/"
        results = list(run_in_process_pool(url))

        for result in results:
            self.assertIsInstance(result, ServerTimeoutError)
        self.assertEqual(max_workers * 4, len(results))


if __name__ == "__main__":
    unittest.main()

```
</details>

### Expected behavior

It is expected that all futures get cancelled.

### Logs/tracebacks

The tests pass. All outputs happen outside the user code and cannot be handled:

<details>
<summary> The outputs of `test_connection_timeout_process_pool`</summary>

```python-traceback
Traceback (most recent call last):
  File "/test_timepouts.py", line 20, in async_request
    async with session.get(file_url) as response:
  File "/venv-3.9/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/venv-3.9/lib/python3.9/site-packages/aiohttp/client.py", line 540, in _request
    raise ServerTimeoutError(
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host http://example.com:81/
Task exception was never retrieved
future: <Task finished name='Task-97' coro=<async_request() done, defined at //test_timepouts.py:18> exception=ServerTimeoutError('Connection timeout to host http://example.com:81/')>
Traceback (most recent call last):
  File "/venv-3.9/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/venv-3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/venv-3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/venv-3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/venv-3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
asyncio.exceptions.CancelledError
```

```python-traceback
Traceback (most recent call last):
  File "/test_timepouts.py", line 20, in async_request
    async with session.get(file_url) as response:
  File "/venv-3.9/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/venv-3.9/lib/python3.9/site-packages/aiohttp/client.py", line 540, in _request
    raise ServerTimeoutError(
aiohttp.client_exceptions.ServerTimeoutError: Connection timeout to host http://example.com:81/
Exception ignored in: <coroutine object async_request at 0x1184c2340>
RuntimeError: coroutine ignored GeneratorExit
```
</details>

### Python Version

```console
$ python --version
3.9.16
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.4
```

### multidict Version

```console
$ python -m pip show multidict
6.0.4
```

### yarl Version

```console
$ python -m pip show yarl
1.8.2
```

### OS

The issue was reproduced and the test outputs have been generated under macOS 12.6.2.

The original issue with the hanging process pool happened in kubernetes with the `python:3.9-slim` docker image.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> ### Expected behavior
> 
> It is expected that all futures get cancelled.

No, I'm afraid it is not:

> If return_exceptions is False (default), the first raised exception is immediately propagated to the task that awaits on gather(). Other awaitables in the aws sequence **won’t be cancelled** and will continue to run.
https://docs.python.org/3/library/asyncio-task.html#asyncio.gather

I think if you are hitting the TimeoutError, then you have the same timeout in all processes, so they happen to all fail at the same time. That works by coincidence, not by design.

Use `return_exceptions=True` to run all tasks to completion, or cancel the tasks yourself if you want them to be cancelled. Maybe something like:
```
tasks = [asyncio.create_task(...) for t in ...]
try:
    await asyncio.gather(*tasks)
except Exception:
    for t in tasks:
        t.cancel()
    await asyncio.gather(*tasks)
    raise
```

**Comment by pokotylo** [comment]
I am probably not correct in the _Expected behavior_ section, I was misled with the `gather` docstring that is less clear than the docs.

Still I do not understand the difference in the behavior for 'Connection timeout' and simple 'Timeout', given that in both cases concurrent coroutines will fail approximately simultaneously. I do not observe `Exception ignored in: <coroutine object async_request>` and `RuntimeError: coroutine ignored GeneratorExit` for simple Timeouts. It is also unclear where `CancelledError` comes from, if gather does not cancel coroutines.

The worst thing is that these uncontrolled failures may lead to a `BrokenProcessPool` exception, or to a hanging process pool.

Also thanks for the hint with using `return_exceptions=True` to run all tasks to completion - we used this workaround and it prevented our issues with the process pool.

**Comment by Dreamsorcerer** [comment]
Ah, I think the `Timeout` you are referring to subclasses `CancelledError`, so this part might be relevant:

> If any Task or Future from the aws sequence is cancelled, it is treated as if it raised [CancelledError](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError) – the gather() call is not cancelled in this case.

**Comment by hitrust** [comment]
After encounter  'Server disconnected' error, the same issue also occurs, like below

Exception ignored in: <coroutine object test_img at 0x00000255AE584C40>
RuntimeError: coroutine ignored GeneratorExit
Exception ignored in: <coroutine object test_img at 0x00000255AE584BC0>
RuntimeError: coroutine ignored GeneratorExit
Exception ignored in: <coroutine object test_img at 0x00000255AE584B40>
RuntimeError: coroutine ignored GeneratorExit
Exception ignored in: <coroutine object test_img at 0x00000255AE584AC0>
RuntimeError: coroutine ignored GeneratorExit
Exception ignored in: <coroutine object test_img at 0x00000255AE584A40>
RuntimeError: coroutine ignored GeneratorExit
Exception ignored in: <coroutine object test_img at 0x00000255AE5849C0>
RuntimeError: coroutine ignored GeneratorExit
...
Exception ignored in: <coroutine object test_img at 0x00000255AE584940>
RuntimeError: coroutine ignored GeneratorExit

Name: aiohttp
Version: 3.9.3
Python 3.9.13

use aiohttp in asyncio gather tasks.

When I tried to remove 'proxy=proxy' argument from 'session.get()', the code just throw  'Server disconnected' error, the other requests are just fine.
