### ISSUE TITLE
Use ada url parser

### ISSUE THREAD

**Issue by v1gnesh** [fafhrd91/aiohttp#7217]
Firstly, thank you to everyone who has contributed to this project over the years.
The impact your contributions have on others' productivity & work in general is invaluable.

In continuation of the work done in https://github.com/aio-libs/aiohttp/pull/1626, https://github.com/aio-libs/aiohttp/pull/5364, and https://github.com/aio-libs/aiohttp/pull/6144... I wanted to ask if [ada](https://github.com/ada-url/ada) could be used for URL parsing.

Nodejs will be integrating it shortly - https://github.com/nodejs/node/pull/46410 & https://github.com/nodejs/node/commit/3ee97ee0ead30e9b831fccc7edba8e803efb4a57.

**Comment by Dreamsorcerer** [comment]
Well, if it offers a benefit, and someone wants to add it, then seems reasonable.

I'm not sure exactly where the URL parsing happens, but I suspect it's through yarl, so the change will need to happen in that project, rather than aiohttp.

**Comment by v1gnesh** [comment]
Thanks Sam, I know nothing about C/C++  😬 .
Just thought I'd surface this here in case anyone is interested.
I'll "move" this issue to yarl, and close this one for now.
