### ISSUE TITLE
aiohttp WebSocket cannot upgrade

### ISSUE THREAD

**Issue by redradist** [fafhrd91/aiohttp#7224]
### Describe the bug

During the testing the following example from README.md page:
```python
from aiohttp import web

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(text=text)

async def wshandle(request):
    ws = web.WebSocketResponse()
    await ws.prepare(request)

    async for msg in ws:
        if msg.type == web.WSMsgType.text:
            await ws.send_str("Hello, {}".format(msg.data))
        elif msg.type == web.WSMsgType.binary:
            await ws.send_bytes(msg.data)
        elif msg.type == web.WSMsgType.close:
            break

    return ws


app = web.Application()
app.add_routes([web.get('/', handle),
                web.get('/echo', wshandle),
                web.get('/{name}', handle)])

if __name__ == '__main__':
    web.run_app(app)
```

using WebSocket I got the following error:
```console
No WebSocket UPGRADE hdr: None
 Can "Upgrade" only to "WebSocket".
```

### To Reproduce

1. Run sample for WebSocker from README.md page
2. Open in browser ws://0.0.0.0:8080/ws/echo or http://0.0.0.0:8080/ws/echo

### Expected behavior

Return echo message

### Logs/tracebacks

```python-traceback
No WebSocket UPGRADE hdr: None
 Can "Upgrade" only to "WebSocket".
```

### Python Version

```console
$ python --version
3.11
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.4
```

### multidict Version

```console
$ python -m pip show multidict
6.0.4
```

### yarl Version

```console
$ python -m pip show yarl
1.8.2
```

### OS

macOS

### Related component

Server

### Additional context

Firefox 110.0

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> Open in browser ws://0.0.0.0:8080/ws/echo or http://0.0.0.0:8080/ws/echo

What do you mean by open in browser? They are Websocket endpoints, so you'd need to write some JS to open a websocket, right?

**Comment by redradist** [comment]
> > Open in browser ws://0.0.0.0:8080/ws/echo or http://0.0.0.0:8080/ws/echo
> 
> What do you mean by open in browser? They are Websocket endpoints, so you'd need to write some JS to open a websocket, right?

Oh ... looks like I get the issue, it is just not possible to upgrade to WebSocket using browser ...
Closing the issue
