### ISSUE TITLE
Stdout buffered when not a tty

### ISSUE THREAD

**Issue by CGamesPlay** [fafhrd91/aiohttp#7290]
### Describe the bug

When running an aiohttp.web.Server, if the process is piped to something like cat, stdout is buffered permanently until the server shuts down. This prevents using print statements to debug if you are using a process manager like honcho, or a log formatter, etc. When using aiohttp-devtools, the problem is even more confusing, because your endpoint will crash and return with no prints, then after saving the file adev will restart the server, causing the buffered prints to flush, thereby *appearing* to come from your next request.

### To Reproduce

1. Create `test.py` using the example server from https://docs.aiohttp.org/en/stable/web_quickstart.html
2. Run the program directly.
3. Run the program with stdout detached from a tty.

### Expected behavior

In both cases, the server should output "======== Running on http://0.0.0.0:8080 ========". However, in the second case, no output is received, even after waiting. This is because aiohttp is buffering the stdout until after the server shuts down. When ^C is pressed, aiohttp begins to flush the buffer, but cat has already quit at that point, causing the program to crash with a BrokenPipe. A similar problem could be seen with `python3 test.py > test.txt`, where `test.txt` would remain empty until after ^C is pressed.

### Logs/tracebacks

```python-traceback
$ python3 test.py
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
^C⏎

$ python3 test.py | cat
^CException ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

### Python Version

```console
$ python --version
Python 3.9.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.4
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: /.../lib/python3.9/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by: aiohttp-devtools
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /.../lib/python3.9/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /.../lib/python3.9/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

macOS

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I don't think this is something we should be changing...

If you're running python in a situation where buffering doesn't work, then you should be running it unbuffered (`python -u`).

**Comment by Dreamsorcerer** [comment]
If you expect it to do that automatically base on the presence of a tty, that suggestion should be made upstream to cpython, given that any Python application will have the same issue.
