### ISSUE TITLE
tarfile stream write failes with the async write of the StreamResponse

### ISSUE THREAD

**Issue by gitartpiano** [fafhrd91/aiohttp#7301]
### Is your feature request related to a problem?

```python
                response = web.StreamResponse(
                    status=200,
                    reason="OK",
                    headers={
                        "Content-Disposition": f"attachment;filename={compressed_file_name}"
                    },
                )
                await response.prepare(request)
                buff = BytesIO()
                # https://docs.python.org/3/library/tarfile.html#tarfile.open
                tar = tarfile.open(compressed_file_name, "w|gz", buff)
                tar.add(output_path, os.path.basename(output_path))
                tar.close()
                await response.write(buff.getvalue())
                await response.write_eof()
                return response
```
This solution works, but it reads compresses the file/directory in memory.
Preferred solution is on-the-fly compression; where response stream is written while file/directory is being compressed.

### Describe the solution you'd like

```python
                response = web.StreamResponse(
                    status=200,
                    reason="OK",
                    headers={
                        "Content-Disposition": f"attachment;filename={compressed_file_name}"
                    },
                )
                await response.prepare(request)
                tar = tarfile.open(compressed_file_name, "w|gz", response)
                tar.add(output_path, os.path.basename(output_path))
                tar.close()
                await response.write_eof()
                return response
```
But this solution does not work, the response stream is not written and this error is printed:
```
/usr/lib/python3.8/tarfile.py:460: RuntimeWarning: coroutine 'StreamResponse.write' was never awaited
  self.fileobj.write(self.buf)
```

### Describe alternatives you've considered

Cannot find any alternative. Please recommend.

### Related component

Server

### Additional context

StreamResponse

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I think you'd need to figure out some way to process tarfiles with asyncio. I don't see any libraries that support this in a quick search, but it's going to be rather difficult otherwise. tarfile is a sync API, while aiohttp is an async one.

While you could pass a custom file-like object to `tarfile.open()`, it would be using a sync API, so it'd be difficult to make the needed `await response.write()` call.

I'll close this, as it's not really anything to do with aiohttp, but do post an update if you do find a working library or other solution.

**Comment by gitartpiano** [comment]
Figured out a workaround, probably not the best solution:
```python
            compressed_file_name = os.path.basename(output_path) + "." + compress
            if compress in ("targz", "tar.gz", "tgz"):
                response = web.StreamResponse(
                    status=200,
                    reason="OK",
                    headers={
                        "Content-Disposition": f"attachment;filename={compressed_file_name}"
                    },
                )
                await response.prepare(request)
                buff = MyBytesIO()
                tar_process = threading.Thread(
                    target=buff.targz, args=(compressed_file_name, output_path)
                )
                tar_process.start()
                while tar_process.is_alive():
                    await response.write(buff.getvalue())
                await response.write(buff.getvalue())  # one more read for safety?
                await response.write_eof()
                return response
```
where
```python
class MyBytesIO(BytesIO):
    def __init__(self):
        self.lock = Lock()

    def write(self, data):
        with self.lock:
            super().write(data)

    def getvalue(self):
        with self.lock:
            value = super().getvalue()
            super().truncate(0)
            super().seek(0)
            return value

    def targz(self, compressed_file_name, output_path):
        # https://docs.python.org/3/library/tarfile.html#tarfile.open
        tar = tarfile.open(compressed_file_name, "w|gz", self)
        tar.add(output_path, os.path.basename(output_path))
        tar.close()
```
@Dreamsorcerer would you mind reviewing it?

**Comment by Dreamsorcerer** [comment]
The sticky point is that `buff.getvalue()` can block the event loop while waiting for lock, thus freezing your application.
Maybe safer to do `await asyncio.to_thread(buff.getvalue)`.

I'm also not too familiar with locks when it comes to mixing threading and asyncio (my guess is that should be a threading Lock, rather than an asyncio one, but not 100% sure (the example doesn't show which is used)).

**Comment by gitartpiano** [comment]
> my guess is that should be a threading Lock, rather than an asyncio one, but not 100% sure

Yes it is threading lock in my implementation:
```
from threading import Lock
```

> buff.getvalue() can block the event loop while waiting for lock, thus freezing your application

The solution appears to work, but so far I have tested it only by on-the-fly packaging a small directory.

I will update this thread after performance testing this with a large data directory and with a large file. With those test cases yes, it is possible that `getvalue()` would take too long to return (because write call is writing too large of a chunk), I will add measuring and logging how much time and how much data each `getvalue()` call takes for those performance tests.

> Maybe safer to do await asyncio.to_thread(buff.getvalue)

If you could provide a more complete solution, I would not mind testing it (also comparing its performance to the original solution).

**Comment by Dreamsorcerer** [comment]
> If you could provide a more complete solution, I would not mind testing it (also comparing its performance to the original solution).

I meant literally:
```diff
-                   await response.write(buff.getvalue())
+                   await response.write(await asyncio.to_thread(buff.getvalue))
```
