### ISSUE TITLE
It seems like the domain of aiohttp was expired

### ISSUE THREAD

**Issue by hr3iobin** [fafhrd91/aiohttp#7307]
### Is your feature request related to a problem?

The domain of aiohttp project was expired, even the [readthedoc's link](https://aiohttp.readthedocs.io) is redirect to offical doc link, but it cannot visit now.

### Describe the solution you'd like

Offical domain aiohttp.org was expired, renewal it please.

### Describe alternatives you've considered

Renewal it.

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
It looks like both aiohttp.org and aio-libs.org might've been squatted. Only Andrew has (had?) access to them, I don't.

**Comment by webknjaz** [comment]
Which is why I'm assigning this to @asvetlov

**Comment by Dreamsorcerer** [comment]
Appears to be resolved already?

**Comment by Dreamsorcerer** [comment]
Worth noting that on namecheap, there is a 'Sharing & Transfer' tab under a domain name. If @asvetlov wants to add either of us there, we could help with domain management (I have the same username on there).

**Comment by webknjaz** [comment]
Looks like it. Closing.
