### ISSUE TITLE
websocket: message.json() fails with a TypeError when the message exceeds the size limit

### ISSUE THREAD

**Issue by justvanrossum** [fafhrd91/aiohttp#7313]
### Describe the bug

When a websocket message exceeds the size limit, calling message.json() raises a TypeError instead of an informative exception

### To Reproduce

Send a large websocket message to an aiohttp server.

In the handler, calling message.json() raises TypeError:

    TypeError: the JSON object must be str, bytes or bytearray, not WebSocketError

`message.data` is set to a WebSocketError instance:

    aiohttp.http_websocket.WebSocketError: Message size 29818 exceeds limit 8192

(I lowered the limit to more easily trigger the problem)

### Expected behavior

I would expect calling `message.json()` to raise the WebSocketError.

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "/Users/just/code/git/BlackFoundry/fontra/src/fontra/core/remote.py", line 47, in _handleConnection
    message = message.json()
              ^^^^^^^^^^^^^^
  File "/Users/just/code/git/BlackFoundry/fontra/venv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 98, in json
    return loads(self.data)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not WebSocketError
```

### Python Version

```console
Python 3.11.2
```

### aiohttp Version

```console
Name: aiohttp
Version: 3.8.4
```

### multidict Version

```console
Name: multidict
Version: 6.0.4
```

### yarl Version

```console
Name: yarl
Version: 1.8.2
```

### OS

macOS 10.15

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
OK, I've been working through a PR to try and make this more type safe.

2 options we can do. First is to raise the exception from `.json()`, but I'm not sure how much sense this makes, and it would still fail on other message types (e.g. CLOSE has an int, which would still produce a TypeError). This would not affect type safety.

Second is to have `.json()` only on TEXT and BINARY messages. This means the code would need to do something like `if msg.type in (WSMsgType.TEXT, WSMsgType.BINARY)`. But, this could be checked with mypy etc. If you don't check the type it'll complain that there's no `.json()` method.

**Comment by Dreamsorcerer** [comment]
Note that you can implement the second approach in your code now. My changes would just make it a requirement and flag up any issues when checked with mypy.

**Comment by justvanrossum** [comment]
I think I am puzzled (as a newbie aiohttp user) why the error is delivered as a message instead of a raised exception.

**Comment by Dreamsorcerer** [comment]
I'm not too sure what the reasoning is for this, but you'll note from the websockets example that the expected behaviour is to check for WSMsgType.ERROR and then break (because the connection will be closed on an error):
https://docs.aiohttp.org/en/stable/client_quickstart.html#websockets

The data will only be an exception if the type is ERROR.

Maybe @asvetlov can provide some reasoning why we don't raise the exception.

**Comment by justvanrossum** [comment]
> The data will only be an exception if the type is ERROR.

Thanks, I've adjusted my code to check for `WSMsgType.ERROR`.
