### ISSUE TITLE
Python 3.10 - DeprecationWarning on example "Run a Basic Low-Level Server"

### ISSUE THREAD

**Issue by schuberttobias** [fafhrd91/aiohttp#7314]
### Describe the bug

In Python 3.10 you'll get a DeprecationWarning If you run the example [Run a Basic Low-Level Server](https://docs.aiohttp.org/en/latest/web_lowlevel.html).

### To Reproduce

Run example code from documentation: 

https://docs.aiohttp.org/en/stable/web_lowlevel.html#run-a-basic-low-level-server

```python
import asyncio
from aiohttp import web


async def handler(request):
    return web.Response(text="OK")


async def main():
    server = web.Server(handler)
    runner = web.ServerRunner(server)
    await runner.setup()
    site = web.TCPSite(runner, 'localhost', 8080)
    await site.start()

    print("======= Serving on http://127.0.0.1:8080/ ======")

    # pause here for very long time by serving HTTP requests and
    # waiting for keyboard interruption
    await asyncio.sleep(100*3600)


loop = asyncio.get_event_loop()

try:
    loop.run_until_complete(main())
except KeyboardInterrupt:
    pass
loop.close()
```

### Expected behavior

No DeprecationWarnings.

### Logs/tracebacks

```python-traceback
(aiohttp-test) root@e6dabeed3c80:~/aiohttp-test# python3 test.py
/root/aiohttp-test/test.py:23: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
======= Serving on http://127.0.0.1:8080/ ======
```

### Python Version

```console
3.10.6
```

### aiohttp Version

```console
3.8.4
```

### multidict Version

```console
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /root/.local/share/virtualenvs/aiohttp-test-WmGPGqKN/lib/python3.10/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
Name: yarl
Version: 1.9.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /root/.local/share/virtualenvs/aiohttp-test-WmGPGqKN/lib/python3.10/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Ubuntu 22.04.2 LTS (GNU/Linux 4.14.314-237.533.amzn2.x86_64 x86_64)

### Related component

Server

### Additional context

Related to #6752 and possibly to #6757 #5572

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Feel free to make a PR. That whole bottom section can just be replaced with `asyncio.run()`.

**Comment by Dreamsorcerer** [comment]
Looks like there's a few other cases of `run_until_complete` in the docs that could also be updated.

**Comment by schuberttobias** [comment]
@Dreamsorcerer Thank you for your comments. I'm sorry, but I am lacking time to set up a PR to solve this.
