### ISSUE TITLE
Option to make the `save()` and `load()` methods of CookieJar update instead of overwrite cookies

### ISSUE THREAD

**Issue by User087** [fafhrd91/aiohttp#7324]
### Describe the solution you'd like

It seems the current behaviour of `session.cookie_jar.load()` is to overwrite the current cookies of `session` instead of just updating the present cookies wherever the domain is the same and they're just expired etc. and appending the rest of the loaded cookies wherever the domains are new. I suggest adding an option to make it behave in the latter manner.

I suggest something similar for `session.cookie_jar.save()`, to only overwrite already-written cookies in the file when the cookies of `session` are more up-to-date, and otherwise append new cookies from different domains etc.

### Describe alternatives you've considered

For `load()`, probably load the pickled cookies into a separate variable and then have to use whatever the relevant methods are to update `session._cookies` instead of overwriting it, which defeats the point of having `load()` as a convenience method. Similar issue with `save()`.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
load/save are for persisting the cookie jar on disk. To restore a cookie jar from disk that updates an existing cookiejar, seems like an extreme edge case. I'd expect a typical application using this functionality to restore the cookiejar on startup (it'd probably even make sense for load() to be a classmethod that returns a new instance..). What is your use case for this?

I'm even less clear on you suggestion for save(). The function uses pickle to dump the cookies, so I'm unclear how you propose updating the file, or what difference it would make to a user...
