### ISSUE TITLE
server improperly parses cookies containing raw json

### ISSUE THREAD

**Issue by PhracturedBlue** [fafhrd91/aiohttp#7330]
### Describe the bug

Some other application in my domain is setting a domain-wide cookie that is raw json.  My application is also setting a cookie. 
 However, if my cooke is set after the domain-wide cookie, then request.cookie is missing my cookie.

### To Reproduce

server.py:
```
from aiohttp import web

async def handler(request):
    print(f"Raw: {request.raw_headers}")
    print(f"Cookies: {request.cookies}")

app = web.Application()
app.add_routes([web.get('/', handler)])
web.run_app(app)
```

Then:
curl -k -H 'Cookie:test={"key": 1}; MY_COOKIE="gAAA"' http://localhost:8080/
Displays:
Raw: ((b'User-Agent', b'curl/7.29.0'), (b'Host', b'localhost:8080'), (b'Accept', b'*/*'), (b'Cookie', b'test={"key": 1}; MY_COOKIE="gAAA"'))
**Cookies: {}**

and 
curl -k -H 'Cookie:MY_COOKIE="gAAA"; test={"key": 1}' http://localhost:8080/
Displays:
Raw: ((b'User-Agent', b'curl/7.29.0'), (b'Host', b'localhost:8080'), (b'Accept', b'*/*'), (b'Cookie', b'MY_COOKIE="gAAA"; test={"key": 1}'))
**Cookies: {'MY_COOKIE': 'gAAA'}**

### Expected behavior

I expect 'MY_COOKIE' to be in the request.cookies dictionary

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
$ python --version
Python 3.11.0
```

### aiohttp Version

```console
$ python -m pip show aiohttp
.venv/bin/python3 -m pip show aiohttp
Name: aiohttp
Version: 3.8.4
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.4
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.2
```

### OS

Centos Linux 7.9

### Related component

Server

### Additional context

This was originally discoverd using aiohttp_session, where all users have the session key in their browser, but only some could authenticate with the server.  this was traced to the order that the cookies were being sent, and eventually to discovering the 'bad' cookie causing corruption

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by PhracturedBlue** [comment]
Having looked at the code, this is apparently the behavior of http.cookies.SimpleCookie.  It is not clear to me whether this can be easily resolved in aiohttp

**Comment by Dreamsorcerer** [comment]
The behaviour is correct, `"` is not a valid character in a cookie-value:
https://httpwg.org/specs/rfc6265.html#sane-set-cookie-syntax

It should be encoded correctly:
> To maximize compatibility with user agents, servers that wish to store arbitrary data in a cookie-value SHOULD encode that data, for example, using Base64 [[RFC4648]](https://httpwg.org/specs/rfc6265.html#RFC4648).

It does seem to work if I do `Cookie:test="{\"key\": 1}"; MY="gAAA"`, but as far as I can see, that is still an invalid cookie value, it should be base64 encoded/decoded.

**Comment by Dreamsorcerer** [comment]
Though it might be better behaviour to throw away the invalid value and continue parsing the remaining cookies (though the spec doesn't seem to suggest any particular behaviour in this case). If that's handled by http.cookies though, you'll need to open an issue with cpython.

**Comment by PhracturedBlue** [comment]
I understand tat the cookie is invalid.  But I have no control over the bad cookie that the browser sent (I didn't set it).  The end result is that while I can set a 'good' cookie in the browser, I can't read it back from aiohttp  due to something I have no control over (some other site setting a broken cookie on the same domain)

But as you say, the issue really seems to be with the SimpleCookie behavior.  I've just monkey-patched it, and will be on my way.

**Comment by PhracturedBlue** [comment]
For completion, there is already an open cpython ticket on this issue:
https://bugs.python.org/issue41945
(now https://github.com/python/cpython/issues/86111)

**Comment by Dreamsorcerer** [comment]
Relevant code appears to be: https://github.com/python/cpython/blob/main/Lib/http/cookies.py#L553-L556

Probably not too difficult to fix it to parse other, valid cookies, if you'd like to give it a go.
