### ISSUE TITLE
Unrecoverable ServerTimeoutError within web.Request context

### ISSUE THREAD

**Issue by dorinclisu** [fafhrd91/aiohttp#7331]
### Describe the bug

I am using the client + server as a streaming proxy server that modifies the url of the requests according to some custom logic. However, the url modification logic is most likely not relevant here.

What happens is that after a while  (days, or sometimes months) in production the ClientSession stops working and throws ServerTimeoutError exception on `.get()` method. This keeps happening even after the production load is taken away, so the only way to recover is to restart the whole python process.

This is most likely a **client** bug but it might be relevant that the client request happens within a web server request. I don't know.
It might be related to https://github.com/aio-libs/aiohttp/issues/4923
The CPU and MEM utilizations have been checked and they are relatively low.

### To Reproduce

I was unable to reproduce the problem yet in the dev environment, but here's a minimal stripped down version of the proxy server. Perhaps you see something wrong or have suggestions on how to get more debug info.
```Python
import asyncio
import logging

import aiohttp
from aiohttp import web



origin_url         = "https://google.com"
origin_timeout     = 5
content_chunk_size = 2**16
server_port        = 8080


app = web.Application()
routes = web.RouteTableDef()

origin: aiohttp.ClientSession


async def on_startup(app: web.Application):
    global origin
    timeout = aiohttp.ClientTimeout(connect=origin_timeout, total=origin_timeout*2)
    origin = await aiohttp.ClientSession(timeout=timeout).__aenter__()

async def on_shutdown(app: web.Application):
    await origin.__aexit__(None, None, None)
    await asyncio.sleep(0.25)  # workaround to enable graceful shutdown of TLS connection - https://docs.aiohttp.org/en/stable/client_advanced.html#graceful-shutdown


app.on_startup.append(on_startup)
app.on_shutdown.append(on_shutdown)


@routes.get('/')
async def proxy(r: web.Request) -> web.StreamResponse:
    try:
        logging.debug(f'Origin request to {origin_url}')
        resp = await origin.get(origin_url, headers=r.headers)

    except aiohttp.ServerTimeoutError as e:
        logging.error(f'Handled exception: {repr(e)}')
        return web.Response(status=504, text='Timeout waiting response from origin')

    except Exception as e:
        logging.error(f'Handled exception: {repr(e)}')
        return web.Response(status=502, text='Error getting response from origin')

    response = web.StreamResponse(status=resp.status, headers=resp.headers)
    await response.prepare(r)

    async for chunk in resp.content.iter_chunked(content_chunk_size):
        await response.write(chunk)

    return response


app.add_routes(routes)


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    web.run_app(app, port=server_port)

```

### Expected behavior

No issue, or at least the ClientSession automatically repairs the connection pool.

### Logs/tracebacks

As I said the issue is not reproducible yet and I can't show the production logs, but we can simulate the error path by modifying the `origin_url` variable to an invalid port such as 1234.
```python-traceback
DEBUG:asyncio:Using selector: EpollSelector
======== Running on http://0.0.0.0:8080 ========
(Press CTRL+C to quit)
DEBUG:root:Origin request to https://google.com:1234
ERROR:root:Handled exception: ServerTimeoutError('Connection timeout to host https://google.com:1234')
INFO:aiohttp.access:127.0.0.1 [28/Jun/2023:16:05:03 +0000] "GET / HTTP/1.1" 504 200 "-" "curl/7.68.0"
```

### Python Version

```console
$ python --version
3.11.3

but it also happened on 3.9
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.4
```

### multidict Version

```console
$ python -m pip show multidict
6.0.4
```

### yarl Version

```console
$ python -m pip show yarl
1.9.2
```

### OS

Docker image python:3.11-slim

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I think there are some open issues about the session possibly reusing a connection that is closed, it might be the same issue.

I'm not sure this will make a difference or not, but I'd suggest using `async with` when using `session.get()` as per the examples in the documentation.

I could also make some unrelated suggestions, such as using cleanup_ctx and avoiding globals like our examples/demos.

**Comment by dorinclisu** [comment]
Thanks, using `async with` seems to have solved the issue, and I think I found out why. 

The trigger of the bug is most likely when the client response is not fully read, and also not released. This is bound to happen when using `await session.get()` and then iterating `resp.content.iter_chunked()` while sending a streaming response, as some server users will invariably close their connection (timeout or whatever), raising ConnectionResetError in `await response.write(chunk)`. When using the session context manager, the response is guaranteed to be released even if an exception occurs.

This is the updated code:
```Python
async def proxy(r: web.Request) -> web.StreamResponse:
    try:
        logging.debug(f'Origin request to {origin_url}')
        async with origin.get(origin_url, headers=r.headers) as resp:
            response = web.StreamResponse(status=resp.status, headers=resp.headers)
            await response.prepare(r)

            async for chunk in resp.content.iter_chunked(content_chunk_size):
                await response.write(chunk)

    except aiohttp.ServerTimeoutError as e:
        logging.error(f'Handled exception: {repr(e)}')
        return web.Response(status=504, text='Timeout waiting response from origin')

    except aiohttp.ClientError as e:
        logging.error(f'Handled exception: {repr(e)}')
        return web.Response(status=502, text='Error getting response from origin')

    return response
```

An interesting aspect is that last year (didn't keep track of the version) the crash was happening every few months. After updating to 3.8.4, the crash started to happen every few **hours** (which in a way was good for a sense of replicability). The reason I think has something to do with the aiohttp server behavior: https://docs.aiohttp.org/en/latest/web_advanced.html#aiohttp-web-peer-disconnection

More precisely, in the previous version, handler cancellation was the implicit behavior, meaning that the coroutines were canceled before `response.write(chunk)` would raise an exception, maintaining a clean client session. Now with 3.8.4 there is no cancellation, implicit or explicit.  Waiting for the release of 3.9 to enable cancellation again.

**Comment by dorinclisu** [comment]
> I could also make some unrelated suggestions, such as using cleanup_ctx and avoiding globals like our examples/demos.

Avoiding global variable is trivial by just doing `app['origin'] = ...` instead of `global origin` but it would make absolutely no difference to the behavior. 

Now, what I find somewhat hacky is having to do `await aiohttp.ClientSession().__aenter__()` and `await .__aexit__()` at startup and shutdown respectively. I read the documentation about `cleanup_ctx` but I don't see how it would be much better:
```python
async def client(app: web.Application):
    origin = await aiohttp.ClientSession().__aenter__()
    app['origin'] = origin
    yield
    await origin.__aexit__(None, None, None)
    await asyncio.sleep(0.25)

app.cleanup_ctx.append(client)
```

**Comment by Dreamsorcerer** [comment]
> > I could also make some unrelated suggestions, such as using cleanup_ctx and avoiding globals like our examples/demos.
> 
> Avoiding global variable is trivial by just doing `app['origin'] = ...` instead of `global origin` but it would make absolutely no difference to the behavior.

Yes, not related. But, we generally encourage avoiding non-constant globals in our demos, which includes `app`:
https://github.com/aio-libs/aiohttp-demos/blob/master/demos/polls/aiohttpdemo_polls/main.py#L46

> I read the documentation about `cleanup_ctx` but I don't see how it would be much better:

Just do:
```python
async def client(app: web.Application):
    async with aiohttp.ClientSession() as client
        app['origin'] = client
        yield
    await asyncio.sleep(0.25)

app.cleanup_ctx.append(client)
```
