### ISSUE TITLE
Status 302 is displayed instead of status 404

### ISSUE THREAD

**Issue by iyamk** [fafhrd91/aiohttp#7354]
### Describe the bug

I just want to make it show status 404. Why here everything so complicated 

### To Reproduce

Run code:
```
from aiohttp import web

@routes.get('/404')
async def not_found(request):
    return web.Response(text='404')

@routes.get('/{file}')
async def file(request):
    return web.HTTPFound('/404')

app = web.Application()
app.add_routes(routes)
```

### Expected behavior

It should return a 404 status. But instead, there is a required location parameter that redirects to /404 with a 302 code

### Logs/tracebacks

```python-traceback
no
```

### Python Version

```console
$ Python 3.11.3
```

### aiohttp Version

```console
Python 3.11.3
[user@linux prbot]$ python -m pip show aiohttp
Name: aiohttp
Version: 3.8.4
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /home/user/.local/lib/python3.11/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by: aiogram
```

### multidict Version

```console
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/user/.local/lib/python3.11/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
Name: yarl
Version: 1.9.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /home/user/.local/lib/python3.11/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Arch linux

### Related component

Server

### Additional context

Can't you do it just like in php? It is very difficult to understand the documentation and in general these middlewares that are redundant for this

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
What should return a 404?

You have an endpoint which returns HTTPFound (a 302). And an endpoint which just returns the message '404' with the default status of 200...

**Comment by Dreamsorcerer** [comment]
If you want to do an explicit 404 for some reason, then your endpoint should do `raise web.HTTPNotFound()`.
