### ISSUE TITLE
Authentication header is removed with a legal redirect (port in host)

### ISSUE THREAD

**Issue by Alex-Izquierdo** [fafhrd91/aiohttp#7381]
### Describe the bug

According to the documentation:
```
Authorization header will be removed if you get redirected to a different host or protocol.
```
But I've found a case where the header was removed without meet the criteria. 

### To Reproduce

Perform a GET request (with follow_redirects enabled) against an HTTP server that returns a 301 of the following form:

https://example.com:443/resource -> https://example.com/resource/

In this case, just the trailing slash was added and the port was removed. The library is considering the port as part of the host so it removes the Authentication header. 

### Expected behavior

Authentication header should not be removed because neither the host nor the protocol have really changed. 

### Logs/tracebacks

```python-traceback
_
```

### Python Version

```console
_
```

### aiohttp Version

```console
3.8.4
```

### multidict Version

```console
_
```

### yarl Version

```console
_
```

### OS

_

### Related component

Client

### Additional context

_

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Hmm, that does seem a little off, given that it would actually be using the same port for both requests.
If you could open a PR with a test to reproduce the issue, that'd go a long way to getting it fixed (and if you'd like to have a go at fixing it too, even better).

**Comment by Alex-Izquierdo** [comment]
Hello @Dreamsorcerer Thanks for your response. 
This sample script is enough to reproduce the problem. (you need to create the certs)  
You can see that without change the protocol or the host the Authorization header is not received by the server. 
```python
from aiohttp import web, ClientSession
import ssl
import asyncio

# port must be 443 to be cross compatible with host with/without port. It might require admin rights
# Also it can be served behind some http server like nginx
PORT = 443
HOST = "localhost"
URL_REQUEST = f"https://{HOST}:{PORT}/example"


routes = web.RouteTableDef()


@routes.get(r"/example{none:/?}")
async def example(request: web.Request):
    if str(request.rel_url).endswith("/"):
        return web.Response(text=f"Received headers: {request.headers}")
    raise web.HTTPMovedPermanently(f"{request.scheme}://{HOST}/example/")


async def server():
    print("RUNNING SERVER")
    app = web.Application()
    app.add_routes(routes)
    ssl_context = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)

    # openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout domain_srv.key -out domain_srv.crt
    ssl_context.load_cert_chain("domain_srv.crt", "domain_srv.key")

    runner = web.AppRunner(app)

    await runner.setup()
    site = web.TCPSite(runner, HOST, PORT, ssl_context=ssl_context)
    await site.start()


async def client():
    await asyncio.sleep(0.1)
    print("RUNNING CLIENT")
    async with ClientSession() as session:
        headers = {"Authorization": "Bearer some-token"}
        async with session.get(URL_REQUEST, ssl=False, headers=headers) as resp:
            print("History:", resp.history)
            print(await resp.text())


async def main():
    server_task = asyncio.create_task(server())
    client_task = asyncio.create_task(client())
    await asyncio.gather(server_task, client_task)


asyncio.run(main())

```

**Comment by Alex-Izquierdo** [comment]
Also I believe this thing about removing the Authorization header is a too conservative measure. Even the redirect could point to a different host and still be valid (e.g deprecated hostname), so IMO, that behavior should be at least optional.

**Comment by Dreamsorcerer** [comment]
I think it's pretty standard behaviour to discard auth details when changing host. If you don't want the behaviour, I think you'd be better of disallowing redirects and sending the new request to the redirect address directly, thus making it explicit.

A reproducer is helpful, but if you could make a PR with the failing test, it would save us a lot of time. We're pretty short on time at the moment.

**Comment by eyalhei** [comment]
Hi @Dreamsorcerer, I like to take a swing at this

From the looks of it, keeping the header is only setup to work when moving from http to https
in this case, scheme remains https

**Comment by Dreamsorcerer** [comment]
> From the looks of it, keeping the header is only setup to work when moving from http to https

Or, when of the same origin. But, `yarl.URL` reports different origins for the 2 values in this issue, despite both having the same port attribute. It seems to include the port or not based on the original string.

**Comment by Dreamsorcerer** [comment]
This should have been resolved in yarl now, so please update yarl and retest.
