### ISSUE TITLE
The Socket server is unable to retrieve information from requests sent by aiohttp！

### ISSUE THREAD

**Issue by AndreWanga** [fafhrd91/aiohttp#7384]
### Describe the bug

When I use aiohttp to send a request to a socket server, the information retrieved using the socket's recv function is incomplete, resulting in a blank display where the message body should be shown. I have investigated the socket server and found that when I use the requests library to send a request to the socket server, the information is complete. Therefore, it should be an issue with aiohttp.

### To Reproduce

1. run socket server using test_socket.py(in files.zip)
2. run test.py(in files.zip)
3. watch the log of test_socket.py, the msg end with "\r\n\r\n"
[files.zip](https://github.com/aio-libs/aiohttp/files/12098203/files.zip)

### Expected behavior

When using aiohttp to send a request to the socket server, the socket server should be able to read the complete request information. In the above example, it should end with {"hello":1}.

### Logs/tracebacks

```python-traceback
b'POST /test HTTP/1.1\r\nHost: localhost:8888\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\r\nAccept-Language: en-US,en;q=0.5\r\nContent-Type: application/json\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: Python/3.8 aiohttp/3.8.4\r\nContent-Length: 12\r\n\r\n'
```

### Python Version

```console
$ python --version
3.8.10
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.4
```

### multidict Version

```console
$ python -m pip show multidict
6.0.4
```

### yarl Version

```console
$ python -m pip show yarl
1.9.2
```

### OS

ubuntu 20.04

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by mshandrovskiy** [comment]
aiohttp will send headers as soon as possible, then the rest of the body. You are reading from the socket too greedily and then terminating the loop. Setting a breakpoint on line 11 in `test_socket.py` or modifying termination condition on line 15 to `if len(data) < 1:` for example will let you receive the entire request.

**Comment by AndreWanga** [comment]
> 

Thanks for dealing with my issue. I have tried to change the termination condition to if len(data) < 1: , but it seems like that the socket server is stuck in an infinite loop.

**Comment by AndreWanga** [comment]
> aiohttp will send headers as soon as possible, then the rest of the body. You are reading from the socket too greedily and then terminating the loop. Setting a breakpoint on line 11 in `test_socket.py` or modifying termination condition on line 15 to `if len(data) < 1:` for example will let you receive the entire request.

Thanks for dealing with my issue. I have tried to change the termination condition to if len(data) < 1: , but it seems like that the socket server is stuck in an infinite loop.

**Comment by Dreamsorcerer** [comment]
All the examples in the documentation use `if not data`: https://docs.python.org/3/library/socket.html#example

I'd suggest you just use a framework, such as aiohttp, on the receiving end though...
