### ISSUE TITLE
our server try catch this often : client_exceptions.ServerDisconnectedError

### ISSUE THREAD

**Issue by vonslr** [fafhrd91/aiohttp#7495]
### Describe the bug

 async with session.request(method='POST', url=url, data=jsonreq,timeout=50) as req:
  File "/lib/python3.5/site-packages/aiohttp/client.py", line 637, in __aenter__
    self._resp = yield from self._coro
  File "/lib/python3.5/site-packages/aiohttp/client.py", line 241, in _request
    yield from resp.start(conn, read_until_eof)
  File "/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 559, in start
    (message, payload) = yield from self._protocol.read()
  File "/lib/python3.5/site-packages/aiohttp/streams.py", line 509, in read
    yield from self._waiter
  File "/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
aiohttp.client_exceptions.ServerDisconnectedError

### To Reproduce

sema = asyncio.Semaphore(_CONCURRENT_MAX_COUNT)  
    @staticmethod
    async def request(
        org_req: dict,
        service_name: str
    )-> Tuple[str,str,str,list]: 
       
        url,jsonreq = CommunicationConfigHelper.map_request_by_config(org_req,service_name)
        async with CommunicationService.sema:
           
            async with aio.ClientSession(headers={"content_type": "application/json"}) as session:
               
                async with session.request(method='POST', url=url, data=jsonreq,timeout=50) as req:
                 
                    response_data = await req.json(encoding='utf=8')
                    # traceback happens!!!
                    res_header = response_data['ANSWER']['HDR']
                    return 
main code is just this 

### Expected behavior

please let me know the reason and how to fix it ,thank you

### Logs/tracebacks

```python-traceback
quite often but not always
```

### Python Version

```console
$ python --version
Python 3.5.2
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Metadata-Version: 2.0
Name: aiohttp
Version: 2.2.0
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp/
Author: Nikolay Kim <fafhrd91@gmail.com>, Andrew Svetlov <andrew.svetlov@gmail.com>
Author-email: aio-libs@googlegroups.com
Installer: pip
License: Apache 2
Location:/lib/python3.5/site-packages
Requires: yarl, multidict, chardet, async-timeout
Classifiers:
  License :: OSI Approved :: Apache Software License
  Intended Audience :: Developers
  Programming Language :: Python
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Development Status :: 5 - Production/Stable
  Operating System :: POSIX
  Operating System :: MacOS :: MacOS X
  Operating System :: Microsoft :: Windows
  Topic :: Internet :: WWW/HTTP
  Framework :: AsyncIO
```

### multidict Version

```console
$ python -m pip show multidict
Metadata-Version: 2.1
Name: multidict
Version: 5.0.2
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
Installer: pip
License: Apache 2
Location: /lib/python3.5/site-packages
Requires: 
Classifiers:
  License :: OSI Approved :: Apache Software License
  Intended Audience :: Developers
  Programming Language :: Python
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Programming Language :: Python :: 3.7
  Programming Language :: Python :: 3.8
  Development Status :: 5 - Production/Stable
```

### yarl Version

```console
$ python -m pip show yarl
Metadata-Version: 2.0
Name: yarl
Version: 0.10.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
Installer: pip
License: Apache 2
Location: /lib/python3.5/site-packages
Requires: multidict
Classifiers:
  License :: OSI Approved :: Apache Software License
  Intended Audience :: Developers
  Programming Language :: Python
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.4
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Topic :: Internet :: WWW/HTTP
```

### OS

centos7.9

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Your message is pretty badly formatted, but it appears the server is being disconnected.

The only other thing to say, is that we certainly aren't going to support aiohttp 2.2, which was released 6 years ago. Nor is anybody going to support Python 3.5, which has been unsupported for 3 years and is a big security risk now...
Update your machine...

**Comment by vonslr** [comment]
LOL，thank you
