### ISSUE TITLE
Performance issue in case of repeating text()/json() calls for single response instance

### ISSUE THREAD

**Issue by yarula** [fafhrd91/aiohttp#7516]
### Describe the bug

If to  add lazy  initialization for ClientResponse's encoding then It will speed up behaviour in case when `text()` or `json()` methods are called several times for same response.

So '_body' optimization does.

When `text()` is called without encoding and several times we spent a lot of time for encoding 'detect`ion in some cases.

### To Reproduce

1. create response instance
2. call  `await resp.text()` without encoding (most popular case) several time under profiler (py-spy, cprofile)
3. ensure encoding detection eats lots of time

### Expected behavior

get_encoding() detects response text encoding exactly once for single response instance ( should be memoized )

### Logs/tracebacks

```python-traceback
.
```

### Python Version

```console
$ python --version
3.11
```

### aiohttp Version

```console
$ python -m pip show aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

linux

### Related component

Client

### Additional context

asyncio daemon with http interaction with side server via aiohttp

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
If it's the charset-normaliser code that's causing the performance issue, then we'll probably just remove this, it's not providing much benefit: https://github.com/aio-libs/aiohttp/issues/7126#issuecomment-1480097722

**Comment by yarula** [comment]
https://github.com/yarula/aiohttp/pull/1

```
diff --git a/aiohttp/client_reqrep.py b/aiohttp/client_reqrep.py
index d479851396..5bb57cddf0 100644
--- a/aiohttp/client_reqrep.py
+++ b/aiohttp/client_reqrep.py
@@ -712,6 +712,7 @@ def __init__(
         self._real_url = url
         self._url = url.with_fragment(None)
         self._body: Optional[bytes] = None
+        self._encoding: Optional[str] = None
         self._writer: Optional[asyncio.Task[None]] = writer
         self._continue = continue100  # None by default
         self._closed = True
@@ -1005,6 +1006,9 @@ async def read(self) -> bytes:
         return self._body

     def get_encoding(self) -> str:
+        if self._encoding:
+            return self._encoding
+ 
         ctype = self.headers.get(hdrs.CONTENT_TYPE, "").lower()
         mimetype = helpers.parse_mimetype(ctype)

@@ -1030,6 +1034,8 @@ def get_encoding(self) -> str:
         if not encoding:
             encoding = "utf-8"

+        self._encoding = encoding
+
         return encoding

     async def text(self, encoding: Optional[str] = None, errors: str = "strict") -> str:
```

**Comment by Dreamsorcerer** [comment]
You didn't answer the question, but we've now removed the charset guessing code by default, which should make it a lot faster.

Note that .encode()/json.loads() can also be relatively slow, so you should really not be calling these methods multiple times and instead just store the result in a variable..

**Comment by yarula** [comment]
Thank you for improving aiohttp. Gonna profile yet another project based on it .... maybe I'll find something interesting)
