### ISSUE TITLE
aiohttp server rejects cookies value with spaces in between them

### ISSUE THREAD

**Issue by gm7y8** [fafhrd91/aiohttp#7517]
### Describe the bug

For example below cookie key value pair  and additional cookies 

PS_DEVICEFEATURES=  width:1920 height:1080 pixelratio:1 touch:0 geolocation:1 websockets:1 webworkers:1 datepicker:1 dtpicker:1 timepicker:1 dnd:1 sessionstorage:1 localstorage:1 history:1 canvas:1 svg:1 postmessage:1 hc:0 maf:0

When i send rest request to server with this cookie attached to it.. its ignoring all the cookies in set in rest request.

### To Reproduce

For example below cookie key value pair  and additional cookies 

PS_DEVICEFEATURES=  width:1920 height:1080 pixelratio:1 touch:0 geolocation:1 websockets:1 webworkers:1 datepicker:1 dtpicker:1 timepicker:1 dnd:1 sessionstorage:1 localstorage:1 history:1 canvas:1 svg:1 postmessage:1 hc:0 maf:0

When i send rest request to server with this cookie attached to it.. its ignoring all the cookies in set in rest request.

### Expected behavior

Legacy applications doesn't adher to latest cookie standard.. is there a way to bypass this behaviour?

### Logs/tracebacks

```python-traceback
NA
```

### Python Version

```console
$ python --version

3.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
aiohttp==2.2.5
```

### multidict Version

```console
$ python -m pip show multidict
multidict==4.7.6
```

### yarl Version

```console
$ python -m pip show yarl
yarl==0.18.0
```

### OS

Linux 

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
That's too vague to know what's happening. Please provide an actual reproducer or the full HTTP request headers. To get an idea of what aiohttp is seeing, you could look at `request.headers.getall("Set-Cookie")` and `request.raw_headers.getall("Set-Cookie")`, which might contain enough information for us to reproduce.

**Comment by Dreamsorcerer** [comment]
Also, it says you're using aiohttp 2.2.5 from over 6 years ago, plus Python 3.6 which has been unsupported for 3 years.
Update your computer first...
