### ISSUE TITLE
Add Method Debug or Custom Method

### ISSUE THREAD

**Issue by Xifeng2009** [fafhrd91/aiohttp#7546]
### Is your feature request related to a problem?

Add Method Debug or Custom Method

### Describe the solution you'd like

Add Method Debug or Custom Method

### Describe alternatives you've considered

Add Method Debug or Custom Method

### Related component

Client

### Additional context

Add Method Debug or Custom Method

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I'm not sure how anybody is supposed to know what you want with that...
Please fill in some more information.
