### ISSUE TITLE
Brotli Link in Client Quickstart Documentation (Binary Response Content) Broken

### ISSUE THREAD

**Issue by karolwjck** [fafhrd91/aiohttp#7605]
### Describe the bug

The Brotli link within the Binary Response Content section in the Quickstart Documentation results in a 404 (Page not found)

![image](https://github.com/aio-libs/aiohttp/assets/29639757/61ad6b80-8e40-4171-b4ed-3f149a5189da)

### To Reproduce

Click on the Brotli link

![image](https://github.com/aio-libs/aiohttp/assets/29639757/bb8578ce-9b48-48e9-bdcb-f7b037dc6a17)

### Expected behavior

Expected behaviour is to be brought to the brotli GitHub repository: 

- https://github.com/python-hyper/brotlicffi 
- https://github.com/google/brotli

### Logs/tracebacks

```python-traceback
NaN
```

### Python Version

```console
NaN
```

### aiohttp Version

```console
Stable
```

### multidict Version

```console
NaN
```

### yarl Version

```console
NaN
```

### OS

This broken link was observed on a Google Chrome (Microsoft Windows 11 Pro)

### Related component

Client

### Additional context

To put it plainly the link to a GitHub Repo is broken in the documentation.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by alexmac** [comment]
Looks like this was fixed in #7611
