### ISSUE TITLE
ClientResponse: provide way to cap the number of content bytes read in a response

### ISSUE THREAD

**Issue by rgeronimi** [fafhrd91/aiohttp#7614]
### Is your feature request related to a problem?

It is necessary to protect my web client from servers sending back huge response contents, by setting a content limit in specific requests (e.g., 64 megabytes for most). Otherwise my crawlers can hit very large downloads.
Checking the Content-Length header is not sufficient as it is only declarative (and sometimes missing).

### Describe the solution you'd like

Have the ClientResponse.read method accept a max_bytes optional argument.

When provided:
- It stops buffering the response beyond this limit
- And raises a specific exception in such case
- It may (or may not) keep reading the connection's content (chunk by chunk to not allocate a huge memory buffer) to return the connection in a proper state to the connection pool, although that may burn a significant bandwidth and time to do so. Alternatively, it may just break the connection. These are aiohttp internals and the API user does not need at this stage to make that decision

### Describe alternatives you've considered

I have tried reading directly from the underlying response stream with response.content.read(n=...)

However , this approach does not set correctly the private response field "_body", thus triggering exceptions when later calling the response.get_encoding() method that relies on this field to guess the content encoding 

So I am currently, in the positive case where I grabbed all the content, setting directly that private field, but this is dirty as I am manipulating the private data structure of aiohttp

### Related component

Client

### Additional context

aiohttp 3.8.5
python 3.11.5

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Well, the parser will error if there's more data than Content-Length header. So, you could rely on that, as long as it doesn't use Transfer-Encoding: chunked instead of a Content-Length header..

But, I think the best approach currently, would be to read it with the streaming API as you've already done, and do any charset guessing manually (note that we've removed charset guessing by default in 3.9 anyway).

**Comment by rgeronimi** [comment]
> note that we've removed charset guessing by default in 3.9 anyway

Ah that changes everything and in such case I agree with you. But in the 3.9 branch I still see the ClientResponse.get_encoding() method:
https://github.com/aio-libs/aiohttp/blob/daeb5d6c0d458fa962b9b3d570b5de3a277bccbf/aiohttp/client_reqrep.py#L1072C9-L1072C21
Will it be removed?

**Comment by Dreamsorcerer** [comment]
No, the default charset function is now `lambda *_: "utf-8"`, but you can pass your own, so it'll just default to utf-8 if there's no header, unless you define the charset function yourself. Maybe it's still worth considering this request, but I think it's the first time this has come up.

**Comment by Dreamsorcerer** [comment]
Basically, without adding the feature to aiohttp, you could easily just do:
```
try:
    encoding = resp.get_encoding()
except RuntimeError:
    encoding = my_charset_func(resp, body)
```

**Comment by Dreamsorcerer** [comment]
Which actually just does the same thing as `resp.get_encoding()` when `resp._body` _is_ defined.

**Comment by rgeronimi** [comment]
I have a limited understanding of the library's internals and upcoming change in 3.9, as I see currently in the code:
- No change in 3.9 (compared to the current 3.8) related to get_encoding() or to the default charset function
- The implementation of get_encoding in 3.8 is not just calling the charset function, as it does additional things which are very useful to my crawler:
https://github.com/aio-libs/aiohttp/blob/b96e15c171a26e66f696fda6a67cd0b735eb5e7a/aiohttp/client_reqrep.py#L1016-L1037

So I don't understand which change in 3.9 will change the situation.

Without a solution today, either I duplicate get_encoding in my own code, or to keep it working I have to manipulate the private _body field.

2 alternatives to the initially proposed solution would be:
- To remove all charset function logic from aiohttp (but then, all of it, otherwise the API is not consistent) - it thus becomes out of scope for aiohttp
- To add an optional content argument to get_encoding() that should be provided by the client. If it is not provided, the method looks for the _body field. If it is provided, then it is the API client responsibility to decide how it got it (first chunk, first N bytes, etc...) in a way that remains compatible with the charset function it has also chosen previously.

**Comment by Dreamsorcerer** [comment]
> No change in 3.9 (compared to the current 3.8) related to get_encoding() or to the default charset function

https://github.com/aio-libs/aiohttp/blob/6ef6e61f175601c8a2e8c732eaa757a962581410/aiohttp/client.py#L235

There's literally no charset library imported in 3.9 at all anymore.

> The implementation of get_encoding in 3.8 is not just calling the charset function, as it does additional things which are very useful to my crawler:

> or to keep it working I have to manipulate the private _body field.

As I said, my solution does exactly the same thing as calling get_encoding() when there is a _body:
https://github.com/aio-libs/aiohttp/issues/7614#issuecomment-1723921821

**Comment by Dreamsorcerer** [comment]
One possibility would be to move the _body check to the resolver function, but that means that all user functions would need to remember to include that check in their function (and a simple lambda would no longer be possible).

**Comment by Dreamsorcerer** [comment]
Also, related documentation from the master branch: https://docs.aiohttp.org/en/latest/client_advanced.html#character-set-detection

**Comment by Dreamsorcerer** [comment]
I think the above solution is probably fine and we won't implement this feature. Though if someone cares to add that solution to the docs somewhere, a PR would be nice.
