### ISSUE TITLE
Improve message for ServerConnectionError

### ISSUE THREAD

**Issue by rgeronimi** [fafhrd91/aiohttp#7619]
### Is your feature request related to a problem?

Client responses might raised a ServerConnectionError.

In such case, the message (which goes into my logs) is difficult to interpret, as it is a raw, very verbose, python representation of the low-level RawResponseMessage object, which doesn't state anywhere that the connection was, indeed, broken. E.g.:
```
<RawResponseMessage(version=HttpVersion(major=1, minor=1), code=301, reason='Moved Permanently', headers=<CIMultiDictProxy('Location': 'https://econfin.massey.ac.nz/school/documents/seminarseries/manawatu/Short%20sales%20and%20rights%20issues.pdf')>, raw_headers=((b'Location', b'https://econfin.massey.ac.nz/school/documents/seminarseries/manawatu/Short%20sales%20and%20rights%20issues.pdf'),), should_close=True, compression=None, upgrade=False, chunked=False)>
```

### Describe the solution you'd like

A concise error message, or at least message header, should synthesize the issue, e.g., "connection to server broken"
which is the standard for most Python exceptions.

It is then the responsibility of the API client to gather more information, when relevant, from the exception fields, like the raw response message.

### Describe alternatives you've considered

I currently have some workaround code grafted on top of aiohttp to synthesize the messages for type of exception:
```
if isinstance(exception, aiohttp.ServerConnectionError):
    msg = "connection to server broken"
    ...
```

### Related component

Client

### Additional context

aiohttp 3.8.5
Python 3.11.5
macOS 13.5.2

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I think the meaning is obvious from the type. Not sure how you're logging these, but maybe you're calling str(), in which case repr() would likely be more suitable for you.

If you have a more concrete suggestion on how to improve the messaging, please open a PR.

**Comment by dmoklaf** [comment]
I agree.
