### ISSUE TITLE
pypi package aiohttp-edit

### ISSUE THREAD

**Issue by walkingpendulum** [fafhrd91/aiohttp#7628]
### Describe the bug

there is clearly created by mistake PYPI package called aiohttp-edit.

### To Reproduce

1. open url https://pypi.org/project/aiohttp-edit/

### Expected behavior

there is no such package

### Logs/tracebacks

```python-traceback
n/a
```

### Python Version

```console
$ python --version
n/a
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.7.4.post4
3.7.4.post11
```

### multidict Version

```console
$ python -m pip show multidict
n/a
```

### yarl Version

```console
$ python -m pip show yarl
n/a
```

### OS

n/a

### Related component

Server, Client

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I'm not sure why you're telling us, not much we can do. Try and contact the uploader: https://pypi.org/user/Sam01101/
