### ISSUE TITLE
Migrate to time-machine

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#7655]
It looks like freezegun is considered an abandoned project at this point.
We should look at migrating the tests to time-machine instead:
https://pypi.org/project/time-machine/

See, for example: https://github.com/spulec/freezegun/pull/511

**Comment by Dreamsorcerer** [comment]
Seems to only be used in tests/test_cookiejar.py.

**Comment by gruebel** [comment]
hey @Dreamsorcerer,

if it is ok, I would like to take it. Happy to finally be able to contribute back to the project 🍻
