### ISSUE TITLE
3.8.6 must be 3.9.0. Are you use semver or something else?

### ISSUE THREAD

**Issue by DriverX** [fafhrd91/aiohttp#7671]
### Describe the bug

https://github.com/aio-libs/aiohttp/releases/tag/v3.8.6
Release must be 3.9.0, and not patch release 3.8.6.

`aiohttp` uses semver or something {aiohttp}ver?

Recent **patch** releases introduce backward incompatible changes. Stop abusing it. 
This hurts developers and leads to version pinning of aiohttp. This leads to the fact that really important bugfixes do not reach applications in time.

### To Reproduce

Most popular semver patch version bound `pip install 'aiohttp>=3.8.0,<3.9.0'` for aiohttp is not correct because aiohttp introduce backward incompatible changes in patch (!!!) release.

### Expected behavior

`pip install 'aiohttp>=3.8.0,<3.9.0'` should not break applications due to implementation incompatibility

### Logs/tracebacks

```python-traceback
...
```

### Python Version

```console
...
```

### aiohttp Version

```console
- 3.8.6 (https://github.com/aio-libs/aiohttp/pull/7561)
- 3.8.2 (https://github.com/aio-libs/aiohttp/issues/6719)
```

### multidict Version

```console
...
```

### yarl Version

```console
...
```

### OS

any

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Security fixes break SemVer considerations most of the time. It's your responsibility to expect this. Don't shift the blame for your actions to others.

Also: https://hynek.me/articles/semver-will-not-save-you/

**Comment by Dreamsorcerer** [comment]
I think the only noticeable backwards incompatible change is the change to the Python parser anyway. Most users will be using the llhttp parser, which should be more compatible than before (as we added leniency options to resolve regressions in parsing badly formatted HTTP responses).
