### ISSUE TITLE
Missing security advisories for release 3.8.6

### ISSUE THREAD

**Issue by musicinmybrain** [fafhrd91/aiohttp#7711]
### Describe the bug

The release notes on https://github.com/aio-libs/aiohttp/releases/tag/v3.8.6 reference security advisories https://github.com/aio-libs/aiohttp/security/advisories/GHSA-pjjw-qhg8-p2p9 and https://github.com/aio-libs/aiohttp/security/advisories/GHSA-gfw2-4jvh-wgfg, but neither seems to have been published.

### To Reproduce

Visit https://github.com/aio-libs/aiohttp/releases/tag/v3.8.6 and follow links to security advisories.

### Expected behavior

Links are valid.

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
N/A
```

### aiohttp Version

```console
N/A
```

### multidict Version

```console
N/A
```

### yarl Version

```console
N/A
```

### OS

N/A

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
@webknjaz @kenballus

**Comment by kenballus** [comment]
Just added affected/unaffected versions to both advisories. I think that was the missing piece for disclosure.

**Comment by musicinmybrain** [comment]
I’ll keep an eye on it. At the moment, the links still give 404 errors.

**Comment by dirkmueller** [comment]
@kenballus can you please publish the advisories?

**Comment by kenballus** [comment]
I don't think I have permission to. @webknjaz @Dreamsorcerer

**Comment by Dreamsorcerer** [comment]
@webknjaz Do these look OK to publish now?

**Comment by Dreamsorcerer** [comment]
@kenballus Actually, they don't appear to have enough information.
![image](https://github.com/aio-libs/aiohttp/assets/2203121/ef1670bd-2c28-4614-908d-168b06648423)

**Comment by kenballus** [comment]
Sorry! was missing severity.

I just added "moderate" to both, so they should be good to go.

**Comment by webknjaz** [comment]
@Dreamsorcerer thanks for handling this! I emailed it to discuss this topic additionally.

**Comment by msmeissn** [comment]
one ofthe advisories has a CVE, the other one has not. can you allocate a CVE for the second https://github.com/aio-libs/aiohttp/security/advisories/GHSA-pjjw-qhg8-p2p9 ?

**Comment by webknjaz** [comment]
@Dreamsorcerer could you confirm receipt of my email?

@msmeissn I just requested a CVE from GitHub.

**Comment by webknjaz** [comment]
@msmeissn GH rejected the request with the following message:

> GitHub cannot issue a CVE for this Security Advisory because it doesn't comply with one or more of the CVE rules. You can move forward in one of two ways:
>
>  * Review the counting rules and update your Security Advisory to meet the criteria specified in the rules.
>      * Specifically for this advisory, make the following change(s):
>      * Indicate what code in your project is vulnerable
>  * Publish your GitHub Security Advisory as-is.
>
> Thank you for making the open source ecosystem more secure by fixing and responsibly disclosing this vulnerability.

@kenballus @Dreamsorcerer could you look into making the requested changes there?
Here's past examples of more comprehensive descriptions:
* https://github.com/aio-libs/aiohttp/security/advisories/GHSA-v6wp-4m6f-gcjg
* https://github.com/aio-libs/aiohttp/security/advisories/GHSA-45c4-8wx5-qw6w
