### ISSUE TITLE
sdist is missing test requirements file

### ISSUE THREAD

**Issue by mtelka** [fafhrd91/aiohttp#7746]
### Describe the bug

The sdist package at PyPI is missing `requirements/test.txt` and/or `requirements/test.in` file.  Without them it is hard to know what Python projects are needed to successfully run test.

This causes some inconvenience during packaging of `aiohttp` for OpenIndiana since we are running tests to make sure our packages works properly.

### To Reproduce

Download sdist from PyPI and unpack it.

### Expected behavior

There is `requirements/test.txt` and/or `requirements/test.in` file.

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
N/A
```

### aiohttp Version

```console
3.8.6
```

### multidict Version

```console
N/A
```

### yarl Version

```console
N/A
```

### OS

OpenIndiana

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
Fair. Integrating https://github.com/re-actors/checkout-python-sdist would be a welcome contribution if someone would want to make a PR.
