### ISSUE TITLE
[3.9] Import fails on Windows PyPy

### ISSUE THREAD

**Issue by JelleZijlstra** [fafhrd91/aiohttp#7848]
### Describe the bug

Importing aiohttp 3.9.0 on Windows in PyPy 3.8 fails with an error about `time.gmtime`.

### To Reproduce

* Run PyPy 3.8 on Windows
* import aiohttp

### Expected behavior

No crash

### Logs/tracebacks

```python-traceback
.tox\ci-pypy3\lib\site-packages\aiohttp\__init__.py:6: in <module>
    from .client import (
.tox\ci-pypy3\lib\site-packages\aiohttp\client.py:76: in <module>
    from .cookiejar import CookieJar
.tox\ci-pypy3\lib\site-packages\aiohttp\cookiejar.py:39: in <module>
    class CookieJar(AbstractCookieJar):
.tox\ci-pypy3\lib\site-packages\aiohttp\cookiejar.py:64: in CookieJar
    calendar.timegm(time.gmtime(MAX_TIME))
E   ValueError: Invalid argument
```

(Seen in [Black's CI](https://github.com/psf/black/actions/runs/6914280784/job/18811967454?pr=4010))
```


### Python Version

```console
Successfully set up PyPy 7.3.11 with Python (3.8.16)
```

### aiohttp Version

```console
Successfully installed aiohttp-3.9.0 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 black-0.1.dev1+g7e1ebdd click-8.1.7 frozenlist-1.4.0 idna-3.4 multidict-6.0.4 mypy-extensions-1.0.0 pathspec-0.11.2 typing-extensions-4.8.0 yarl-1.9.2
```

### multidict Version

```console
multidict-6.0.4
```

### yarl Version

```console
yarl-1.9.2
```

### OS

Windows

### Related component

Server

### Additional context

This seems related to #7824. It already catches OSError; I suspect PyPy just throws a different exception here.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Ah, I bumped the CI to Pypy 3.9 because it segfaults 50% of the time (didn't actually help, still segfaults), so must have missed this one.

**Comment by Dreamsorcerer** [comment]
@Rongronggg9

**Comment by Dreamsorcerer** [comment]
Oh, we never ran it on Windows though, so maybe we wouldn't have caught it.
