### ISSUE TITLE
Nominate J. Nick Koston to aiohttp committers

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#7880]
I'm nominating @bdraco to the aiohttp Core team.

There's plenty of examples in the previous weeks of good quality PRs, with all the tests we'd expect:
https://github.com/aio-libs/aiohttp/pulls?q=is%3Apr+author%3Abdraco+is%3Aclosed
There is a clear understanding of our development requirements.

@aio-libs/aiohttp-dev please vote here in the comments (or reaction).
The vote ends Wednesday, November 29.

**Comment by webknjaz** [comment]
+1

**Comment by Dreamsorcerer** [comment]
Great, @bdraco you should have access now.

**Comment by bdraco** [comment]
Thank you!

On a side note, Home Assistant just shipped aiohttp 3.9.1 to the beta channel and so far everything has been going well.

**Comment by samuelcolvin** [comment]
Great, thanks @bdraco for volunteering.

**Comment by webknjaz** [comment]
@bdraco if you want to be notified about changes to some files, that can be arranged through https://github.com/aio-libs/aiohttp/blob/master/.github/CODEOWNERS.
Also, FYI, we have a matrix space and rooms — [#aio-libs-space:matrix.org](https://matrix.to/#/%23aio-libs-space:matrix.org) and [#aio-libs:matrix.org](https://matrix.to/#/%23aio-libs:matrix.org). That's where some people come to ask questions more interactively. Might be useful to have some presence there. Personally, these days I'm best reachable through matrix myself.

**Comment by bdraco** [comment]
> @bdraco if you want to be notified about changes to some files, that can be arranged through [`master`/.github/CODEOWNERS](https://github.com/aio-libs/aiohttp/blob/master/.github/CODEOWNERS?rgh-link-date=2023-12-01T02%3A18%3A40Z).

Thanks. I've got notifications filtered via email pretty well so hopefully I won't miss anything that I'm concerned about.

> Also, FYI, we have a matrix space and rooms — [#aio-libs-space:matrix.org](https://matrix.to/#/%23aio-libs-space:matrix.org) and [#aio-libs:matrix.org](https://matrix.to/#/%23aio-libs:matrix.org). That's where some people come to ask questions more interactively. Might be useful to have some presence there. Personally, these days I'm best reachable through matrix myself.

I set up a matrix account and joined that room, however I'm usually much easier to reach on discord (same handle) if you need something urgently.
