### ISSUE TITLE
Replace aiodns with dnspython

### ISSUE THREAD

**Issue by inkozlo** [fafhrd91/aiohttp#7922]
### Is your feature request related to a problem?

It's not a significant issue, but the replacement has the potential to streamline aiohttp internals a bit, and I believe we can ensure backward compatibility.

### Describe the solution you'd like

Use https://dnspython.readthedocs.io/en/latest/async-resolver.html

### Describe alternatives you've considered

no need change atm

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I think you'll need to provide more information on how this improves things. aiodns appears to be a very small, lightweight library that does exactly what we want. I'm not sure what is meant by "streamline aiohttp internals a bit", given that the integration with aiodns appears to be only a few lines of code.
