### ISSUE TITLE
Appkey is not defined in the handlers.

### ISSUE THREAD

**Issue by jmspereira** [fafhrd91/aiohttp#7947]
### Describe the bug

Hey, first of all, thank you for the awesome project! 
I'm not sure that this is even a bug, or if it is the desired behavior (but if so, I do not think it is very clear).

### To Reproduce

```
from typing import NamedTuple

from aiohttp import web


class TestObj(NamedTuple):
    x: int
    y: int


async def do_something(request: web.Request) -> web.Response:
    print(request.app[web.AppKey("test", TestObj)])

    return web.Response()


def main():
    app = web.Application()
    app.add_routes([web.get("/do-something", do_something)])
    app[web.AppKey("test", TestObj)] = TestObj(1, 2)

    web.run_app(app, port=8182, access_log=None, print=lambda x: None)


if __name__ == "__main__":
    main()
```

### Expected behavior

The key should be present because it has the same name and type. Otherwise is very difficult to maintain a global instance of the AppKey to pass to the handlers.

### Logs/tracebacks

```python-traceback
Error handling request
Traceback (most recent call last):
  File "/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "test_aiohttp.py", line 12, in do_something
    print(request.app[web.AppKey("test", TestObj)])
  File "/lib/python3.10/site-packages/aiohttp/web_app.py", line 194, in __getitem__
    return self._state[key]
KeyError: <AppKey(__main__.test, type=__main__.TestObj)>
```

### Python Version

```console
$ python --version
Python 3.10.12
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.9.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Requires: aiosignal, async-timeout, attrs, frozenlist, multidict, yarl
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.3
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Requires: idna, multidict
```

### OS

Ubuntu 22.04

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
The key is the instance, not the name/type.

So, you need to save the key somewhere globally and reuse it across the project.

**Comment by Dreamsorcerer** [comment]
We can probably make this clearer in the docs, but you'll see all the examples use a variable, rather than creating a new instance when indexing.

**Comment by jmspereira** [comment]
Thank you for the answer, but what is supposed to do when the handlers are defined in a different module than the server initialization?
Should the "standard" define all the app keys in a module and import them both in the module that initiates the server and in the handlers modules?

**Comment by Dreamsorcerer** [comment]
Yes, there needs to be a canonical location. For projects, I typically put them in typedefs.py or similar (along with typing aliases etc.). Between different projects, it needs to be imported, for example see aiohttp-jinja2:

> The static function has similar usage, except it requires you to set app[aiohttp_jinja2.static_root_key].
> ```
> app = web.Application()
> app[aiohttp_jinja2.static_root_key] = "/static"
> ```
https://aiohttp-jinja2.readthedocs.io/en/latest/#default-globals

And we use that key, for example, in aiohttp-devtools:
https://github.com/aio-libs/aiohttp-devtools/blob/master/aiohttp_devtools/runserver/serve.py#L28

**Comment by jmspereira** [comment]
Ok, I will do it, thank you so much for the fast answer!

**Comment by jmspereira** [comment]
Hey @Dreamsorcerer, I was making this migration but there are some cases where the value that I want to store an AppKey is a callable (for instance a partial that is completed with the remaining args in the handler). However when I do:

`some_key = AppKey("some_key", Callable[[type_arg1, type_arg2], return_type])`

Mypy is not very happy saying:
error: Argument 2 to "AppKey" has incompatible type "object"; expected "type[Never] | None"

**Comment by Dreamsorcerer** [comment]
See the examples in the docs for the alternative syntax. i.e. It'll work with `AppKey[Callable]("some_key")`. The problem is that things like Callable are not _types_, but we don't want to annotate it as anything and have mistakes like `AppKey(..., 5)`. I'm not sure if there is a better annotation to make this work.

**Comment by Dreamsorcerer** [comment]
I've opened a discussion to see if there's anything we can do in the future:
https://github.com/python/typing/discussions/1543

**Comment by jmspereira** [comment]
Thanks!
