### ISSUE TITLE
`test_import_time` failed on RISC-V

### ISSUE THREAD

**Issue by moui0** [fafhrd91/aiohttp#7955]
### Describe the bug

I'm trying to build aiohttp on RISC-V machines, but all of them fail in the import time test. The import time on RISC-V is much longer than 200ms: Two of the machines take about 500 to 700 milliseconds and the other two take 1 to 2 seconds

I wish you could increase the timeout, but it would make this test not very effective.

### To Reproduce

`pytest`

### Expected behavior

Pass this test.

### Logs/tracebacks

```python-traceback
https://archriscv.felixc.at/.status/log.htm?url=logs/python-aiohttp/python-aiohttp-3.9.1-1.log
```

### Python Version

```console
$ python --version
3.11.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.9.1
```

### multidict Version

```console
$ python -m pip show multidict
6.0.4
```

### yarl Version

```console
$ python -m pip show yarl
1.9.2
```

### OS

Arch Linux on RISC-V

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
I would just ignore it, as it's probably not very relevant to you. Feel free to make a PR though which makes it easier to ignore or makes the threshold configurable.

**Comment by moui0** [comment]
Thank you. I'll skip this test.
