### ISSUE TITLE
Receiving different response when using aiohttp instead of requests module?

### ISSUE THREAD

**Issue by H-Maa** [fafhrd91/aiohttp#7982]
### Describe the bug

I'm trying to send data to an api using aiohttp, but it only works when I use requests module. The response from the api is blank when I use aiohttp, which I believe is caused by incorrect payload encoding.

### To Reproduce

```
headers = {
            "accept-encoding": "gzip, deflate, br",
            "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
            ...
            }
format_payload returns either dict (for aiohttp) or urlencoded dict (for requests)

# ---------- Not working
payload = await self.format_payload(id) # returns payload dict
headers = self.retrieve_headers(headers=headers, add_params=None, payload=urlencode(payload), cookies=cookies)

async with self.aioss.post(
    url,
    params=self.params,
    headers=headers,
    data=json.dumps(payload)
) as resp:
    data = await resp.json()
    return data

# ---------- Working
payload = self.format_payload(id)  # returns urlencoded payload
headers = self.retrieve_headers(headers=headers, add_params=None, payload=payload, cookies=cookies)

data = requests.post(
    url,
    params=self.params,
    headers=headers,
    data=payload
)```

```
### Expected behavior

Response from API should not be blank, I think the issue is that the payload is encoded incorrectly for the API.
Payload should look like this: `id=73129014464&text=hi%21%21%21+&text_extra=&image_extra=&is_self_see=0&channel_id=23&action_type=0&publish_scenario=0&skip_rethink=0`

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
3.11.4
```

### aiohttp Version

```console
3.8.5
```

### multidict Version

```console
6.0.4
```

### yarl Version

```console
1.9.2
```

### OS

Windows 11

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
The libraries do not work identically, but I don't think you have provided enough information to find the mistake with your aiohttp code.

For example, passing a str as a URL will encode/escape the URL, which could be one cause (e.g. if you have query parameters, you should pass them in the params argument, or pass a pre-encoded yarl.URL rather than str).

**Comment by H-Maa** [comment]
> The libraries do not work identically, but I don't think you have provided enough information to find the mistake with your aiohttp code.
> 
> For example, passing a str as a URL will encode/escape the URL, which could be one cause (e.g. if you have query parameters, you should pass them in the params argument, or pass a pre-encoded yarl.URL rather than str).

I just figured out what the issue is with mitmproxy.
```async with self.aioss.post(
    url,
    params=self.params,
    headers=headers,
    data=json.dumps(payload)```
was not properly encoding the URL. I had also tried
``` url = url + "?" + urlencode(self.device.params)```
but I didn't realize I had to use yarl
```
url = url + "?" + urlencode(self.device.params)
        
url = yarl.URL(url, encoded=True)
````

This works now.

**Comment by H-Maa** [comment]
I just figured out what the issue is with mitmproxy.
```
async with self.aioss.post(
    url,
    params=self.params,
    headers=headers,
    data=json.dumps(payload)
```
was not properly encoding the URL. I had also tried
```url = url + "?" + urlencode(self.device.params)```
but I didn't realize I had to use yarl to mark it as encoded
```
url = url + "?" + urlencode(self.device.params)
        
url = yarl.URL(url, encoded=True)
```

This works now.

**Comment by Dreamsorcerer** [comment]
> `url = url + "?" + urlencode(self.device.params)`

In this case, it'd probably make sense to pass them to the params argument, rather than constructing the URL yourself.
