### ISSUE TITLE
Issue with the OutputString method in controlling value assignment

### ISSUE THREAD

**Issue by iconFehu** [fafhrd91/aiohttp#7999]
### Is your feature request related to a problem?
I am currently facing an issue with the OutputString method in the CookieGenerator class of my web scraping project, which is named . The method is responsible for generating the Set-Cookie header, and I've noticed that it concatenates the self.coded_value by default.

I am encountering a challenge with the OutputString method in the Cookie class within the aiohttp library. The method is responsible for generating the Set-Cookie header, and it appears to concatenate the self.coded_value by default.

The current implementation seems to hardcode the usage of self.coded_value when constructing the key-value pair for the Set-Cookie field. I would like to have the flexibility to control whether it uses self.coded_value or self.value based on a parameter.

### Describe the solution you'd like

I propose modifying the OutputString method to accept an additional parameter, perhaps named use_coded_value, that would allow users to choose between self.coded_value and self.value during the construction of the Set-Cookie field.

### Describe alternatives you've considered

```
# Using self.coded_value
result_string = instance.OutputString(use_coded_value=True)

# Using self.value
result_string = instance.OutputString(use_coded_value=False)
```

### Related component

Client

### Additional context

I'm using this within an aiohttp project for web scraping.
![bb06245360dce25d6ab8b35ad2598adc](https://github.com/aio-libs/aiohttp/assets/46149128/16f3bee3-5c04-4957-acb9-f893ed6da8d6)

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
You appear to be submitting an issue from a template that has absolutely nothing to do with this library.
