### ISSUE TITLE
`FileResponse` has undefined behavior if the file is changed out from under it between the `stat` and `open` calls

### ISSUE THREAD

**Issue by bdraco** [fafhrd91/aiohttp#8013]
This was discovered while fixing another issue in https://github.com/aio-libs/aiohttp/pull/8012#issuecomment-1883851654

This is a rare case so its not likely we need to prioritize fixing it but I'm sure this race has bitten someone with random unexplained failures who uses aiohttp to serve index or signature files that get changed out frequently.

### Describe the bug

We can fix this by `open`ing the file first, doing `fstat` to get the `stat`

### To Reproduce

replace the file on the FS between the `stat` and `open` call

### Expected behavior

The handler should still send the original file

### Logs/tracebacks

```python-traceback
n/a
```

### Python Version

```console
$ python --version
```

### aiohttp Version

```console
$ python -m pip show aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

n/a

### Related component

Server

### Additional context

n/a

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment]
It looks like this is worth fixing as it will also give a nice performance boost by reducing one executor job per request https://github.com/aio-libs/aiohttp/pull/10095

**Comment by steverep** [comment]
> It looks like this is worth fixing as it will also give a nice performance boost by reducing one executor job per request #10095

👍🏻 but I'd add a benchmark for a 304 response as well.  Those would end up with a penalty from any overhead opening the file and the extra executor job to close it (4xx responses would also be penalized but less a concern I guess).

**Comment by bdraco** [comment]
> > It looks like this is worth fixing as it will also give a nice performance boost by reducing one executor job per request #10095
> 
> 👍🏻 but I'd add a benchmark for a 304 response as well. Those would end up with a penalty from any overhead opening the file and the extra executor job to close it (4xx responses would also be penalized but less a concern I guess).

I kept that in mind when I wrote the fix. The number of executor jobs remains the same for both a success and 304 response.  If you would like to add a benchmark for 304s as well in a fresh PR, that would be a nice addition to ensure we don't regress it in the future.

**Comment by steverep** [comment]
The fix certainly handles the closings smartly, but I would be more worried about the additional overhead of the file openings.  If cache is controlled well, many implementations are likely serving 304s much more than 200s.  #10101 probably introduced a minor penalty there, but I don't see a better way to fix this issue. 🤷🏻‍♂️

**Comment by bdraco** [comment]
> > It looks like this is worth fixing as it will also give a nice performance boost by reducing one executor job per request #10095
> 
> 👍🏻 but I'd add a benchmark for a 304 response as well. Those would end up with a penalty from any overhead opening the file and the extra executor job to close it (4xx responses would also be penalized but less a concern I guess).
@steverep 
I went ahead and wrote it in https://github.com/aio-libs/aiohttp/pull/10114
