### ISSUE TITLE
request tuto/method how to debug unclosed sessions on exit

### ISSUE THREAD

**Issue by copdips** [fafhrd91/aiohttp#8180]
### Is your feature request related to a problem?

Hello,

Sometimes, we forget to close aiohttp sessions. This can lead to errors like the following upon script exit:

```shell
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001D33B5C8988>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001D33B7139A8>, 113308.796)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001D33B5C87C8>
```

My question is: Is there an easy debugging method to identify which session object remains open?

In a large project, we may use multiple aiohttp sessions for various purposes, such as aio credentials, aio storage, or direct HTTPS sessions. When we forget to close all of them, it becomes quite difficult to pinpoint the still-open ones using only the error message above.

### Describe the solution you'd like

It would be helpful if the error message included the `line number` where the session was initially opened.

### Describe alternatives you've considered

During session creation, it would be useful to accept `a parameter for a label`. This label could then be displayed in the error message if the session is not closed properly.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
This isn't really an issue with aiohttp, it's an issue with your architecture/coding practices.

If you always use `async with` when creating a session, then you won't have any unclosed sessions. Alternatively, I've seen libraries that provide context manager stacks as part of an application's lifecycle (maybe combined with dependency injection). You can use a linting rule or something to enforce this usage across your code.

**Comment by copdips** [comment]
@Dreamsorcerer 

Thanks for your prompt reply.

While I know that `async with` is the recommended pratice, there are situations where we might be called upon to debug  code outside of our control, such as code written by others or in third party modules. (aiohttps is used by many third party aio modules).

Unfortunately, when these external sources don't use `async with`, it can be challenging to identify the unclosed sessions.

Only after pingpointing these unclose sessions, can we suggest adpoting `async with` as a best pratice.

So I think this is real use case.

**Comment by Dreamsorcerer** [comment]
If you want to give it a go, it'd look something like:
```
from aiohttp.helpers import DEBUG

if DEBUG:
    self._tb = traceback.extract_stack()
```

**Comment by copdips** [comment]
hello,

Is it possible to save the traceback stack during the session `__init__` if DEBUG mode is on, and display it in the error message as follows ?

For example:

```diff
class ClientSession:
    def __init__(
        self,
        ...
    ) -> None:
+       if DEBUG:
+           import traceback
+           self.tb = traceback.extract_stack()
        ...

    def __del__(self, _warnings: Any = warnings) -> None:
        if not self.closed:
            kwargs = {"source": self}
            _warnings.warn(
                f"Unclosed client session {self!r}", ResourceWarning, **kwargs
            )
            message = f"Unclosed client session"
+           if DEBUG:
+               message += f"\nSession creation traceback stack: {self.tb}"
            context = {"client_session": self, "message": f"Unclosed client session: {self.tb}"}
            if self._source_traceback is not None:
                context["source_traceback"] = self._source_traceback
            self._loop.call_exception_handler(context)
```

**Comment by Dreamsorcerer** [comment]
That was my suggestion. Feel free to make a PR if you've got it working. Will need a test to show it's working correctly too (needs to be marked with `@pytest.mark.dev_mode`).

**Comment by copdips** [comment]
sorry, I just found it's already been implemented, when setting the env var `PYTHONASYNCIODEBUG=1`, the unclosed session gives already the creation traceback, all is good now, thank for your help.
