### ISSUE TITLE
OSError : bind(): bad family

### ISSUE THREAD

**Issue by anshm-2166** [fafhrd91/aiohttp#8192]
### Describe the bug

I'm running a server on android using aiohttp. The client part of aiohttp lib works finely as intended, but when running a server, I encounter an issue.

Error : 
![image](https://github.com/aio-libs/aiohttp/assets/149814863/756737af-f183-4f49-b136-42e4d5f9713d)
![image](https://github.com/aio-libs/aiohttp/assets/149814863/3b1b6a90-1219-42cb-93c2-7934a3b4c4ef)

My Code : 
```python
# examples/server_simple.py
from aiohttp import web

async def handle(request):
    name = request.match_info.get('name', "Anonymous")
    text = "Hello, " + name
    return web.Response(text=text)

async def wshandle(request):
    ws = web.WebSocketResponse()
    await ws.prepare(request)

    async for msg in ws:
        if msg.type == web.WSMsgType.text:
            await ws.send_str("Hello, {}".format(msg.data))
        elif msg.type == web.WSMsgType.binary:
            await ws.send_bytes(msg.data)
        elif msg.type == web.WSMsgType.close:
            break

    return ws


app = web.Application()
app.add_routes([web.get('/', handle),
                web.get('/echo', wshandle),
                web.get('/{name}', handle)])

if __name__ == '__main__':
    web.run_app(app)
```

### To Reproduce

N/A

### Expected behavior

Server functionality should function normally.

### Logs/tracebacks

```python-traceback
Stated above in description.
```

### Python Version

```console
$ python --version
Python 3.11.8
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.9.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: /data/user/0/org.softbuddy.pythonx/files/PY_HOME/.local/lib/python3.11/site-packages
Requires: aiosignal, attrs, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /data/user/0/org.softbuddy.pythonx/files/PY_HOME/.local/lib/python3.11/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /data/user/0/org.softbuddy.pythonx/files/PY_HOME/.local/lib/python3.11/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Android 14 API 34 aarch64 (arm64-v8a) 

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Soft-Buddy** [comment]
Nevermind, found the solution. My python was compiled without IPV6 support, so the error was coming. A homie suggested me to enable it and now it's fixed. Thank you for the excellent lib.

![image](https://github.com/aio-libs/aiohttp/assets/149814863/eeca4db1-b532-46cd-a87e-40c8d9c2ed01)
![image](https://github.com/aio-libs/aiohttp/assets/149814863/dcd503e9-1ab4-4aab-a4b0-4aada81b9d7a)

Kudos to all the developers !
