### ISSUE TITLE
aiohttp.web listens both TCP and Unix socket if `-U` has been supplied

### ISSUE THREAD

**Issue by eirnym** [fafhrd91/aiohttp#8205]
### Describe the bug

documentation for `-U` `aiohttp.web` parameter: `Unix file system path to serve on. Specifying a path will cause hostname and port arguments to be ignored.`

The `aiohttp` web argument parser expects that it would be run without `-H` and `-P` parameters. Thus default has been passed to `argparse`. Defaults in argparse works in way that if values has not been specified, they are set anyway. In this situation it works not as intended. The possible solution is to override

Bonus: there may be many hostnames could be provided (as run server accepts), but argument parser is not adapted in this way. 

### To Reproduce

Let's take very basic aiohttp server implementation from tutorial:

```python
from aiohttp import web

async def hello(request):
    return web.Response(text="Hello, world")


def init_func(argv):
    app = web.Application()
    app.add_routes([web.get('/', hello)])
    return app
```

and run it:

```sh
$ python -m aiohttp.web -U /path/to/socket/file.sock package.module:init_func
```

### Expected behavior

I'm expecting that server is:
* Listening on localhost:8080 (as documented) if no arguments explicitly provided
* Listening on hostname:port (as documented) if hostname:port are provided
* Listening on Unix socket only If Unix socket is provided and hostname isn't explicitly provided (as documented)
* Listening on Unix socket only (as documented) or both (optional, but desired) If both unix socket and hostname are explicitly provided

### Logs/tracebacks

```python-traceback
DEBUG:asyncio:Using selector: KqueueSelector
======== Running on http://localhost:8080, http://unix:/path/to/socket/file.sock: ========
(Press CTRL+C to quit)
```

### Python Version

```console
$ python --version
Python 3.12.2
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.9.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /Users/eirnym/Developer/sdk/python/312/iguana/lib/python3.12/site-packages
Requires: aiosignal, attrs, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/eirnym/Developer/sdk/python/312/iguana/lib/python3.12/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.4
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /Users/eirnym/Developer/sdk/python/312/iguana/lib/python3.12/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

macOS

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Right, that should probably be replace with a recommendation to use aiohttp-devtools though...

**Comment by webknjaz** [comment]
Not sure about a recommendation but a note regarding another way would be useful. Many frameworks provide runpy entrypoints so I think it should remain exposed.
