### ISSUE TITLE
ClientSession cannot reuse connection pool

### ISSUE THREAD

**Issue by ladybai** [fafhrd91/aiohttp#8216]
### Describe the bug

ClientSession cannot reuse connection pool

### To Reproduce

Here is my code:
![image](https://github.com/aio-libs/aiohttp/assets/136571839/0eccc46e-82d0-468c-9a38-7fd1ad68440c)

ClientSession is created only once. The purpose is to reuse the connection. Many requests with the same URL and port are sent at the same time, but the packet capture result shows that the connection created manny times
    

### Expected behavior

Many requests with the same URL and port should share one connection

### Logs/tracebacks

```python-traceback
None
```

### Python Version

```console
$ python --version
Python 3.8.8
```

### aiohttp Version

```console
$ python -m pip show aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
3.9.1
```

### yarl Version

```console
$ python -m pip show yarl
1.9.4
```

### OS

Windows

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by ladybai** [comment]
I debuged the BaseConnector.connect function, and found a suspicious point:
`proto = self._get(key)`
the proto always return None, and causes the connection to be re-established all the time

**Comment by Dreamsorcerer** [comment]
> Many requests with the same URL and port are sent at the same time

Maybe you meant something else, but you can't send 2 requests at the same time with the same connection. So, if your description is accurate, then this is working as intended (i.e. the only way it could possibly work).

If you are sending multiple requests over time and have completed/closed the previous requests/responses (cleanly), then it should be reusing the connections.

**Comment by Olegt0rr** [comment]
@ladybai,

Can't reproduce the issue

```python
import asyncio

from aiohttp import ClientSession, TCPConnector


async def main():
    connector = TCPConnector()
    session = ClientSession(connector=connector, base_url="https://www.google.com")

    for _ in range(5):
        async with session.get("/") as response:
            await response.text()
            assert len(connector._conns) == 1  # <--------------- LOOK HERE

    await session.close()


if __name__ == '__main__':
    asyncio.run(main())

```
