### ISSUE TITLE
ERROR: aiohttp has an invalid wheel, .dist-info directory 'yarl-1.9.4.dist-info' does not start with 'aiohttp'

### ISSUE THREAD

**Issue by JulianChenlol** [fafhrd91/aiohttp#8245]
### Describe the bug

aiohttp-3.9.3

I have downloaded aiohttp package from an online machine(Centos 7.9), and uploaded them to another offline machine(Centos 7.9). Both Python 3.10.1,Pip 21.2.4. 

pip install --no-index --find-links=package -r requirements.txt
I got an error:
Processing ./package/aiohttp-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
ERROR: aiohttp has an invalid wheel, .dist-info directory 'yarl-1.9.4.dist-info' does not start with 'aiohttp'

### To Reproduce

I have downloaded aiohttp package from an online machine(Centos 7.9), and uploaded them to another offline machine(Centos 7.9). Both Python 3.10.1,Pip 21.2.4. 
-----
These are instructions:
python -m pip download -d package -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

-----
These are aiohttp related.
-rw-r--r-- 1 root root 1226319 Mar 25 14:13 aiohttp-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
-rw-r--r-- 1 root root    7617 Mar 25 14:13 aiosignal-1.3.1-py3-none-any.whl
-rw-r--r-- 1 root root    5721 Mar 25 14:13 async_timeout-4.0.3-py3-none-any.whl
-rw-r--r-- 1 root root   60752 Mar 25 14:13 attrs-23.2.0-py3-none-any.whl
-rw-r--r-- 1 root root  239539 Mar 25 14:13 frozenlist-1.4.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl
-rw-r--r-- 1 root root   61567 Mar 25 14:13 idna-3.6-py3-none-any.whl
-rw-r--r-- 1 root root  124266 Mar 25 14:13 multidict-6.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
-rw-r--r-- 1 root root  301580 Mar 25 14:13 yarl-1.9.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
-----
pip install --no-index --find-links=package -r requirements.txt
I got an error:
Processing ./package/aiohttp-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
ERROR: aiohttp has an invalid wheel, .dist-info directory 'yarl-1.9.4.dist-info' does not start with 'aiohttp'

### Expected behavior

I tried to install from offline package on the online machine, and there is no bug, but the offline machine had an error.

### Logs/tracebacks

```python-traceback
pip install --no-index --find-links=package -r requirements.txt
I got an error:
Processing ./package/aiohttp-3.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
ERROR: aiohttp has an invalid wheel, .dist-info directory 'yarl-1.9.4.dist-info' does not start with 'aiohttp'
```

### Python Version

```console
$ python --version
Python 3.10.1
```

### aiohttp Version

```console
$ python -m pip show aiohttp
I will install 3.9.3
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /usr/local/python3/lib/python3.10/site-packages
Requires: 
Required-by: yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.4
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /usr/local/python3/lib/python3.10/site-packages
Requires: multidict, idna
Required-by:
```

### OS

Linux VM_131_141_linux 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Related component

Server

### Additional context

THANK YOU!

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by webknjaz** [comment]
You're not downloading from the PyPI where we upload the official releases. Perhaps the maintainers of your third party index messed up the file names. Take it up with them. The wheels we publish are installable. You may need to get a newer pip to so it'd understand the modern tags, but that's about it. Though the error is unlikely related to pip being old — it indicates that you must be getting corrupted files. If you want to verify the files, compare their checksums with the hashes on the PyPI. Most of our projects (aiohttp/multidict/frozenlist/yarl) also publish sigstore signatures on the GitHub Releases pages like https://github.com/aio-libs/aiohttp/releases/tag/v3.9.3. You can use them for checking the provenance as well.

**Comment by JulianChenlol** [comment]
> You're not downloading from the PyPI where we upload the official releases. Perhaps the maintainers of your third party index messed up the file names. Take it up with them. The wheels we publish are installable. You may need to get a newer pip to so it'd understand the modern tags, but that's about it. Though the error is unlikely related to pip being old — it indicates that you must be getting corrupted files. If you want to verify the files, compare their checksums with the hashes on the PyPI. Most of our projects (aiohttp/multidict/frozenlist/yarl) also publish sigstore signatures on the GitHub Releases pages like https://github.com/aio-libs/aiohttp/releases/tag/v3.9.3. You can use them for checking the provenance as well.

Thank you! I downloaded from the GitHub Releases pages and it works!
