### ISSUE TITLE
Expired cookies not listed in the response cookies

### ISSUE THREAD

**Issue by novitae** [fafhrd91/aiohttp#8274]
### Describe the bug

When sending a request, the request expired cookies returned in the response are not listed in the `.cookies` attributes.

### To Reproduce

1. Send a request to a server
2. Some of the cookies returned must be expired
3. Check the response.cookies
4. All the expired are missing

### Expected behavior

They should be present

### Logs/tracebacks

```python-traceback
None
```

### Python Version

```console
$ python --version
Python 3.11.7
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.9.3
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /Users/n/Library/Caches/pypoetry/virtualenvs/uchecker-ImmZ4SqW-py3.11/lib/python3.11/site-packages
Requires: aiosignal, attrs, frozenlist, multidict, yarl
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/n/Library/Caches/pypoetry/virtualenvs/uchecker-ImmZ4SqW-py3.11/lib/python3.11/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.4
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /Users/n/Library/Caches/pypoetry/virtualenvs/uchecker-ImmZ4SqW-py3.11/lib/python3.11/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

macOS

### Related component

Client

### Additional context

Here is the response cookies of my aiohttp request seen from my proxy:
<img width="630" alt="Capture d’écran 2024-03-31 à 13 14 50" src="https://github.com/aio-libs/aiohttp/assets/85891169/5a7fb392-30a7-4326-8c12-c84701d5cecf">
Here is the listed cookies (you can see that only the expiring in 2034 are here)
<img width="579" alt="Capture d’écran 2024-03-31 à 13 15 32" src="https://github.com/aio-libs/aiohttp/assets/85891169/4314b36a-508f-4d4c-9d60-bf0903aad6f6">
Here is the set-cookie header, only one remains.
<img width="1067" alt="Capture d’écran 2024-03-31 à 13 16 27" src="https://github.com/aio-libs/aiohttp/assets/85891169/f14b8a1e-4eae-48f7-b396-3e9365c3ca8e">
So at the end a cookie disappeared, two are stored in cookies, and one is in the headers.

Here is the same request with httpx:
<img width="834" alt="Capture d’écran 2024-03-31 à 13 16 52" src="https://github.com/aio-libs/aiohttp/assets/85891169/3ec3cbca-e6a7-4032-9bed-d4349dd36d3b">

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
If they're expired, then it's probably a deliberate design decision to drop them...
Your screenshot shows cookies expiring in 2025 though, so unless your clock is wrong, they should not be hidden...

**Comment by novitae** [comment]
> Your screenshot shows cookies expiring in 2025 though, so unless your clock is wrong, they should not be hidden...

Or maybe I'm a time traveler.

Anyway I switched to httpx that works fine
