### ISSUE TITLE
Reserve generic property on app to store app state in a typed fashion

### ISSUE THREAD

**Issue by grigory-bogush** [fafhrd91/aiohttp#8285]
Hello. I would like to have the ability to have typed properties on application instance so that I don't have to do extra casts and look up dictonary key names that are set during app initalization every time I need to access something on the app.

I saw the argument below and wanted to ask for a sensible compomise to ensure typing works well. I would sugggest to reserve a property called `app_state` that is fully generic and is set during app creating in the constructor (thus inheriting type that is passed).

That way (for example) dataclass can be created to have everything in the app in one place and typed properly

**The original argument**:

Software design is always a compromise.
Honestly, I never need to use an aggregator but push all needed properties into application's dictionary.
For type checking you can use a little helper:
```
def foo(app: Application) -> FooType:
    return cast(FooType, app['FOO_LABEL'])
```
I understand that the solution is not ideal.
Maybe we need to come up with a better solution but it should be not an inheritance.

Suppose you have something like
```
class MyApp(Application):
    def foo(self):
        return something
```

Eventually, in aiohttp we decided to add a `foo` attribute to the base class. As the result, code is broken in a hard way. Depending on how did you add your `foo` and how `foo` is added to base application one implementation wins. Which one is a complex question: instance attribute overrides a class method, but if a class declared a property the property setter is called and so on.

Replacing string keys for application storage with a [ContextVar-styled](https://docs.python.org/3/library/contextvars.html#contextvars.ContextVar) object is an interesting idea.
It can solve the static typing problem and avoid names clashing. I did not experiment with it yet though.

_Originally posted by @asvetlov in https://github.com/aio-libs/aiohttp/issues/2691#issuecomment-456570012_

**Comment by Dreamsorcerer** [comment]
https://docs.aiohttp.org/en/stable/web_advanced.html#application-s-config

If you care about type safety etc. you should probably enable warnings (`python -Wall` or `python -We` for example) which would already have sent you to that page.
