### ISSUE TITLE
aiohttp does not support concurrent requests exceeding 500.

### ISSUE THREAD

**Issue by yunhungo** [fafhrd91/aiohttp#8419]
### Describe the bug

Concurrent requests over 500 will result in a "connect ECONNRESET" error, which seems to be random. I've noticed that the server uses the loop.create_server API, but locally, this API can support more than 10,000 concurrent requests. Could there be an issue with aiohttp's implementation?

### To Reproduce

Create an aiohttp web service and use a script to simulate 1000 concurrent requests. The requests at the end might result in errors.

### Expected behavior

No error

### Logs/tracebacks

```python-traceback
connect ECONNRESET
```

### Python Version

```console
3.10.13
```

### aiohttp Version

```console
latest
```

### multidict Version

```console
None
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

macOS & Linux

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by CaerDarrow** [comment]
This problem may be related with exceeding system socket count. Try increasing "ulimit -n"

**Comment by Dreamsorcerer** [comment]
If this is still a problem, please provide a complete reproducer of the issue and whether the above suggestion makes any difference.
