### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by emdneto** [fafhrd91/aiohttp#8435]
### Describe the bug

When accessing https://docs.aiohttp.org/ there's no documentation

### To Reproduce

Access https://docs.aiohttp.org/ on browser

### Expected behavior

Documentation must be shown

### Logs/tracebacks

```python-traceback
intersphinx inventory 'https://aiohttp.readthedocs.io/en/stable/objects.inv' not readable due to ValueError: unknown or unsupported inventory version: ValueError('invalid inventory header: <!doctype html>')
```

### Python Version

```console
$ python --version
```

### aiohttp Version

```console
$ python -m pip show aiohttp
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
```

### OS

macOS

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
#8434
