### ISSUE TITLE
aiohttp.org site is down

### ISSUE THREAD

**Issue by aslonnie** [fafhrd91/aiohttp#8437]
### Describe the bug

<img width="736" alt="image" src="https://github.com/aio-libs/aiohttp/assets/95255098/3e1049a1-3275-4b21-98e5-19495bb0355a">

seems that domain expired..

### To Reproduce

visit https://docs.aiohttp.org/ in firefox

chrome will refuse the show the page due to third-party cookie

### Expected behavior

docs should show

### Logs/tracebacks

```python-traceback
n/a
```

### Python Version

```console
n/a
```

### aiohttp Version

```console
n/a
```

### multidict Version

```console
n/a
```

### yarl Version

```console
n/a
```

### OS

macos

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
#8434
