### ISSUE TITLE
Support for sending Trailer headers

### ISSUE THREAD

**Issue by SamStephens** [fafhrd91/aiohttp#8452]
### Is your feature request related to a problem?

In order to create a custom runtime for AWS Lambda, if you are streaming responses, [errors need to be reported using Trailer headers](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html#runtimes-custom-response-streaming).

### Describe the solution you'd like

The ability to provide Trailer headers as part of doing https://docs.aiohttp.org/en/stable/client_quickstart.html#streaming-uploads

### Describe alternatives you've considered

There's no alternatives I know of, and no Python HTTP client libraries support Trailer headers that I can find.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
#1652

I've personally not seen anything using trailer headers before, so demand seems to be very low. If you'd like to take a look at implementing it though, we can take a look at a PR.

**Comment by webknjaz** [comment]
IIRC the parser handles them but we don't expose the API. It's good to have this feature, I think. The typical use-case is that the client could upload something, reading it from disk in chunks and calculate the SHA-256 hash or similar. It can be expensive for the client to pre-load it into memory and pre-calculate the entire hash but would be efficient while streaming. In case of the server, it's also more efficient to combine stream processing with validation for efficiency reasons.
