### ISSUE TITLE
Weak Etag can not trigger negotiation caching

### ISSUE THREAD

**Issue by yangjiawen-qaq** [fafhrd91/aiohttp#8462]
### Describe the bug

![image](https://github.com/aio-libs/aiohttp/assets/62173522/d1cb7997-1f18-490b-a440-6338e06406c1)
If the above code is a weak Etag, the judgment logic in the any function will not be executed, and finally return False, resulting in the failure of the negotiation cache. Why can't the weak Etag judge that etag.value==etag_value? Is there something wrong with this implementation?

### To Reproduce

Return the resource file through web.FileResponse, and convert the returned Etag into a weak Etag, that is, add the W/ prefix

### Expected behavior

Weak Etag can also trigger negotiation caching

### Logs/tracebacks

```python-traceback
none
```

### Python Version

```console
Python 3.10.11
```

### aiohttp Version

```console
3.9.1
```

### multidict Version

```console
6.0.4
```

### yarl Version

```console
1.9.4
```

### OS

Linux

### Related component

Server

### Code of Conduct

- [ ] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
> Why can't the weak Etag judge that etag.value==etag_value?

> An origin server MUST use the strong comparison function when comparing entity tags for If-Match
https://datatracker.ietf.org/doc/html/rfc9110#section-13.1.1-2

> A recipient MUST use the weak comparison function when comparing entity tags for If-None-Match
https://datatracker.ietf.org/doc/html/rfc9110#section-13.1.2-2

So, I think the latter is implemented incorrectly. You don't provide any information on how you're using it though, so not sure which one you are trying to use.
