### ISSUE TITLE
aiohttp cannot be used in python 3.14.

### ISSUE THREAD

**Issue by AraHaan** [fafhrd91/aiohttp#8476]
### Describe the bug

This is because they have already removed ``typing.ByteString`` that is used inside of ``payload.py``.

They suggest either replacing it with ``bytes | bytearray`` or [collections.abc.Buffer](https://docs.python.org/3/library/collections.abc.html#collections.abc.Buffer). For use as an ABC, prefer [Sequence](https://docs.python.org/3/library/collections.abc.html#collections.abc.Sequence) or [collections.abc.Buffer](https://docs.python.org/3/library/collections.abc.html#collections.abc.Buffer).

### To Reproduce

Clone the CPython main branch and build, then install pip and aiohttp.

Next try to run some code that depends on the latest version of aiohttp.

### Expected behavior

Everything to work as aiohttp would be prepared for the removal of ``typing.ByteString``. Preparing it now before it becomes stable is a good idea as then it requires less work later.

### Logs/tracebacks

```python-traceback
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "__init__.py", line 8, in <module>
  File "__init__.py", line 23, in <module>
  File "client.py", line 49, in <module>
  File "__init__.py", line 6, in <module>
  File "client.py", line 38, in <module>
  File "payload.py", line 10, in <module>
ImportError: cannot import name 'ByteString' from 'typing' (C:\Users\User\OneDrive\Desktop\DiscordBot\pcbuild\bin\lib.zip\typing.pyc)
```
```


### Python Version

```console
$ python --version
3.14.0a0
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.9.5
```

### multidict Version

```console
$ python -m pip show multidict
6.0.5
```

### yarl Version

```console
$ python -m pip show yarl
1.9.4
```

### OS

Windows

### Related component

Server, Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by AraHaan** [comment]
Seems the change already happened, but waiting a new release so I can get those changes.

https://github.com/aio-libs/aiohttp/pull/8408

**Comment by webknjaz** [comment]
Alright, so we don't need to track it, then.

**Comment by Dreamsorcerer** [comment]
More to the point, if you are running CPython from source, you can do the same with aiohttp, just checkout the 3.10 branch.

**Comment by AraHaan** [comment]
I tried the 3.10 branch however the build fails, even when I manually invoke ``cython`` prior to ``setup.py bdist_wheel`` with the 3.14 self-built interpreter (it fails to copy the vendor include files and then properly allow them to be included..

And yes I am trying to build it on Windows.
