### ISSUE TITLE
With forced TLSv1.3, still TLSv1.0 Client Hello is sent

### ISSUE THREAD

**Issue by C0D3D3V** [fafhrd91/aiohttp#8478]
### Describe the bug

It looks like https://bbb-lb.uni-paderborn.de only configured TLS1.3. But aiohttp is not able to connect to this site. Requests does the request without problem. In Wireshark I see that aiohttp sends a TLS Client Hello with version 1.0, but requests sends a Client hello with version 1.3. The same is the case for curl and wget, curl sends an TLSv1.3 Client Hello, wget not, and so wget can not connect to the website.

Forcing requests to use TLS1.2 (so that it sends an TLSv1.2 Client hello), then it also can not connect to the server.

Is this considered a bug, or is this expected because the `bbb-lb.uni-paderborn.de` server is misconfigured? 

### To Reproduce

Simple Script for testing:

```
import asyncio

import aiohttp
import requests


async def async_fetch(url):
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as response:
            return await response.text()


def fetch(url):
    response = requests.get(url)
    return response.text


async def main():
    url = "https://bbb-lb.uni-paderborn.de"
    content = fetch(url)
    print(f"Result sync: {content}")
    content = await async_fetch(url)
    print(f"Result async: {content}")


asyncio.run(main())
```

### Expected behavior

Some option to allow aiohttp to connect to such misconfigured servers.

### Logs/tracebacks

```python-traceback
Connection timeout to host https://bbb-lb.uni-paderborn.de
```

### Python Version

```console
$ python --version
Python 3.12.3
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.9.5
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /home/daniel/Desktop/other_repos/bbb-download/.venv/lib/python3.12/site-packages
Requires: aiosignal, attrs, frozenlist, multidict, yarl
Required-by: bbb-dl
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/daniel/Desktop/other_repos/bbb-download/.venv/lib/python3.12/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.4
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /home/daniel/Desktop/other_repos/bbb-download/.venv/lib/python3.12/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Arch Linux  6.8.9-arch1-1

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by C0D3D3V** [comment]
Ufff, this only works because I first make the request via requests. If you comment out 
```
content = fetch(url)
print(f"Result sync: {content}")
```
it does not work

**Comment by C0D3D3V** [comment]
After digging deeper, I found out, that the version fields are not the problem. Sorry for bothering you.

**Comment by C0D3D3V** [comment]
For anyone who is interested, the problem is that no ALPN extension is used by aiohttp, thats why the (haproxy?) reverse proxy used by the university ignored the client hello. The requests library and curl default uses the ALPN extension. If you use the --no-alpn flag on curl it can also not connect. 

requests uses urllib3, that automatically sets the alpn correct, see https://github.com/search?q=repo%3Aurllib3%2Furllib3%20set_alpn_protocols&type=code 

If anyone needs to fix this too: We can get the same behavior if you set the alpn option in your ssl context like this: `ssl_context.set_alpn_protocols(['http/1.1']])`

**Comment by Dreamsorcerer** [comment]
As far as I can see, ALPN is initiated by a client. So, it's a bug in proxy that it won't work without ALPN at all.

I wonder if it's worth setting this by default though? I'm not clear exactly what tradeoffs this might make, but from a quick read, I think the benefit is faster connection as the protocol is decided up-front without an extra roundtrip, while the drawback is advertising the protocol in cleartext (but, that doesn't really appear to be a security issue if we're just advertising HTTP versions).
