### ISSUE TITLE
Http query character encoding issues

### ISSUE THREAD

**Issue by Zhaobudaoyuema** [fafhrd91/aiohttp#8486]
### Describe the bug

When executing a GET request, I encountered an issue related to the encoding of parentheses characters in the query string. The expected encoded characters should be %28 and %29, but instead, the unencoded parentheses () were transmitted.

The url I entered：
![image](https://github.com/aio-libs/aiohttp/assets/66905526/254d05fe-babb-4886-83d7-92e4bd61d8fd)

Encoded URL：
![image](https://github.com/aio-libs/aiohttp/assets/66905526/5a6a587e-ca16-47a3-8a8b-64804612f912)

This will cause the signature verification of the request I initiated to fail

### To Reproduce

Any query with% 28% 29 will be converted to ()

### Expected behavior

Keep the original %28 and %29 without decoding

### Logs/tracebacks

```python-traceback
async with self._session.request(method, url, timeout=timeout) as response:
The most basic get request, with% 28,% 29 in the query
```

### Python Version

```console
$ python --version 3.10.13
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.9.5
```

### multidict Version

```console
$ python -m pip show multidict
```

### yarl Version

```console
$ python -m pip show yarl
1.9.4
```

### OS

win10

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Use a pre-encoded URL:
https://docs.aiohttp.org/en/stable/client_quickstart.html#passing-parameters-in-urls
