### ISSUE TITLE
FastAPI integration

### ISSUE THREAD

**Issue by pavelschon** [fafhrd91/aiohttp#8487]
### Is your feature request related to a problem?

Given I have:
* FastAPI `app` object with `/` endpoint.
* aiohttp client session object called `session`.

Now I want to call
```python
response = await session.get("/")
```

and expect it to trigger endpoint `/` on the `app` object, within the same event loop, while not making any http connection inside.

Similar library httpx has something similar, I could do:

```python
app = FastAPI(...)
with AsyncClient(transport=ASGITransport(app=app, client=("1.2.3.4", 123)), base_url="http://test") as client:
    response = await client.get("/")
```

Here the `ASGITransport` is the bridge between the client and FastAPI `app`.

AFAIK this is not possible with `aiohttp`.

### Describe the solution you'd like

see above

### Describe alternatives you've considered

Use httpx instead.

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
We just merged this 3rd-party library into the docs:
https://github.com/aio-libs/aiohttp/pull/8473

I think that achieves what you're looking for?
