### ISSUE TITLE
Doc Add ConnectionResetError exception to ClientWebSocketResponse documentation

### ISSUE THREAD

**Issue by leszekhanusz** [fafhrd91/aiohttp#8505]
### Is your feature request related to a problem?

In the documentation, for [send_json](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientWebSocketResponse.send_json), [send_str](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientWebSocketResponse.send_str), [send_bytes](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientWebSocketResponse.send_bytes), it should be noted that those methods will raise a `ConnectionResetError` if the transport is closing.

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
@bdraco This looks wrong to me? ConnectionResetError is a built-in, not part of our exception hierarchy. Should we be raising such exceptions? Or converting them into all into ClientConnectionErrors?

I think the web side suppresses these exception web_protocol.py (catching ConnectionError), but there are probably a couple of places on the client side that this can be thrown.

**Comment by bdraco** [comment]
I think they should be `ClientConnectionError`, but we probably need a new exception that is also derived from `ConnectionResetError` and `ClientConnectionError` like we do with `ClientOSError` https://github.com/aio-libs/aiohttp/blob/11a96fcc7b62b33f0088640a05237e262cac5691/aiohttp/client_exceptions.py#L129 to be back-compat
