### ISSUE TITLE
Expiring the cookie jar is unexpectedly expensive

### ISSUE THREAD

**Issue by bdraco** [fafhrd91/aiohttp#8575]
### Describe the bug

![clear_cookie_jar](https://github.com/user-attachments/assets/0a553c8a-1592-490d-9a16-7b41bbb9819e)

### To Reproduce

I think the trace source if python-kasa since it clear the cookie jar on every connection

### Expected behavior

clear should be fast

### Logs/tracebacks

```python-traceback
n/a
```

### Python Version

```console
n/a
```

### aiohttp Version

```console
3.10.0
```

### multidict Version

```console
n/a
```

### yarl Version

```console
n/a
```

### OS

Linux

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment]
Its the 350000 calls to `.items()`

**Comment by bdraco** [comment]
Not a regression but noticed it while investigating another issue

**Comment by Dreamsorcerer** [comment]
Is this because they use a predicate? It's not clear how much we could improve it if they want to use predicate..

**Comment by bdraco** [comment]
Yes they use a predicate.  I usually stew on these type of issues for a bit until I come up with a better algorithm to reduce the overhead.  Sometimes they never get solved but often it just takes me a long time to reach a solution.

**Comment by bdraco** [comment]
heapq is probably the solution... but those type of constructs are always a bit painful to get right

**Comment by Dreamsorcerer** [comment]
The predicate would still need to run against every morsel, right?

The only way I see of reducing that is to completely change the predicate API, so it can do something like skipping the entire cookie for a `(domain. path)` key without checking the individual morsels. It'd probably also need to have a good idea of whether the majority of cookies will be kept or deleted, if the latter then it can just store the ones to keep, then clear the cookiejar and readd them, instead of deleting all the other cookies one-by-one.

**Comment by bdraco** [comment]
> The predicate would still need to run against every morsel, right?
> 
> The only way I see of reducing that is to completely change the predicate API, so it can do something like skipping the entire cookie for a `(domain. path)` key without checking the individual morsels. It'd probably also need to have a good idea of whether the majority of cookies will be kept or deleted, if the latter then it can just store the ones to keep, then clear the cookiejar and readd them, instead of deleting all the other cookies one-by-one.

Sorry for the lack of clarity, I renamed the issue.  Its seems like its always the call from `_do_expiration` that's show up on the profile so the `heapq` seems like the right solution here.

![expire](https://github.com/user-attachments/assets/ae341905-f37c-49a2-b5de-bcc1e733aad9)

**Comment by Dreamsorcerer** [comment]
Ah, I see, so that has a predicate which is always False, in order to have it evaluate the expiration times. Yeah, a heapq or similar makes sense then.
