### ISSUE TITLE
The `timeout` parameter of `aiohttp.ClientSession` does work for types other than `Union[ClientTimeout, _SENTINEL, None]`

### ISSUE THREAD

**Issue by aucampia** [fafhrd91/aiohttp#8602]
### Describe the bug

The typing for the `timeout` parameter of `aiohttp.ClientSession` is `Union[ClientTimeout, _SENTINEL, None]`

https://github.com/aio-libs/aiohttp/blob/f1e4213fb06634584f8d7a1eb90f5397736a18cc/aiohttp/client.py#L174

but the function is written to also accommodate values for timeout that is of `float` type:

https://github.com/aio-libs/aiohttp/blob/f1e4213fb06634584f8d7a1eb90f5397736a18cc/aiohttp/client.py#L1116-L1124

https://github.com/aio-libs/aiohttp/blob/f1e4213fb06634584f8d7a1eb90f5397736a18cc/aiohttp/client.py#L523-L529

https://github.com/aio-libs/aiohttp/blob/f1e4213fb06634584f8d7a1eb90f5397736a18cc/aiohttp/client.py#L185-L191

### To Reproduce

Write some python code that passes a float/int value to `aiohttp.ClientSession.get(...,timeout=...)`  and run mypy on it.

### Expected behavior

No type error as the code will run correctly.

### Logs/tracebacks

```python-traceback
kron/clients/open_exchange_rates/client.py: note: In member "historical" of class "OpenExchangeRatesApiClient":
  kron/clients/open_exchange_rates/client.py:62: error: Argument "timeout" to "get" of "ClientSession" has incompatible type "int"; expected "ClientTimeout | _SENTINEL | None"  [arg-type]
  Found 1 error in 1 file (checked 2577 source files)
```

### Python Version

```console
$ python --version
Python 3.12.4
```

### aiohttp Version

```console
$ poetry run python -m pip show aiohttp

Name: aiohttp
Version: 3.10.1
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /home/iwana/.cache/pypoetry/virtualenvs/kron-sw1LGez6-py3.12/lib64/python3.12/site-packages
Requires: aiohappyeyeballs, aiosignal, attrs, frozenlist, multidict, yarl
Required-by: gcloud-aio-auth, pytest-aiohttp
```

### multidict Version

```console
$ poetry run python -m pip show multidict

Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /home/iwana/.cache/pypoetry/virtualenvs/kron-sw1LGez6-py3.12/lib64/python3.12/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ poetry run python -m pip show yarl
Name: yarl
Version: 1.9.4
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /home/iwana/.cache/pypoetry/virtualenvs/kron-sw1LGez6-py3.12/lib64/python3.12/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

Fedora Linux 40 (Xfce)

### Related component

Server

### Additional context

```
$ poetry run python -m pip show mypy
Name: mypy
Version: 1.10.1
Summary: Optional static typing for Python
Home-page: https://www.mypy-lang.org/
Author: Jukka Lehtosalo
Author-email: jukka.lehtosalo@iki.fi
License: MIT
Location: /home/iwana/.cache/pypoetry/virtualenvs/kron-sw1LGez6-py3.12/lib64/python3.12/site-packages
Requires: mypy-extensions, typing-extensions
Required-by: 
```

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
It's there for backwards compatibility, but shouldn't be used to ensure forward compatibility with v4. Therefore, it's not in the typing information.

**Comment by Dreamsorcerer** [comment]
The documentation also has not mentioned `float` for many years. Here's the documentation from 3.7.2:
https://docs.aiohttp.org/en/v3.7.2/client_reference.html#aiohttp.ClientSession

**Comment by aucampia** [comment]
> The documentation also has not mentioned `float` for many years. Here's the documentation from 3.7.2 (the oldest I can see on RTD): https://docs.aiohttp.org/en/v3.7.2/client_reference.html#aiohttp.ClientSession

Thanks for the feedback @Dreamsorcerer, we will just change our code to not pass a `float`/`int` then.

Technically, and somewhat pedantically, if you are following SEMVER, then `float` should still be valid, and the type hints should accept that, but alas just not passing `int`/`float` seems sensible due to the forward compatibility benefits.

**Comment by Dreamsorcerer** [comment]
I think we prefer the typing information to help nudge people away from deprecated things. The only reason you didn't have a type error before is because it was `**kwargs: Any`. 3.10 just added `Unpack` support to get all the kwargs typed properly.

**Comment by gandhis1** [comment]
I encountered this issue as well upon a recent upgrade. I understand the motivation behind it, but I'm going to guess that there are a LOT of people who are using it with a `float`/`int` not knowing any better, because comparable libraries like `requests` and `httpx` support numeric values. i.e. such a change is somewhat disruptive
