### ISSUE TITLE
ClientResponse.json() doesn't set status code

### ISSUE THREAD

**Issue by dgilmanAIDENTIFIED** [fafhrd91/aiohttp#8741]
### Describe the bug

When ClientResponse.json() raises a ContentTypeError it doesn't set the HTTP status code in that exception object. Presumably there is a status code available at that point otherwise the call to `read()` inside of `json()` would have thrown an exception? There may be other properties on the ContentTypeError class that can be set.

### To Reproduce

```
try:
    resp.json()  # throws ContentTypeError
except ContentTypeError as exc:
    print(exc.status)  # prints 0, as it was not initialized
```

### Expected behavior

The ContentTypeError is initialized like the rest of the ClientResponseError

### Logs/tracebacks

```python-traceback
n/a
```

### Python Version

```console
3.12.5
```

### aiohttp Version

```console
3.10.3
```

### multidict Version

```console
n/a
```

### yarl Version

```console
n/a
```

### OS

n/a

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment]
It looks like its not copied to the exection

```diff
diff --git a/aiohttp/client_reqrep.py b/aiohttp/client_reqrep.py
index e7b9d3827..785b8d15d 100644
--- a/aiohttp/client_reqrep.py
+++ b/aiohttp/client_reqrep.py
@@ -1127,6 +1127,7 @@ class ClientResponse(HeadersMixin):
                 raise ContentTypeError(
                     self.request_info,
                     self.history,
+                    status=self.status,
                     message=(
                         "Attempt to decode JSON with "
                         "unexpected mimetype: %s" % self.content_type
```

Can you try this diff?

**Comment by bdraco** [comment]
It does inherit from `ClientResponseError` so it is expected to be set. AFAICT this has never been side since it was added

**Comment by bdraco** [comment]
Looks like its never worked https://github.com/aio-libs/aiohttp/commit/ecc8e634cc6613001cb832707a8160eb7e97d4aa
