### ISSUE TITLE
on_request_headers_sent params type was never imported into the top-level file.

### ISSUE THREAD

**Issue by Hadock-is-ok** [fafhrd91/aiohttp#8946]
### Describe the bug

aiohttp.tracing.TraceRequestHeadersSentParams exists in aiohttp/tracing.py, but wasn't imported into \__main_\_.py like the other param types.

### To Reproduce

# file: main.py
import aiohttp
from types import SimpleNamespace

trace_config = aiohttp.TraceConfig()

async def on_request_headers_sent(session: aiohttp.ClientSession, trace_config_ctx: SimpleNamespace, params: aiohttp.TraceRequestHeadersSentParams):
    ...

### Expected behavior

aiohttp.TraceRequestHeadersSentParams would be a valid typehint and no issues would occur.

### Logs/tracebacks

```python-traceback
params: aiohttp.TraceRequestHeadersSentParams
Type of parameter "params" is unknown (PylancereportUnknownParameterType)
(parameter) params: Unknown
```

### Python Version

```console
$ python --version
Python 3.12.4
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.10.3
Location: venv/lib/python3.12/site-packages
Requires: aiohappyeyeballs, aiosignal, attrs, frozenlist, multidict, yarl
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.5
Location: venv/lib/python3.12/site-packages
Requires:
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.4
Location: venv/lib/python3.12/site-packages
Requires: idna, multidict
Required-by: aiohttp, wavelink
```

### OS

macOS Monterey (12.7.6)

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
As you've already identified the solution, it'd be great if you could just put the fix in a PR.

**Comment by Hadock-is-ok** [comment]
> As you've already identified the solution, it'd be great if you could just put the fix in a PR.

If you've said this 4 minutes earlier I'd be able to 😅 
Rest assured I'll get on a pc in ~30 minutes and make one.
