### ISSUE TITLE
Incorrect re-use future in _make_or_get_ssl_context

### ISSUE THREAD

**Issue by historyandfun** [fafhrd91/aiohttp#9020]
### Describe the bug

I meet following error:
```
RuntimeError: Task <Task pending name='Task-2' coro=<async_connect() running at <ipython-input-1-ba65b5596d34>:18>> got Future <Future pending> attached to a different loop
```
After going through the code, it seems the bug is caused by `aiohttp/connector.py::_make_or_get_ssl_context`. There is a global cache _made_ssl_context for asyncio.Future[SSLContext]. However, the cached future is bound to the first loop. When a new call with different loop to _make_or_get_ssl_context, the cached future is not expected because it has the old loop.

The bug exists since 3.10

### To Reproduce

Please see the description.

### Expected behavior

The calls to `client_session.ws_connect(url)` by multiple threads should not throw exception

### Logs/tracebacks

```python-traceback
RuntimeError: Task <Task pending name='Task-2' coro=<async_connect() running at <ipython-input-1-ba65b5596d34>:18>> got Future <Future pending> attached to a different loop
```

### Python Version

```console
$ python --version
3.8
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.10.5
```

### multidict Version

```console
$ python -m pip show multidict
n/a
```

### yarl Version

```console
$ python -m pip show yarl
n/a
```

### OS

Linux

### Related component

Client

### Additional context

N/A

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by bdraco** [comment]
Thats definitely going to be a problem.

This one might be a bit tricky to fix.

**Comment by bdraco** [comment]
It would be very helpful to get to a solution quicker if you could provide an xfail test for this case.

**Comment by historyandfun** [comment]
> It would be very helpful to get to a solution quicker if you could provide an xfail test for this case.

The example code is as following:
```python
import time
import asyncio
import concurrent.futures
import aiohttp
from aiohttp import ClientResponseError

import nest_asyncio

async def async_connect(loop):
    # Start client session and use it to create a websocket with all the connection options provided.
    client_session = aiohttp.ClientSession(loop=loop)
    database_url = "wss://{}:{}/gremlin".format('gremlin_host', 8182)
    return await client_session.ws_connect(database_url)

def test_connect():
    start = time.time()
    loop = asyncio.new_event_loop()
    results = loop.run_until_complete(async_connect(loop))
    print("results=", results, "latency=", time.time()-start)
    return results

def main():
    raw_response_list = []
    with concurrent.futures.ThreadPoolExecutor() as executor:
        res_list = []
        for i in range(5):
            res_list.append(executor.submit(test_connect))
        for res in concurrent.futures.as_completed(res_list):
            raw_response_list.append(res.result())
    print("raw_response_list=", raw_response_list)

nest_asyncio.apply()
main()
```

**Comment by Dreamsorcerer** [comment]
Generally, you shouldn't have multiple loops, which is probably why nobody else has noticed the issue so far.

But, I agree this looks like it should be isolated. @bdraco Shouldn't it just be a cache on an instance, rather than a class variable? Do we need to cache between connectors? (most users only use a single connector for an entire application anyway)

**Comment by bdraco** [comment]
Creating an ssl context is relatively expensive.  I think it’s more common to have a lot of connectors. At least on my Home Assistant installs I see some with up to 40 as each library is making their own.

**Comment by bdraco** [comment]
The simplest and most straightforward fix would be to create the verify and no verify context at import time. The downside is that we end up doing work that may never get used if they don’t make any ssl connections

**Comment by Dreamsorcerer** [comment]
OK, that'd be difficult to deal with then. If we want to handle this case, then we'd need to make that cache loop-local somehow. Maybe a simple solution would be to do a nested dict (`{loop_id: {...}`). Though I'm not clear how much benefit there is in supporting multiple loops.

**Comment by Dreamsorcerer** [comment]
> The simplest and most straightforward fix would be to create the verify and no verify context at import time. The downside is that we end up doing work that may never get used if they don’t make any ssl connections

Oh, I forgot it was only the 2 contexts. That would also work, and avoid recomputing per loop.

**Comment by historyandfun** [comment]
> Generally, you shouldn't have multiple loops, which is probably why nobody else has noticed the issue so far.
> 
> But, I agree this looks like it should be isolated. @bdraco Shouldn't it just be a cache on an instance, rather than a class variable? Do we need to cache between connectors? (most users only use a single connector for an entire application anyway)

The use case of multiple connections in one thread happens when there is a connection pool: https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/python/gremlin_python/driver/client.py

**Comment by Dreamsorcerer** [comment]
> multiple connections

connectors, not connections
