### ISSUE TITLE
MIsing header file

### ISSUE THREAD

**Issue by RandyLBryant** [fafhrd91/aiohttp#9126]
### Describe the bug

I am trying to build and install sacad on Mac OS 11.6.8 using python 3.12.6 and I am getting the following error:

self.initialize_options()
aiohttp/_websocket.c:196:12: fatal error: 'longintrepr.h' file not found
#include "longintrepr.h"
^~~~~~~~~~~~~~~

### To Reproduce

I am trying to build and install sacad on Mac OS 11.6.8 using python 3.12.6 and I am getting the following error:

self.initialize_options()
aiohttp/_websocket.c:196:12: fatal error: 'longintrepr.h' file not found
#include "longintrepr.h"
^~~~~~~~~~~~~~~

### Expected behavior

Need missing header file to build without errors

### Logs/tracebacks

```python-traceback
self.initialize_options()
aiohttp/_websocket.c:196:12: fatal error: 'longintrepr.h' file not found
#include "longintrepr.h"
^~~~~~~~~~~~~~~
```

### Python Version

```console
$ python --version
3.12.6
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Randys-MacBook-Pro:playcd randy$ python -m pip show aiohttp
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/Python3.11/site-packages/pip/__init__.py", line 6
    def main(args: Optional[List[str]] = None) -> int:
                 ^
SyntaxError: invalid syntax
```

### multidict Version

```console
$ python -m pip show multidict
Randys-MacBook-Pro:playcd randy$ python -m pip show multidict
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/usr/local/lib/Python3.11/site-packages/pip/__init__.py", line 6
    def main(args: Optional[List[str]] = None) -> int:
                 ^
SyntaxError: invalid syntax
```

### yarl Version

```console
$ python -m pip show yarl
Randys-MacBook-Pro:playcd randy$ $python -m pip show yarl
-bash: -m: command not found
```

### OS

MAC OS

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
File a report against sacad, they probably pin aiohttp to an old version for no apparent reason.

Also, fix you Python command first. In the same bug report you've said you're using 3.12 and shown logs that show you're running 2.7...

Maybe you need to use `python3` on your machine..
