### ISSUE TITLE
Replace blockdiag

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#9134]
In docs/tracing_reference.rst we use blockdiag to create some diagrams. The project is unmaintained now and causing issues upgrading to latest versions of sphinx.

We need someone to replace these diagrams with an alternative. In the Sphinx documentation, they recommend GraphViz: https://chiplicity.readthedocs.io/en/latest/Using_Sphinx/UsingGraphicsAndDiagramsInSphinx.html

So, the blockdiag statements need to be replaced with graphviz ones.

**Comment by webknjaz** [comment]
I'd look into https://pypi.org/p/sphinx-mermaid

**Comment by shirsakm** [comment]
Hi, I would like work on this issue, but I would need some guidance. Would that be okay?

**Comment by Dreamsorcerer** [comment]
Go ahead. Let us know if you have questions.

**Comment by Dreamsorcerer** [comment]
Personally, I don't mind what is used, as long as it works. If someone wants to take it on, use whatever you want.

I'd note that sphinx-mermaid appears to be about as abandoned as blockdiag, so I'm thinking that graphviz is probably a safer bet.
