### ISSUE TITLE
Disable retry in tests

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#9141]
The client now has retry logic (https://github.com/aio-libs/aiohttp/blob/ba51537349a9acdf4b9d0427c4a21e0fb6a2ae05/aiohttp/client.py#L642), but this logic can mask issues in tests.
We should disable the retry logic by default in tests (e.g. when using TestClient).

**Comment by ShubhAgarwal-dev** [comment]
Can I be assigned this? I will try to get this as part of the hacktoberfest event...

**Comment by Dreamsorcerer** [comment]
Go ahead.

**Comment by ShubhAgarwal-dev** [comment]
Hi Sam, this is my first time contributing to open-source and working with such a huge codebase. Can you guide me a bit on what is required be done..?

**Comment by webknjaz** [comment]
@ShubhAgarwal-dev this needs understanding how the tests work, inspecting them and making sure they disable retries, essentially not hitting the block under the linked line of code. Perhaps, running the tests locally and generating an HTML coverage report would reveal which tests hit said line.

@Dreamsorcerer perhaps we shouldn't mark issues as `Hacktoberfest` when they require deeper context?

**Comment by Dreamsorcerer** [comment]
Well, basically we want the linked line in the original post to always be False. So, we could probably add a new argument to ClientSession, or a private attribute maybe which defaults that variable to True normally, but False in the tests.

The ClientSession for TestClient is created at:
https://github.com/aio-libs/aiohttp/blob/25b67b6fa6d95bae96f7d55ba21a5c09b92f3046/aiohttp/test_utils.py#L296

So, that's where we'll need to pass the parameter or modify the private attribute.

> @Dreamsorcerer perhaps we shouldn't mark issues as `Hacktoberfest` when they require deeper context?

I think the above is sufficient, no need to verify coverage etc. or have deeper knowledge of the code. Once a rough implementation is ready, we can figure out a test to verify the behaviour.

**Comment by Dreamsorcerer** [comment]
I'd probably suggest the private attribute initially, and keep it as an implementation detail. If users ask for this to be configurable in future, then we can consider adding a new parameter.

**Comment by Dreamsorcerer** [comment]
Ah, forgot to update the PR. If you include 'Fixes #9141' in the PR description next time, then the issue would be auto-closed.
