### ISSUE TITLE
add `Sequence[str | int]` typing  in `_RequestOptions.params`

### ISSUE THREAD

**Issue by kiraware** [fafhrd91/aiohttp#9144]
### Describe the bug

I want to send query params with session.get(). with one of the param is a list. Based on the documentation [here](https://docs.aiohttp.org/en/stable/client_quickstart.html#passing-parameters-in-urls), 

>  the library support nested lists ({'key': ['value1', 'value2']}) alternative as well.

So i try to sent with that. And it works. The problem is with the typing, mypy complaining about incompatible type

![image](https://github.com/user-attachments/assets/1b165fd0-5bdd-46a4-96c9-19673d15f7bd)

Output
```console
{
  "args": {
    "key1": "value1",
    "key2": [
      "value2",
      "22"
    ]
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip, deflate",
    "Host": "httpbin.org",
    "User-Agent": "Python/3.12 aiohttp/3.10.5",
    "X-Amzn-Trace-Id": "Root=1-66e7b68c-13c127ab188b8f274cca5ede"
  },
  "origin": "110.110.110.110",
  "url": "http://httpbin.org/get?key1=value1&key2=value2&key2=22"
}
```

I try to find the code that may cause the problem. And i found that params typing is not supporting sequence like str or int. `params: Union[Mapping[str, Union[str, int]], str, None]`. I think this is easy to fix, because it's only the problem with the params type forgot to add `Sequence[str | int]`

### To Reproduce

Use mypy to analyze this code

```python
import asyncio
from typing import Sequence

from aiohttp import ClientSession


async def main() -> None:
    async with ClientSession("http://httpbin.org") as session:
        params: dict[str, str | Sequence[str | int]] = {
            "key1": "value1",
            "key2": ["value2", 22],
        }

        async with session.get("/get", params=params) as resp:
            expect = "http://httpbin.org/get?key1=value1&key2=value2&key2=22"
            assert str(resp.url) == expect
            print(await resp.text())


asyncio.run(main())
```

### Expected behavior

mypy is not complaining about incompatible type

### Logs/tracebacks

```python-traceback
Argument "params" to "get" of "ClientSession" has incompatible type "dict[str, str | Sequence[str | int]]"; expected "Mapping[str, str | int] | str | None"Mypyarg-type
(variable) params: dict[str, str | Sequence[str | int]]
```

### Python Version

```console
Python 3.12.1
```

### aiohttp Version

```console
name         : aiohttp
version      : 3.10.5
description  : Async http client/server framework (asyncio)
```

### multidict Version

```console
name         : multidict
version      : 6.0.5
description  : multidict implementation
```

### yarl Version

```console
name         : yarl
version      : 1.9.11
description  : Yet another URL library
```

### OS

Windows

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
#8564

**Comment by kiraware** [comment]
Ah sorry, i dont find it. Hope it released soon. Thanks for your response
