### ISSUE TITLE
Replace aioredis in example

### ISSUE THREAD

**Issue by Dreamsorcerer** [fafhrd91/aiohttp#9283]
We have aioredis in one of our examples:
https://github.com/aio-libs/aiohttp/blob/master/examples/background_tasks.py

This should be migrated to valkey (aioredis was merged into redis, then redis was forked to valkey to keep it open source).

Should be simple to update the example and then update the requirements files.

**Comment by Cycloctane** [comment]
@Dreamsorcerer I'd like to open a pull request to handle it. I'm using valkey-py to replace aioredis.
