### ISSUE TITLE
issue programmatically overriding ssl certs with 3.10.6

### ISSUE THREAD

**Issue by cosmoselodie** [fafhrd91/aiohttp#9296]
### Describe the bug

hey - not sure how you all will feel about this, and so I welcome alternative solutions.  

I have a discord bot using a library called py-cord and this library ends up using aiohttp - so I'm not a direct consumer of the aiohttp library.  Yesterday I noticed after respinning some of our images with an upgraded set of python libraries that I was getting an issue with our ssl certs that are preventing us to connect to discord.  We've had this issue before, as the windows machines we're using in AWS don't have the proper certs installed, so I use a workaround where I programmatically alter the environment variables to set `SSL_CERT_FILE` using a library called certifi to bypass using system certs and instead use the cert from the certifi package.

Its a bit of a hack, but it essentially looks like this:
```python
import os
import certifi
os.environ["SSL_CERT_FILE"] = certifi.where()
```
This works fine with 3.10.5.  However in 3.10.6 it only works if I'm able to run this code BEFORE aiohttp is imported.  I did some digging in the 3.10.6 release and I found this, which I think may be the culprit:

https://github.com/aio-libs/aiohttp/pull/9029/commits/b740401ebcf6c93360f76e1ccea96f1eb765f60b

My understanding is that this is setting the ssl context at import time and so I speculate that by doing this it prevents me from updating the environment variable `SSL_CERT_FILE` after aiohttp is imported.  I'm totally willing to be wrong here.

I have a need to manipulate where my python app is pulling this cert file and certifi seems to provide the right cert to make my program work.  I don't know of another way to do this without the `SSL_CERT_FILE` environment variable, so if there's another way to update the ssl context after aiohttp imports, I'd gladly take that suggestion.  Alternatively, I wonder if the ssl context truly has to be setup at import time for aiohttp or if there's a way a future version of aiohttp could allow me to somehow update this state at a much higher level in my app (again, just reminding you, i don't call aiohttp directly, I'm using a library called py-cord that uses aiohttp).

For now I have a couple of workarounds - I can force my app to pull 3.10.5 easily enough, or I can inject this hack in an `__init__.py` before most other libraries start importing - but it'd be cool if there was a way to update this SSL_CERT_FILE without worrying about when aiohttp is imported.

Looking forward to your thoughts.

### To Reproduce

to repro, I think you can just do this:

- import aiohttp
- set `SSL_CERT_FILE` in the environment to some cert you install from somewhere.  certifi works
- then try to connect to something using aiohttp that requires that specific cert file and aiohttp will fail because the ssl context won't be updated to use the file you set.

To see it work, just set the `SSL_CERT_FILE` *before* importing aiohttp, and it should connect

### Expected behavior

I can update `SSL_CERT_FILE` anywhere in my program, regardless of where aiohttp is imported, and the ssl context will respect this setting.

### Logs/tracebacks

not really applicable - I basically noodled around with my discord bot until I tracked down which library was causing the connection to fail.  Then I reverted the library, which was aiohttp to 3.10.5 and everything worked.  Following that, I upgraded back to 3.10.6 and then added my SSL_CERT_FILE` hack to happen somewhere before aiohttp was imported and my problem went away.  That's when I dug through the changelogs and found the commit I linked y'all too.

### Python Version

```console
$ python --version
Python 3.10.11
```

### aiohttp Version

```console
$ python -m pip show aiohttp
(ebb) PS C:\Users\Administrator\foo> python -m pip show aiohttp
Name: aiohttp
Version: 3.10.6
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author:
Author-email:
License: Apache 2
Location: c:\programdata\elodiegames\ebb\.venv\lib\site-packages
Requires: aiohappyeyeballs, aiosignal, async-timeout, attrs, frozenlist, multidict, yarl
Required-by: py-cord
```

### multidict Version

```console
$ python -m pip show multidict
(ebb) PS C:\Users\Administrator\foo> python -m pip show multidict
Name: multidict
Version: 6.1.0
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: c:\programdata\elodiegames\ebb\.venv\lib\site-packages
Requires: typing-extensions
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
(ebb) PS C:\Users\Administrator\foo> python -m pip show yarl
Name: yarl
Version: 1.12.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: c:\programdata\elodiegames\ebb\.venv\lib\site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

windows 11 in aws

### Related component

Client

### Additional context

this is aiohttp by was of pycord 2.6.1.  I can downgrade aiohttp while leaving pycord alone and my problem with ssl goes away.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Well, the documented way to use certifi is:
https://docs.aiohttp.org/en/stable/client_advanced.html#example-use-certifi

I wasn't aware of SSL_CERT_FILE. @bdraco Do we want to consider this use case? As an env var, I'm not sure we should worry about it changing during the app lifecycle, certifi can be used explicitly as above or the env could be changed before import..

**Comment by webknjaz** [comment]
> I wasn't aware of SSL_CERT_FILE.

I *think* this is something that OpenSSL is supposed to read, and it depends on how it's compiled, plus it might need to be set before `ssl` is imported…

**Comment by bdraco** [comment]
> I wasn't aware of SSL_CERT_FILE. @bdraco Do we want to consider this use case? As an env var, I'm not sure we should worry about it changing during the app lifecycle, certifi can be used explicitly as above or the env could be changed before import..

We can't provide any guarantees about when the ssl context is created as our top guarantee needs to be not blocking the event loop.

I would highly recommend not using an env var as its always bound to be a bit brittle.  If the env var is set before import time that should always work though.

The safest and best path forward would be to create the ssl context yourself and create your own connector since we have strong guarantees that it will keep working as long as python doesn't change it.

Creation the ssl context example: https://github.com/home-assistant/core/blob/dev/homeassistant/util/ssl.py
Creation of your own connector example: https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/aiohttp_client.py

**Comment by bdraco** [comment]
Once note of caution is that creating the SSLContext does blocking I/O to load certificates from disk so it should be done in the executor or at import time (assuming your code is imported before the event loop starts, or late imports are done in the executor)

**Comment by webknjaz** [comment]
I'd say that the env var should be set outside the Python process even, for consistency. However, maybe we could provide a lifecycle hook that would return our context by default but allow replacing it with user-provided implementations…

On a related note, we should probably encourage the end-users to use https://truststore.rtfd.io in their apps.

**Comment by Dreamsorcerer** [comment]
> maybe we could provide a lifecycle hook that would return our context by default but allow replacing it with user-provided implementations

Isn't that functionally the same as just passing the ssl parameter? I don't see a reason for something new.
