### ISSUE TITLE
3.10.x changed behavior of retrieving headers with mocks

### ISSUE THREAD

**Issue by dblock** [fafhrd91/aiohttp#9297]
### Describe the bug

Coming from https://github.com/opensearch-project/opensearch-py/pull/828 in which 2 tests started failing when upgrading from 3.10.5 to 3.10.6 that wasn't expected.

```
FAILED test_opensearchpy/test_async/test_http_connection.py::TestAsyncHttpConnection::test_basicauth_in_request_session - TypeError: 'coroutine' object is not iterable
FAILED test_opensearchpy/test_async/test_http_connection.py::TestAsyncHttpConnection::test_callable_in_request_session - TypeError: 'coroutine' object is not iterable
```

The code does `response.headers.getall("warning", ())` and before it ended up being the default `()` and now it's an `<coroutine object AsyncMockMixin._execute_mock_call at 0x108757680>`.

The mock setup is fairly straightforward.

```
    @pytest.mark.asyncio  # type: ignore
    @mock.patch("aiohttp.ClientSession.request", new_callable=mock.Mock)
    async def test_basicauth_in_request_session(self, mock_request: Any) -> None:
        async def do_request(*args: Any, **kwargs: Any) -> Any:
            response_mock = mock.AsyncMock()
            response_mock.headers = CIMultiDict()
            response_mock.status = 200
            return response_mock

        mock_request.return_value = aiohttp.client._RequestContextManager(do_request())
```

I tried isolating the change to a smaller repro but couldn't figure it out.

### To Reproduce

1. Check out https://github.com/opensearch-project/OpenSearch-py.
2. `docker run -d -p 9200:9200 -p 9600:9600 -e OPENSEARCH_INITIAL_ADMIN_PASSWORD=myStrongPassword123! -e "discovery.type=single-node" opensearchproject/opensearch:latest`
3. In dev-requirements.txt set `aiohttp==3.10.6`.
4. `nox -rs test-3.10`

If you use 3.10.5 tests will pass.

### Expected behavior

No change between .5 and .6.

### Logs/tracebacks

```python-traceback
N/A
```

### Python Version

```console
$ python --version

3.10
```

### aiohttp Version

```console
Name: aiohttp
Version: 3.10.6
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: 
Author-email: 
License: Apache 2
Location: /Users/dblock/.pyenv/versions/3.11.1/lib/python3.11/site-packages
Requires: aiosignal, async-timeout, attrs, charset-normalizer, frozenlist, multidict, yarl
Required-by:
```

### multidict Version

```console
$  python -m pip show multidict

Name: multidict
Version: 6.0.4
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Location: /Users/dblock/.pyenv/versions/3.11.1/lib/python3.11/site-packages
Requires: 
Required-by: aiohttp, yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.9.2
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl/
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Location: /Users/dblock/.pyenv/versions/3.11.1/lib/python3.11/site-packages
Requires: idna, multidict
Required-by: aiohttp
```

### OS

MacOS

### Related component

Client

### Additional context

I apologize for a pretty high level bug report, but hopefully someone who works on this project can easily spot what has changed in 3.10.6 to cause this.

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
If you're using `async with` then the subtle change is that it now returns `await self._resp.__aenter__()`. If I'm reading correctly, you've just made the resp a `Mock`, so that method will just return another mock. A real response would return itself.

Ultimately, you should probably be using https://docs.aiohttp.org/en/stable/testing.html#aiohttp.test_utils.make_mocked_request
Which would give you a real Request object with the networking parts mocked out.

**Comment by dblock** [comment]
This was very helpful, thank you. Added a mock response class in https://github.com/opensearch-project/opensearch-py/pull/829 that returns `self` from `__aenter__`.
