### ISSUE TITLE
Payload registry has to do a linear search to find payloads

### ISSUE THREAD

**Issue by bdraco** [fafhrd91/aiohttp#9419]
https://github.com/aio-libs/aiohttp/blob/21f5f92a755dc5ac7225b5e76f561553cf86565e/aiohttp/payload.py#L97

There is a note that its inefficent.

We might be able to clean it up by giving each payload a key as part of the base class and then doing a dict lookup instead

**Comment by Dreamsorcerer** [comment]
> We might be able to clean it up by giving each payload a key as part of the base class and then doing a dict lookup instead

Doesn't really work, because it works with isinstance checks, which could be a subclass or an abc. I thought about this previously and didn't think of any improvements. Not sure what zope.interface is though, might be worth looking into.

**Comment by bdraco** [comment]
Maybe if we have a property that is a key thats the same for the subclassed object.. not sure if that will work.  Needs some more thought.

**Comment by Dreamsorcerer** [comment]
Not sure what you mean, the subclasses are e.g. subclass of bytes or (more realistically) a subclass of io.BufferedIO. They are not our classes, just arbitrary types that might be used to store/stream data.

**Comment by bdraco** [comment]
I need to dig at it a bit more to come up with a solution. This one will take a bit of thought so I opened the issue so I don't forget to come back to it.

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by tab1tha** [comment]
Looking at this

**Comment by bdraco** [comment]
We can likely store the payload type() and then do a dict lookup on the type() of the incoming and we get no matches because it's subclasses, fallback to the linear search

**Comment by bdraco** [comment]
We don't have a benchmark for simple post requests which makes this a bit more difficult to quantify what the performance drag of the linear search is.  We should add a benchmark first
