### ISSUE TITLE
RequestInfo is documented to be a namedtuple but its actually a dataclass or attrs

### ISSUE THREAD

**Issue by bdraco** [fafhrd91/aiohttp#9504]
https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientResponse.request_info

It would be about 2x as fast to create if it were a namedtuple though, and although dataclasses are faster to access its rarely accessed so namedtuple probably is a better choice.  frozen dataclasses are also slower to create https://docs.python.org/3.9/library/dataclasses.html#frozen-instances.... and we create them for every request.
> There is a tiny performance penalty when using frozen=True: [__init__()](https://docs.python.org/3.9/reference/datamodel.html#object.__init__) cannot use simple assignment to initialize fields, and must use [object.__setattr__()](https://docs.python.org/3.9/reference/datamodel.html#object.__setattr__).

Additionally the attrs default isn't used on 3.11/3.10 at all

https://github.com/aio-libs/aiohttp/blob/13dc0200d855bdfec1d4c4f3e1c9a1c66f88f1eb/aiohttp/client_reqrep.py#L110

```diff
diff --git a/aiohttp/client_reqrep.py b/aiohttp/client_reqrep.py
index dad7fe78e..1eeaf7068 100644
--- a/aiohttp/client_reqrep.py
+++ b/aiohttp/client_reqrep.py
@@ -105,16 +105,12 @@ class ContentDisposition:
     filename: Optional[str]
 
 
-@attr.s(auto_attribs=True, frozen=True, slots=True)
-class RequestInfo:
+class RequestInfo(NamedTuple):
     url: URL
     method: str
     headers: "CIMultiDictProxy[str]"
-    real_url: URL = attr.ib()
+    real_url: URL
 
-    @real_url.default
-    def real_url_default(self) -> URL:
-        return self.url
 
 
 class Fingerprint:
@@ -401,7 +397,7 @@ class ClientRequest:
     @property
     def request_info(self) -> RequestInfo:
         headers: CIMultiDictProxy[str] = CIMultiDictProxy(self.headers)
-        return RequestInfo(self.url, self.method, headers, self.original_url)
+        return tuple.__new__(RequestInfo, (self.url, self.method, headers, self.original_url))
 
     def update_host(self, url: URL) -> None:
         """Update destination host, port and connection type (ssl)."""
```

**Comment by asvetlov** [comment]
I really doubt if we have the real bottleneck here. Attrs/dataclasses have better human-readable interface than namedtuple, that's why I accepted the current code.

Technically every namedtuple <-> attrs <-> dataclasses change is not 100% backward compatible, that's why I'm not super exciting in mutation of such things. It may slightly break some existing code, which is not good.

**Comment by Dreamsorcerer** [comment]
> Technically every namedtuple <-> attrs <-> dataclasses change is not 100% backward compatible, that's why I'm not super exciting in mutation of such things. It may slightly break some existing code, which is not good.

I think v4 is already migrating from attrs to dataclasses though. So, if we want to make any other changes, we should be able to get them in before the v4 release.

**Comment by bdraco** [comment]
This keeps coming up on production profiles so there is something there. It needs to be benchmarked and quantified first.

**Comment by bdraco** [comment]
One thing to keep in mind is all the profiles I see it on are 3.10 and 3.11 beta so it could not be concern on master

**Comment by bdraco** [comment]
NamedTuple creation is 2.7x faster https://github.com/aio-libs/aiohttp/pull/9692

**Comment by asvetlov** [comment]
Ok, let's do it.

**Comment by bdraco** [comment]
`NamedTuple` seems to make the most sense for cases where we would have `frozen=True` and we create the object on every request.

`attrs` or `dataclasses` seem better for all cases where `frozen=False`

**Comment by bdraco** [comment]
I looked at all the other frozen objects

`Etag` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/helpers.py#L1026
I can't find `Etag` created anywhere ... seems dead code?

`ProxyInfo` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/helpers.py#L232
Only called from `proxies_from_env` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/helpers.py#L266
Can't find any calls to `proxies_from_env` in the code. Is this dead code as well?

`MimeType` called from `parse_mimetype` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/helpers.py#L307C7-L307C15
https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/helpers.py#L315
Its behind an `lru_cache` so its probably not worth optimizing

`ClientTimeout` and `ClientWSTimeout` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/client.py#L197 https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/client_ws.py#L36
Downstream hopefully isn't making these on every request but that seems like its too risky to change since creation is external

`ContentDisposition` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/client_reqrep.py#L103
Only created with multipart so its going to be a lot more rare and probably not worth optimizing for. 
`ContentDisposition` might be worth changing the overhead of the multipart likely makes it moot.

All the traces https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/tracing.py#L224
Downstream hopefully isn't making these on every request but that seems like its too risky to change since creation is external

`FileField` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/web_request.py#L80
Too risky to change since creation is external

`_ErrInfo` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/web_protocol.py#L113
Doesn't happen enough to matter

`StaticDef` and `RouteDef`
https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/web_routedef.py#L58
Created once per route, doesn't matter since its not frequent

`WebSocketReady` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/web_ws.py#L53
Only called in `can_prepare` and likely rarely called at all


Takes aways:

Can we drop `Etag` and `ProxyInfo`.. they look like dead code?  Maybe they are used externally?

The rest of the frozen cases likely aren't worth changing as they don't happen enough to bother optimizing for (and they don't show up in any profiling)

**Comment by bdraco** [comment]
extracted the `Etag` and `ProxyInfo` issue into https://github.com/aio-libs/aiohttp/issues/9699 since its a different concern
