### ISSUE TITLE
WebSocketResponse.close() should wait for a close frame in its timeout window

### ISSUE THREAD

**Issue by lenard-mosys** [fafhrd91/aiohttp#9506]
### Describe the bug

After calling `WebSocketResponse.close()` the server waits for a single message from the client, and if it's not a close message, then it indicates an abnormal closure:

https://github.com/aio-libs/aiohttp/blob/13dc0200d855bdfec1d4c4f3e1c9a1c66f88f1eb/aiohttp/web_ws.py#L489-L506

The problem with this is that a non-close client message might be in flight when the server sends its close message, and this results in an abnormal closure at the server's side, even if the client responds to the close message immediately. Here is the situation I'm describing:

![aiohttp_ws_close_issue_opt](https://github.com/user-attachments/assets/2e367a28-0761-48fe-a32c-95937fa763f1)

To my best understanding this is reported as an abnormal closure on the server side based on the implementation of `WebSocketResponse.close()`.

### To Reproduce

I didn't write a reproducer yet.

### Expected behavior

During the timeout wait for a close message, and discard messages that arrive before that. Only report an abnormal closure if that close message never arrives.

### Logs/tracebacks

```python-traceback
NA
```

### Python Version

```console
all
```

### aiohttp Version

```console
master, as of writing 13dc0200d855bdfec1d4c4f3e1c9a1c66f88f1eb
```

### multidict Version

```console
NA
```

### propcache Version

```console
NA
```

### yarl Version

```console
NA
```

### OS

NA

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Yeah' that doesn't sound right. Feel free to make a PR, or maybe @bdraco might be interested in this one.

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by bdraco** [comment]
fixed via https://github.com/aio-libs/aiohttp/pull/9508
