### ISSUE TITLE
update_cookies in client_reqrep.py has the same performance issue that was solved for the jar itself in #9204

### ISSUE THREAD

**Issue by bdraco** [fafhrd91/aiohttp#9520]
The cookies get recreated every time.  I need to dig into the cookie code some more to see if we can avoid this

https://github.com/aio-libs/aiohttp/blob/d74e51b5cf93eb99a1fb6aa66950a863c7c056ee/aiohttp/client_reqrep.py#L510

https://github.com/aio-libs/aiohttp/pull/9204

<img width="1349" alt="Screenshot 2024-10-21 at 1 44 47 PM" src="https://github.com/user-attachments/assets/d076cd4d-00c6-4a22-8e3e-6f92cd2a1ea8">

**Comment by bdraco** [comment]
<img width="1233" alt="Screenshot 2024-10-17 at 9 55 31 PM" src="https://github.com/user-attachments/assets/ca7ffb41-ad96-494f-bca3-24451cae36b8">

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by bdraco** [comment]
I think we have to wait for https://github.com/python/cpython/pull/126157

**Comment by bdraco** [comment]
If we don't find another solution by the time Python 3.14 is released, we can close this one

**Comment by bdraco** [comment]
I think its unlikely we are going to be able to improve the performance without moving away from stdlib http.cookies.  As the change to improve Morsel creation time is already merged upstream, I think there is nothing left to do but wait so I'm going to close this issue out.
