### ISSUE TITLE
Changes for 3.1.0 through to 3.4.4 appears twice in the changelog

### ISSUE THREAD

**Issue by janusheide** [fafhrd91/aiohttp#9544]
### Describe the bug

changes for 3.1.0 through to 3.4.4 appears twice in the changelog

https://docs.aiohttp.org/en/stable/changes.html#id673
https://docs.aiohttp.org/en/stable/changes.html#id539

### To Reproduce

visit the changelog, e.g. both these points to the changes for 3.4.4

https://docs.aiohttp.org/en/stable/changes.html#id673
https://docs.aiohttp.org/en/stable/changes.html#id539

### Expected behavior

That changes for 3.1.0 through 3.4.4 appeared once in changes.

### Logs/tracebacks

```python-traceback
not relevant
```

### Python Version

```console
not relevany
```

### aiohttp Version

```console
not relevant
```

### multidict Version

```console
not relevant
```

### propcache Version

```console
not relevant
```

### yarl Version

```console
not relevant
```

### OS

not relevant

### Related component

Server, Client

### Additional context

not relevany

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
@webknjaz?

I'm not sure how this is supposed to work, but it looks like the page is produced from concatenating CHANGES.rst to HISTORY.rst, (the latter having all releases till 3.4.4, the former having all from 3.1.0). Is there a reason we have 2 files?

**Comment by webknjaz** [comment]
I think history is from pre-towncrier times. I don't see a reason why they shouldn't be merged. FWIW, I never touched that one so if you want details, it'd need some Git archeology..

**Comment by AchilleasTsiamoulis** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
