### ISSUE TITLE
`Etag` and `ProxyInfo` in `helpers.py` may be dead code

### ISSUE THREAD

**Issue by bdraco** [fafhrd91/aiohttp#9699]
I looked at all the other frozen objects

Takes aways:

Can we drop `Etag` and `ProxyInfo`.. they look like dead code?  Maybe they are used externally?

The rest of the frozen cases likely aren't worth changing as they don't happen enough to bother optimizing for (and they don't show up in any profiling)

Analysis below
-- 
 
`Etag` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/helpers.py#L1026
I can't find `Etag` created anywhere ... seems dead code?

`ProxyInfo` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/helpers.py#L232
Only called from `proxies_from_env` https://github.com/aio-libs/aiohttp/blob/d9dd7b20132bf0a41d9f1c99ed84c1622b3452a4/aiohttp/helpers.py#L266
Can't find any calls to `proxies_from_env` in the code. Is this dead code as well?

**Comment by asvetlov** [comment]
`ETag` is the type of `web.StreamResponse.etag` property.
See #4594

`proxies_from_env` is called for `aiohttp.Session(trust_env=True)`

**Comment by asvetlov** [comment]
I guess both are not hot code, there is no need to convert them into NamedTuple

**Comment by bdraco** [comment]
Thanks

**Comment by bdraco** [comment]
I missed the call in from `get_env_proxy_for_url` since I was only looking outside of helpers

**Comment by asvetlov** [comment]
No problem
