### ISSUE TITLE
`ClientResponseError.request_info.real_url` not include port number

### ISSUE THREAD

**Issue by yolave** [fafhrd91/aiohttp#9720]
### Describe the bug

When a request fails and raises a `ClientResponseError`, when comparing the original url and the one returned by the exception, they don't match because the value returned by `request_info.real_url` do not include the port number. Same situation with `request_info.url`.

### To Reproduce

1. Perform any request (GET, POST, PUT, DELETE, etc)
2. Use a url that includes the port (ie: `http://myurl:8080/path`)
3. Catch the exception and check the value from `ClientResponseError.request_info.real_url`
4. Compare the original url and the one returned by `ClientResponseError.request_info.real_url` and check that the port is not included in the one returned by the exception

### Expected behavior

The url returned by the exception should match the original one used to perform the request

### Logs/tracebacks

```python-traceback
import asyncio
from aiohttp import ClientSession, ClientResponseError

async def run():
    url = "https://www.google.com:443/bad/path"
    try:
        async with ClientSession() as session:
            async with session.request(url=url, method="GET") as response:
                if response.status in range(200, 299):
                    print("Success")
                else:
                    response.raise_for_status()
    except ClientResponseError as ex:
        print(f"{ex.request_info.real_url} != {url}")
        print(f"{ex.request_info.url} != {url}")


if "__main__" == __name__:
    asyncio.run(run())

```

Output:
```
https://www.google.com/bad/path != https://www.google.com:443/bad/path
https://www.google.com/bad/path != https://www.google.com:443/bad/path
```
```


### Python Version

```console
$ python --version
3.9.13
```

### aiohttp Version

```console
$ python -m pip show aiohttp
Name: aiohttp
Version: 3.10.10
Summary: Async http client/server framework (asyncio)
Home-page: https://github.com/aio-libs/aiohttp
Author: None
Author-email: None
License: Apache 2
Requires: aiohappyeyeballs, frozenlist, async-timeout, multidict, aiosignal, yarl, attrs
Required-by: aioresponses
```

### multidict Version

```console
$ python -m pip show multidict
Name: multidict
Version: 6.0.5
Summary: multidict implementation
Home-page: https://github.com/aio-libs/multidict
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache 2
Requires:
Required-by: yarl, aiohttp
```

### propcache Version

```console
$ python -m pip show propcache
Name: propcache
Version: 0.2.0
Summary: Accelerated property cache
Home-page: https://github.com/aio-libs/propcache
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Requires:
Required-by: yarl
```

### yarl Version

```console
$ python -m pip show yarl
Name: yarl
Version: 1.17.1
Summary: Yet another URL library
Home-page: https://github.com/aio-libs/yarl
Author: Andrew Svetlov
Author-email: andrew.svetlov@gmail.com
License: Apache-2.0
Requires: propcache, idna, multidict
Required-by: aiohttp
```

### OS

Edition	Windows 11 Enterprise
Version	23H2
OS build	22631.4391
Experience	Windows Feature Experience Pack 1000.22700.1047.0

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
443 is a bad example

> Output:
> 
> ```
> https://www.google.com/bad/path != https://www.google.com:443/bad/path
> https://www.google.com/bad/path != https://www.google.com:443/bad/path
> ```

real_url is not a str, it's a URL: https://yarl.aio-libs.org/en/latest/api/#yarl.URL
This will be normalised when converted to a str or doing comparisons (443 is the default port, so it's removed):
```
yarl.URL("https://www.google.com/bad/path") == yarl.URL("https://www.google.com:443/bad/path")
```

Port 8080 should appear though.

**Comment by yolave** [comment]
I know both properties are URL, but that doesn't justify that the port should be removed when converted to string. If the request was made using a port, the representation should include it, despite it's a standard port (80 when http, 443 when https) or not.

is this behavior documented anywhere? because this worked until today when I installed the version `3.10.10`.

**Comment by bdraco** [comment]
https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.3
> URI producers and
   normalizers should omit the port component and its ":" delimiter if
   port is empty or if its value would be the same as that of the
   scheme's default.

**Comment by Dreamsorcerer** [comment]
> If the request was made using a port, the representation should include it

Then we'd get weird situations as you've shown above where 2 URLs that request the same resource are not considered equal. Passing a str is just a convenience to save you creating the URL object, you shouldn't expect to get the exact same str when converting a URL object back to str. If you want a reliable comparison, use a URL object and avoid the automatic conversion.

**Comment by asvetlov** [comment]
Moreover, URL normalization is not limited to default ports only. 
I can imagine non-ASCII characters normalization for example.
