### ISSUE TITLE
FTP download broken in client >= 3.10.0

### ISSUE THREAD

**Issue by poofeg** [fafhrd91/aiohttp#9850]
### Describe the bug

aiohttp versions prior 3.9.5 can download file from FTP via HTTP-proxy. But starting from version 3.10.0, this code throws an exception `aiohttp.client_exceptions.NonHttpUrlClientError: ftp://demo:password@test.rebex.net/readme.txt`

### To Reproduce

```python
    async with aiohttp.ClientSession() as session:
        async with session.get(
            'ftp://demo:password@test.rebex.net/readme.txt',
            proxy='http://some-http-proxy:3128'
        ) as resp:
            print(resp.status)
            print(await resp.text())
```

### Expected behavior

FTP url downloaded

### Logs/tracebacks

```python-traceback
-
```

### Python Version

```console
3.10.15
```

### aiohttp Version

```console
>= 3.10.0
```

### multidict Version

```console
6.1.0
```

### propcache Version

```console
0.2.0
```

### yarl Version

```console
1.17.1
```

### OS

macOS

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
Yeah, to avoid other issues, the connectors now explicitly whitelist the protocols they support.

If you want to lie like that and use the ftp protocol to send http requests, you can do this by subclassing TCPConnector and adding ftp to the supported protocols:
https://github.com/aio-libs/aiohttp/blob/a9a0d849bd4ad65724710662e73f29f1e968bfe6/aiohttp/connector.py#L819

**Comment by Dreamsorcerer** [comment]
Probably all you need is:
```
class FTPConnector(TCPConnector):
    allowed_protocol_schema_set = TCPConnector.allowed_protocol_schema_set | frozenset({"ftp"})
```

**Comment by poofeg** [comment]
> Was it ever supposed to work, though? There's `aioftp` for that.

aioftp does not support HTTP proxy
