### ISSUE TITLE
Downstream changes needed to build version 3.11.1

### ISSUE THREAD

**Issue by theamericanaccount** [fafhrd91/aiohttp#9881]
### Describe the bug

Hello,
Im currently building live latest version of `aiohttp` for Life / DogeOS and I think there's a path finding issue in the file `gen.py`.
I'm currently fixing the build downstream on the python-aiohttp-ur.

### To Reproduce

I'm using the aforementioned ur build recipe. Exact details of the commands run are provided in that source andfurther details can be examined on stream.

### Expected behavior

Well it should build.

### Logs/tracebacks

```python-traceback
I'll probably post them if it keeps failing.
```

### Python Version

```console
I'm using Python 3.12.
```

### aiohttp Version

```console
I'm building aiohttp 3.11.1
```

### multidict Version

```console
I'm using multidict 6.0.5
```

### propcache Version

```console
0.2.0
```

### yarl Version

```console
I'm using yarl 1.9.4
```

### OS

Life / DogeOS

### Related component

`tools/gen.py`

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by theamericanaccount** [comment]
Well, I've written the recipe for [propcache](https://github.com/themartiancompany/python-propcache-ur), [packaged](https://github.com/themartiancompany/fur) it and added it as an optional dependency for [aiohttp](https://github.com/themartiancompany/python-aiohttp-ur).
Version 3.11.1 builds with those seds btw.

**Comment by Dreamsorcerer** [comment]
> with those seds

What ones? You've not actually explained the problem and just created a bunch of links to your repositories and tweets...

**Comment by theamericanaccount** [comment]
The `sed`s in the ur build recipe!
If you follow the links and read that very simple PKGBUILD I'm sure you'll get them!
Or I don't know, just build the package yourself if you're interested in finding the issues, which are with the relatives paths in `gen.py` as I've said.
The links had been provided for your convenience, if you've deleted them I guess it's on you finding the sources back!
Feel free to close the issue, it's kinda obvious you're not willing to solve it!
Cheers!

**Comment by theamericanaccount** [comment]
Oh btw @Dreamsorcerer those are not tweets, those are posts! Tweets are a Twitter exclusive word and that's X, not Twitter! Twitter is a decentralized platform on the Gnosis (and other) blockchain now, don't be mistaken!
