### ISSUE TITLE
Cathing internal exceptions

### ISSUE THREAD

**Issue by daniel-kukiela** [fafhrd91/aiohttp#9882]
### Describe the bug

How can I catch errors like this while using `aiohttp.web.Application()`:
```
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Invalid header value char:
  [...]
```
The client-side receives HTTP 400 with the exception text which I want to avoid (and also log the exception using my logger). It does not seem like I can catch it using middleware or override in any way which I would possibly call a bug (unless I'm missing something obvious)

It seems like this is where this unwanted response for the client is being created: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/web_protocol.py#L411

### To Reproduce

1. Create an Application
2. Run the server
3. Send the request with invalid headers

### Expected behavior

A way to catch and handle the error in my app to log it and send back a generic error message

### Logs/tracebacks

```python-traceback
None
```

### Python Version

```console
$ python --version
3.11
```

### aiohttp Version

```console
$ python -m pip show aiohttp
3.8.5
```

### multidict Version

```console
$ python -m pip show multidict
6.0.4
```

### propcache Version

```console
$ python -m pip show propcache
Not installed
```

### yarl Version

```console
$ python -m pip show yarl
1.9.2
```

### OS

Ubuntu 22.04 LTS

### Related component

Server

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
#3287

Feel free to look at making a PR.
