### ISSUE TITLE
A raw built-in TimeoutError / socket.timeout is being let through in rare cases

### ISSUE THREAD

**Issue by jogc** [fafhrd91/aiohttp#9952]
### Describe the bug

A raw Python built-in TimeoutError / socket.timeout is let through in rare cases instead of an aiohttp.ClientError being generated. I would expect it being enough to handle aiohttp.ClientError to write robust code. It happens when socket.recv raises TimeoutError (or socket.timeout in older Python versions) due to recv syscall returning ETIMEDOUT. I'm not able to reproduce it but what I _think_ happened in my case was that the connection was successfully established and right after the machine lost internet connectivity before/during the HTTP request headers being sent which causes Linux to timeout waiting for TCP ACK for the sent data.

This occurred on Python 3.7.3 / aiohttp 3.7.4.post0 but it seems aiohttp 3.8.5 on Python 3.11.2 also doesn't handle TimeoutError. I am not able to test on the latest version(s) sorry.

### To Reproduce

Modify /usr/lib/python3.7/asyncio/selector_events.py by inserting a `raise TimeoutError` before every instance of `recv` being called.

### Expected behavior

I expected an aiohttp.ClientOSError to be raised and since I handle aiohttp.ClientError that would have been enough.

### Logs/tracebacks

```python-traceback
ERROR:asyncio:Fatal read error on socket transport
protocol: <RequestHandler connected>
transport: <_SelectorSocketTransport fd=10 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 110] Connection timed out
```

### Python Version

```console
3.7.3
```

### aiohttp Version

```console
3.7.4.post0
```

### multidict Version

```console
5.1.0
```

### propcache Version

```console
WARNING: Package(s) not found: propcache
```

### yarl Version

```console
1.6.3
```

### OS

Raspbian GNU/Linux

### Related component

Client

### Code of Conduct

- [X] I agree to follow the aio-libs Code of Conduct

**Comment by Dreamsorcerer** [comment]
We're not about to provide updates or try to figure out what is happening from 3 major versions ago. The description is fairly vague, but there's a good chance the issue no longer exists in 3.11. You'll need to test against the current version.

**Comment by jogc** [comment]
Turns out it was related to serving requests, not acting as a client (my application does both), and it has indeed been fixed in later Python versions (tested: 3.13.0). You can close this.

**Comment by webknjaz** [comment]
Ack. Closing. Though, I believe Sam meant aiohttp 3.11, not CPython 3.11. FYI.

**Comment by webknjaz** [comment]
Thanks for the verbose details on the working env!
